In [5]:
import requests
import pandas as pd
from datetime import datetime, timezone
import time
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.colors import BoundaryNorm
from matplotlib.cm import get_cmap
from matplotlib.patches import Patch
import ast
import folium
from folium.plugins import MarkerCluster
import reverse_geocoder as rg
import re
import pycountry
import os
import numpy as np
import geopandas as gpd
import fiona
import sys
from shapely.geometry import Point
from sklearn.cluster import DBSCAN
import ruptures as rpt
from haversine import haversine
import functions as own
from timezonefinder import TimezoneFinder
import zoneinfo
from scipy.stats import gaussian_kde
from scipy.stats import chisquare, kruskal, mannwhitneyu, spearmanr
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from libpysal.weights import lat2W
from libpysal.weights import Queen
from libpysal.weights import DistanceBand
from esda.moran import Moran_Local, Moran
from shapely.geometry import box
import statsmodels.api as sm
from statsmodels.tsa.seasonal import STL
import importlib

In [20]:
importlib.reload(own)

A barchart is created that depicts the hour of the day when observations are made, is created.

In [9]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

df["hour"] = df["created_at_local"].dt.hour
counts = df["hour"].value_counts().reindex(range(24), fill_value=0).sort_index()

ax = counts.plot(kind="bar", color="teal", figsize=(16,9), logy = False)

plt.title("Total Observations per Hour of Day (Local Time)", fontsize=20)
plt.xlabel("Hour of Day", fontsize=17)
plt.ylabel("Number of Observations", fontsize=17)
plt.xticks(rotation=90)

#for p in ax.patches: # absolute counts above bars
#    ax.annotate(
#        f'{int(p.get_height())}', 
#        (p.get_x() + p.get_width() / 2., p.get_height()), 
#        ha='center', 
#        va='bottom', 
#        fontsize=10,
#        xytext=(0, 5),
#        textcoords='offset points',
#        rotation=90
#    )

ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_xticklabels([f"{h:02d}:00-{(h+1)%24:02d}:00" for h in range(24)], rotation=45, ha="right", fontsize=12)
ax.set_axisbelow(True)
ax.set_ylim(0,6500)

plt.savefig(f"../Products/hour_of_day.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_14684\4183465156.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Chi-square goodness-of-fit test

In [5]:
observed = df["hour"].value_counts().sort_index()
chi2, p = chisquare(observed)
expected = observed.sum() / len(observed) # uniform distribution
residuals = (observed - expected) / np.sqrt(expected)
print(f"{chi2}, {p}, \n {residuals}")

48096.0483621203, 0.0,
 hour
0    -49.723428
1    -51.897371
2    -52.332160
3    -52.577910
4    -52.766948
5    -51.670525
6    -44.071177
7    -16.566074
8     50.448076
9     33.415707
10    30.050821
11    43.548171
12    50.277941
13    42.792017
14    46.213614
15    62.300790
16    63.945425
17    58.406597
18    26.043205
19    -2.425994
20   -22.766537
21   -28.229750
22   -37.795099
23   -44.619389
Name: count, dtype: float64

Then, a barchart with the month of the year

In [13]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

df["month"] = df["created_at_local"].dt.month
df["year"] = df["created_at_local"].dt.year
total_obs = df["month"].value_counts().reindex(range(1,13), fill_value=0).sort_index()
years_per_month = df.groupby("month")["year"].nunique()
counts = (total_obs / years_per_month).round(0).astype(int) # because February, March and April are more common than the rest

ax = counts.plot(kind="bar", color="teal", figsize=(16,9), logy = False)

plt.title("Average Observations per Month of Year", fontsize=20)
plt.xlabel("Month of Year", fontsize=17)
plt.ylabel("Number of Observations", fontsize=17)
plt.xticks(rotation=90)

for p in ax.patches: # absolute counts above bars
    ax.annotate(
        f'{int(p.get_height())}', 
        (p.get_x() + p.get_width() / 2., p.get_height()), 
        ha='center', 
        va='bottom', 
        fontsize=10,
        xytext=(0, 5),
        textcoords='offset points',
        rotation=90
    )

ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_xticklabels(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"], rotation=45, ha="right", fontsize=12)
ax.set_axisbelow(True)
ax.set_ylim(0,1000)

plt.savefig(f"../Products/month_of_year.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_14684\3863024384.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Chi-square goodness-of-fit test

In [11]:
observed = df["month"].value_counts().sort_index()
chi2, p = chisquare(observed)
expected = observed.sum() / len(observed) # uniform distribution
residuals = (observed - expected) / np.sqrt(expected)
print(f"{chi2}, {p}, \n {residuals}")

2017.9362715902323, 0.0,
 month
1    -19.297551
2    -11.157024
3      8.906905
4     16.686523
5     24.385938
6     11.526845
7      1.969411
8      0.966883
9     -1.078275
10    -4.286364
11   -13.375952
12   -15.247338
Name: count, dtype: float64

Then, a barchart with the year

In [25]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["month"] = df["created_at_local"].dt.month
df["year"] = df["created_at_local"].dt.year
counts = df["year"].value_counts().reindex(range(2017,2027), fill_value=0).sort_index()

ax = counts.plot(kind="bar", color="teal", figsize=(16,9), logy = False)

# extrapolation for 2026 (after April)
full_years = range(2018, 2026) # 2018 to 2025
april_fracs = []
for y in full_years:
    total = (df["year"] == y).sum()
    until_april = ((df["year"] == y) & (df["month"] <= 4)).sum()
    april_fracs.append(until_april / total)

avg_april_frac = np.mean(april_fracs)

obs_2026_actual = (df["year"] == 2026).sum()
obs_2026_extrap = int(obs_2026_actual / avg_april_frac) - obs_2026_actual
print(obs_2026_actual, obs_2026_extrap, avg_april_frac)

bars = ax.patches
last_bar = bars[-1]  # 2026-Bar
ax.bar(
    last_bar.get_x() + last_bar.get_width() / 2,
    obs_2026_extrap,
    bottom=obs_2026_actual,
    width=last_bar.get_width(),
    color="#90E4C1",
    hatch="//",
    edgecolor="teal",
    label=f"2026 extrapolated (÷{avg_april_frac:.0%} Apr avg)"
)

plt.title("Total Observations per Year", fontsize=20)
plt.xlabel("Year", fontsize=17)
plt.ylabel("Number of Observations", fontsize=17)
plt.xticks(rotation=90)

#for p in ax.patches: # absolute counts above bars
#    ax.annotate(
#        f'{int(p.get_height())}', 
#        (p.get_x() + p.get_width() / 2., p.get_height()), 
#        ha='center', 
#        va='bottom', 
#        fontsize=10,
#        xytext=(0, 5),
#        textcoords='offset points',
#        rotation=90
#    )

ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_xticklabels(["2017 (from Feb onwards)","2018","2019","2020","2021","2022","2023","2024","2025","2026 (extrapolated)"], rotation=45, ha="right", fontsize=12)
ax.set_axisbelow(True)
ax.set_ylim(0,13000)

plt.savefig(f"../Products/year.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_14684\3796041459.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

2481 6074 0.28997957679063646

Chi-square goodness-of-fit test + quadratic regression

In [26]:
observed = df[(df["year"] > 2017) & (df["year"] < 2026)]["year"].value_counts().sort_index()
chi2, p = chisquare(observed)
expected = observed.sum() / len(observed) # uniform distribution
residuals = (observed - expected) / np.sqrt(expected)
print(f"{chi2}, {p}, \n {residuals}")

yearly = df.groupby("year").size().sort_index()

x = yearly.index.values # x (centered)
x_c = x - x.mean()

X = np.column_stack([x_c, x_c**2]) # design matrix
X = sm.add_constant(X)

y = yearly.values

model = sm.OLS(y, X).fit()
print(model.summary())

6817.286334530689, 0.0,
 year
2018   -59.675055
2019    -9.855955
2020    -1.729752
2021    42.075734
2022    13.505481
2023    15.785736
2024    21.788172
2025   -21.894360
Name: count, dtype: float64
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.919
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     39.66
Date:                Wed, 20 May 2026   Prob (F-statistic):           0.000152
Time:                        09:57:27   Log-Likelihood:                -83.236
No. Observations:                  10   AIC:                             172.5
Df Residuals:                       7   BIC:                             173.4
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.036e+04    570.108     18.171      0.000    9011.346    1.17e+04
x1           342.1091    131.190      2.608      0.035      31.893     652.325
x2          -441.6288     51.857     -8.516      0.000    -564.252    -319.005
==============================================================================
Omnibus:                        1.345   Durbin-Watson:                   3.045
Prob(Omnibus):                  0.510   Jarque-Bera (JB):                0.892
Skew:                           0.448   Prob(JB):                        0.640
Kurtosis:                       1.844   Cond. No.                         16.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

And a chart that shows the annual ratio between new and existing users

In [30]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year"] = df["created_at_local"].dt.year

all_years = sorted(df["year"].unique())

seen_users = set()
results = []

for year in all_years:
    year_users = set(df[df["year"] == year]["created_by"].dropna().unique())
    
    new_users = year_users - seen_users
    returning_users = year_users & seen_users
    
    results.append({
        "year": year,
        "new_users": len(new_users),
        "returning_users": len(returning_users),
        "total_users": len(year_users)
    })
    
    seen_users.update(year_users)

result_df = pd.DataFrame(results)

fig, ax = plt.subplots(figsize=(16, 9))

ax.bar(
    result_df["year"],
    result_df["returning_users"],
    label="Returning Users",
    color="teal",
    width=0.6
)
ax.bar(
    result_df["year"],
    result_df["new_users"],
    bottom=result_df["returning_users"],
    label="New Users",
    color="lightblue",
    width=0.6
)

#for _, row in result_df.iterrows():
#    ratio = row["new_users"] / row["total_users"] * 100
#    ax.annotate(
#        f'{ratio:.0f}% new',
#        (row["year"], row["total_users"]),
#        ha='center',
#        va='bottom',
#        fontsize=9,
#        xytext=(0, 5),
#        textcoords='offset points'
#    )

ax.set_xticks(result_df["year"])
ax.set_xticklabels(result_df["year"], rotation=45, ha="right", fontsize=12)
ax.set_title("Annual New vs. Existing Users", fontsize=20)
ax.set_xlabel("Year", fontsize=17)
ax.set_ylabel("Number of Users", fontsize=17)
ax.legend(fontsize=12)
ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_axisbelow(True)
ax.set_ylim(0,700)

plt.savefig("../Products/new_vs_existing_users_annual.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_14684\2263137817.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

And also the monthly ratio between new and existing users

In [2]:
df = pd.read_csv("../CWData_clean7.csv")
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

all_months = sorted(df["year_month"].unique())

seen_users = set()
results = []

for month in all_months:
    month_users = set(df[df["year_month"] == month]["spotted_by"].dropna().unique())
    
    new_users = month_users - seen_users
    existing_users = month_users & seen_users
    
    results.append({
        "year_month": month,
        "new_users": len(new_users),
        "existing_users": len(existing_users),
        "total_users": len(month_users)
    })
    
    seen_users.update(month_users)

result_df = pd.DataFrame(results)
result_df["year_month_dt"] = result_df["year_month"].dt.to_timestamp()

fig, ax = plt.subplots(figsize=(16, 9))

ax.bar(
    result_df["year_month_dt"],
    result_df["existing_users"],
    label="Returning Users",
    color="teal",
    width=20
)
ax.bar(
    result_df["year_month_dt"],
    result_df["new_users"],
    bottom=result_df["existing_users"],
    label="New Users",
    color="lightblue",
    width=20
)

for _, row in result_df.iterrows():
    ratio = row["new_users"] / row["total_users"] * 100
    ax.annotate(
        f'{ratio:.0f}% new',
        (row["year_month_dt"], row["total_users"]),
        ha='center',
        va='bottom',
        fontsize=5.5,
        rotation=90,
        xytext=(0, 2),
        textcoords='offset points'
    )

ax.set_title("Monthly New vs. Existing Users", fontsize=20)
ax.set_xlabel("Month", fontsize=17)
ax.set_ylabel("Number of Users", fontsize=17)
ax.tick_params(axis="x", labelsize=12)
ax.tick_params(axis="y", labelsize=12)
ax.legend(fontsize=12)
ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_axisbelow(True)
ax.set_ylim(0, 200)

plt.savefig("../Products/new_vs_existing_users_monthly.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\2298316351.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

In [3]:
pd.set_option("display.max_rows", None)
result_df

    year_month  new_users  existing_users  total_users year_month_dt
0      2017-02          2               0            2    2017-02-01
1      2017-03          8               2           10    2017-03-01
2      2017-04          3               4            7    2017-04-01
3      2017-05         15               8           23    2017-05-01
4      2017-06          7              13           20    2017-06-01
5      2017-07         11               9           20    2017-07-01
6      2017-08          4              10           14    2017-08-01
7      2017-09         10              16           26    2017-09-01
8      2017-10          2              15           17    2017-10-01
9      2017-11          3               9           12    2017-11-01
10     2017-12          9              10           19    2017-12-01
11     2018-01         29              12           41    2018-01-01
12     2018-02          6              21           27    2018-02-01
13     2018-03          5               9           14    2018-03-01
14     2018-04         25              15           40    2018-04-01
15     2018-05         14              25           39    2018-05-01
16     2018-06         12              20           32    2018-06-01
17     2018-07         12              32           44    2018-07-01
18     2018-08         16              29           45    2018-08-01
19     2018-09         31              27           58    2018-09-01
20     2018-10         10              25           35    2018-10-01
21     2018-11         12              27           39    2018-11-01
22     2018-12         18              23           41    2018-12-01
23     2019-01         11              21           32    2019-01-01
24     2019-02         11              27           38    2019-02-01
25     2019-03         25              25           50    2019-03-01
26     2019-04         47              31           78    2019-04-01
27     2019-05         34              49           83    2019-05-01
28     2019-06         22              51           73    2019-06-01
29     2019-07         16              45           61    2019-07-01
30     2019-08          9              47           56    2019-08-01
31     2019-09         37              38           75    2019-09-01
32     2019-10         15              38           53    2019-10-01
33     2019-11          8              27           35    2019-11-01
34     2019-12         25              31           56    2019-12-01
35     2020-01         18              34           52    2020-01-01
36     2020-02         19              42           61    2020-02-01
37     2020-03         16              36           52    2020-03-01
38     2020-04         15              36           51    2020-04-01
39     2020-05         28              29           57    2020-05-01
40     2020-06        123              46          169    2020-06-01
41     2020-07         39              45           84    2020-07-01
42     2020-08         27              39           66    2020-08-01
43     2020-09         31              48           79    2020-09-01
44     2020-10         34              42           76    2020-10-01
45     2020-11         41              43           84    2020-11-01
46     2020-12         19              46           65    2020-12-01
47     2021-01         35              45           80    2021-01-01
48     2021-02         32              59           91    2021-02-01
49     2021-03         55              66          121    2021-03-01
50     2021-04         42              75          117    2021-04-01
51     2021-05        106              77          183    2021-05-01
52     2021-06         85              48          133    2021-06-01
53     2021-07         25              81          106    2021-07-01
54     2021-08         17              60           77    2021-08-01
55     2021-09         95              54          149    2021-09-01
56     2021-10         21              68           89    2021-10-01
57     2021-11         15              49           64    2021-11-01
58     2021-12         16              50           66    2021-12-01
59     2022-01          9              54           63    2022-01-01
60     2022-02         11              55           66    2022-02-01
61     2022-03         33              60           93    2022-03-01
62     2022-04         32              56           88    2022-04-01
63     2022-05         99              60          159    2022-05-01
64     2022-06         45              49           94    2022-06-01
65     2022-07         14              54           68    2022-07-01
66     2022-08         26              62           88    2022-08-01
67     2022-09         43              64          107    2022-09-01
68     2022-10         35              59           94    2022-10-01
69     2022-11         32              69          101    2022-11-01
70     2022-12         14              58           72    2022-12-01
71     2023-01         27              55           82    2023-01-01
72     2023-02         38              53           91    2023-02-01
73     2023-03         95              80          175    2023-03-01
74     2023-04         36              90          126    2023-04-01
75     2023-05        100              81          181    2023-05-01
76     2023-06         57              58          115    2023-06-01
77     2023-07         13              55           68    2023-07-01
78     2023-08         27              57           84    2023-08-01
79     2023-09         39              61          100    2023-09-01
80     2023-10         29              69           98    2023-10-01
81     2023-11         12              58           70    2023-11-01
82     2023-12          6              49           55    2023-12-01
83     2024-01          7              43           50    2024-01-01
84     2024-02         20              48           68    2024-02-01
85     2024-03         99              55          154    2024-03-01
86     2024-04         66              78          144    2024-04-01
87     2024-05        120              64          184    2024-05-01
88     2024-06         60              66          126    2024-06-01
89     2024-07         25              65           90    2024-07-01
90     2024-08         26              56           82    2024-08-01
91     2024-09         25              55           80    2024-09-01
92     2024-10         34              61           95    2024-10-01
93     2024-11         11              53           64    2024-11-01
94     2024-12          9              48           57    2024-12-01
95     2025-01         12              42           54    2025-01-01
96     2025-02         15              52           67    2025-02-01
97     2025-03         20              53           73    2025-03-01
98     2025-04         59              56          115    2025-04-01
99     2025-05         96              62          158    2025-05-01
100    2025-06         55              44           99    2025-06-01
101    2025-07         29              51           80    2025-07-01
102    2025-08         22              47           69    2025-08-01
103    2025-09         26              39           65    2025-09-01
104    2025-10         31              58           89    2025-10-01
105    2025-11         36              40           76    2025-11-01
106    2025-12         27              48           75    2025-12-01
107    2026-01         37              33           70    2026-01-01
108    2026-02         24              46           70    2026-02-01
109    2026-03         71              68          139    2026-03-01
110    2026-04         39              90          129    2026-04-01

STL decomposition of these data

In [21]:
own.STL_decomposition(result_df, "total_users", "Total Users")
own.STL_decomposition(result_df, "new_users", "New Users")
own.STL_decomposition(result_df, "existing_users", "Existing Users")

Seasonal strength Total Users: 0.779
Trend strength Total Users:    0.840
Seasonal strength New Users: 0.747
Trend strength New Users:    0.528
Seasonal strength Existing Users: 0.602
Trend strength Existing Users:    0.910

Here, monthly maps of observations are created

In [ ]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

monthly_counts = (
    df
    .groupby(["year_month", "latitude", "longitude"])
    .size()
    .reset_index(name="count")
)

world = gpd.read_file(f"../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona").to_crs("+proj=robin")

for month in monthly_counts["year_month"].unique():
    subset = monthly_counts[monthly_counts["year_month"] == month]
    robin_subset = gpd.GeoDataFrame(
        subset,
        geometry=gpd.points_from_xy(subset["longitude"], subset["latitude"]),
        crs="EPSG:4326"
    ).to_crs("+proj=robin")

    fig, ax = plt.subplots(figsize=(16,8))
    
    # draw world map
    world.plot(ax=ax, color="lightgrey", edgecolor="black", linewidth=0.5)
    
    # plot points
    ax.scatter(
        robin_subset.geometry.x,
        robin_subset.geometry.y,
        s=np.log1p(robin_subset["count"]) * 40, # log for radius
        color="teal",
        edgecolor="black",
        linewidth=0.3,
        alpha=0.7
    )

    legend_counts = [1, 10, 50, 100]
    legend_handles = [
        plt.scatter([], [], s=np.log1p(c) * 40, color="teal", edgecolor="black", linewidth=0.3, alpha=0.7, label=str(c))
        for c in legend_counts
    ]
    legend = ax.legend(
        handles=legend_handles,
        title="Observations",
        loc="lower left",
        frameon=True,
        labelspacing=1.5
    )
    legend.get_title().set_fontsize(12)
    for text in legend.get_texts():
        text.set_fontsize(10)
    
    ax.set_title(f"Observations - {month}")
    ax.set_axis_off()
    
    plt.savefig(f"../Products/Monthly_Activity_Maps/map_{month}.png", dpi=300, bbox_inches="tight")
    plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_3356\122382734.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

I'm retrieving the date when the first observation is made, the number of observations and the number of unique users per Country.

In [4]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

first_countries = (
    df
    .groupby("Country")
    .agg(
        first_date = ("created_at_local","min"),
        total_observations = ("created_at_local","count"),
        unique_users = ("created_by","nunique")
    )
    .reset_index()
)

pd.set_option("display.max_rows", None)

first_countries

C:\Users\yanni\AppData\Local\Temp\ipykernel_3356\1938527830.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

,Country,first_date,total_observations,unique_users
0,Afghanistan,2017-07-03 12:47:55,1,1
1,Albania,2019-10-17 13:44:38,1,1
2,Argentina,2018-01-13 10:41:01,64,9
3,Australia,2017-12-12 17:38:56,357,14
4,Austria,2017-03-04 14:28:56,6094,95
5,Bangladesh,2023-05-25 13:25:55,4,2
6,Belgium,2017-08-03 21:09:49,12,7
7,Brazil,2020-09-04 13:40:09,139,45
8,Bulgaria,2019-08-13 15:47:52,25,3
9,Cambodia,2022-02-26 11:52:59,4,2
10,Cameroon,2018-02-09 09:15:58,3,1
11,Canada,2017-05-06 14:48:03,2165,46
12,Chad,2026-01-16 13:00:14,5,1
13,Chile,2018-01-07 18:37:19,943,46
14,China,2019-05-08 12:52:09,86,9
15,Colombia,2020-11-22 21:19:16,15,6
16,Costa Rica,2018-07-17 08:24:14,596,163
17,Croatia,2019-09-22 18:16:41,23,7
18,Cyprus,2019-03-19 07:14:30,536,4
19,Czechia,2018-04-08 19:00:37,39,11
20,Denmark,2020-07-17 10:02:55,7,3
21,Ecuador,2020-05-13 21:49:59,69,23
22,Egypt,2019-05-09 23:24:08,1,1
23,El Salvador,2023-01-19 11:12:56,16,7
24,Estonia,2017-08-10 17:40:41,1531,6
25,Ethiopia,2024-11-06 22:54:37,7,3
26,Falkland Islands (Malvinas),2022-12-06 14:28:09,1,1
27,Finland,2019-07-27 09:19:27,20,3
28,France,2017-03-19 21:21:58,2258,78
29,Georgia,2021-07-26 18:24:47,1,1
30,Germany,2017-03-19 02:22:03,12332,477
31,Ghana,2021-12-14 15:04:46,2,2
32,Greece,2019-05-04 15:14:25,608,23
33,Guatemala,2017-12-13 15:27:11,142,7
34,Holy See (Vatican City State),2018-11-09 07:20:39,5,4
35,Honduras,2019-02-26 06:48:31,2,2
36,Hungary,2019-04-03 18:19:12,176,15
37,Iceland,2024-07-24 19:50:59,3,1
38,India,2018-03-25 19:52:18,16,8
39,Indonesia,2017-07-25 13:34:24,124,11
40,"Iran, Islamic Republic of",2020-05-15 22:10:36,12,3
41,Ireland,2018-10-21 18:47:11,951,41
42,Israel,2022-04-24 22:21:25,1,1
43,Italy,2017-07-06 10:31:09,1478,69
44,Japan,2018-05-18 06:56:32,8,6
45,Kazakhstan,2018-06-15 14:46:19,7,2
46,Kenya,2019-08-25 11:38:48,16,3
47,"Korea, Republic of",2024-05-29 22:34:46,7,1
48,Kyrgyzstan,2019-05-30 17:44:11,742,34
49,Latvia,2017-08-08 20:23:49,4,3
50,Lebanon,2024-05-12 12:36:07,78,7
51,Liechtenstein,2018-05-18 11:18:49,90,4
52,Lithuania,2017-08-07 20:37:49,8,3
53,Luxembourg,2018-07-03 16:43:27,54,9
54,Malaysia,2018-08-02 18:50:43,156,8
55,Malta,2019-03-26 10:16:06,142,4
56,Mexico,2023-09-27 10:23:16,80,9
57,Montenegro,2022-05-23 18:28:00,3,1
58,Morocco,2019-05-30 14:53:03,27,3
59,Mozambique,2024-12-10 11:12:46,1,1
60,Netherlands,2017-10-21 11:21:49,921,125
61,New Zealand,2020-07-10 11:49:20,16,6
62,Nicaragua,2020-01-22 19:14:38,1,1
63,Nigeria,2021-05-03 22:54:17,1,1
64,North Macedonia,2024-10-02 11:14:48,50,5
65,Norway,2018-01-25 13:54:08,147,50
66,Panama,2022-01-17 19:05:52,1,1
67,Peru,2017-07-14 14:49:31,15,5
68,Philippines,2021-04-07 13:11:47,104,85
69,Poland,2020-07-08 18:08:13,21,8
70,Portugal,2019-04-08 15:13:46,410,12
71,Romania,2019-09-02 14:22:39,5,2
72,Russian Federation,2018-04-05 18:52:34,78,5
73,Rwanda,2020-04-25 19:05:13,2,1
74,Saudi Arabia,2025-07-06 11:28:27,1,1
75,Serbia,2021-07-17 18:09:48,28,1
76,Slovakia,2019-04-29 16:22:25,107,6
77,Slovenia,2018-07-19 09:02:14,22,6
78,South Africa,2021-10-27 15:25:19,7,2
79,Spain,2019-03-15 17:08:43,1608,27
80,Svalbard and Jan Mayen,2017-08-15 14:23:29,6,2
81,Sweden,2017-04-08 12:21:27,234,23
82,Switzerland,2017-02-05 14:49:16,22641,1621
83,"Taiwan, Province of China",2020-12-01 05:16:14,2,1
84,"Tanzania, United Republic of",2019-08-28 08:18:16,1,1
85,Thailand,2017-07-08 17:02:32,2,1
86,Trinidad and Tobago,2022-04-24 08:18:35,1,1
87,Uganda,2024-09-18 09:31:03,7,1
88,Ukraine,2022-06-25 09:52:59,1,1
89,United Kingdom,2017-06-17 15:52:31,4539,129
90,United States,2017-05-18 14:07:53,1759,127
91,Uruguay,2021-08-20 14:26:22,32,6
92,Uzbekistan,2020-12-16 16:34:24,1,1

Then, the date of the first observation per country is plotted on a map, this is an overview.

In [ ]:
# uses first_countries

world = gpd.read_file(f"../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})
first_countries["first_date"] = pd.to_datetime(first_countries["first_date"])
first_countries["year"] = first_countries["first_date"].dt.year

bins = [2016, 2017, 2018, 2019, 2020, 2022, 2024, 2026]
labels = ["2017 (Feb-Dec)","2018","2019","2020","2021-2022","2023-2024","2025-2026 (Jan)"]
first_countries["year_bin"] = pd.cut(first_countries["year"], bins=bins, labels=labels)
first_countries["ISO_A3"] = first_countries["Country"].apply(own.get_iso3)

map_df = world.merge(first_countries, left_on="ADM0_A3", right_on="ISO_A3", how="left").to_crs("+proj=robin")

fig, ax = plt.subplots(1, 1, figsize=(16, 8))

cmap = get_cmap("Blues_r", len(labels))
legend_handles = [
    Patch(facecolor=cmap(i / (len(labels) - 1)), edgecolor="black", linewidth=0.5, label=labels[i])
    for i in range(len(labels))
]
legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))

map_df.plot(
    column="year_bin",
    cmap="Blues_r",
    linewidth=0.5,
    edgecolor="black",
    missing_kwds={"color": "grey"},
    legend=False,
    categorical=True,
    ax=ax
)

ax.legend(handles=legend_handles, title="Year", title_fontsize=12, loc="lower left")
ax.set_title("First Observation per Country", fontsize=15)
ax.set_axis_off()

plt.savefig(f"../Products/first_obs_per_Country.png", dpi=300, bbox_inches="tight")
plt.close()

Then, monthly maps of first observations are created (same colors as the one above).

In [ ]:
# uses first_countries

world = gpd.read_file(f"../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})
first_countries["ISO_A3"] = first_countries["Country"].apply(own.get_iso3)
first_countries["first_date"] = pd.to_datetime(first_countries["first_date"])

bins = [2016, 2017, 2018, 2019, 2020, 2022, 2024, 2026]
labels = ["2017 (Feb-Dec)","2018","2019","2020","2021-2022","2023-2024","2025-2026 (Jan)"]
first_countries["year_bin"] = pd.cut(first_countries["first_date"].dt.year, bins=bins, labels=labels)

# sort months
all_months = pd.period_range(first_countries["first_date"].min(), first_countries["first_date"].max() + pd.offsets.MonthEnd(2), freq="M")

# generate monthly maps
saved_files = []
for month in all_months:
    current = first_countries[first_countries["first_date"] <= month.to_timestamp()]
    if current.empty:
        continue
    
    map_df = world.merge(current, left_on="ADM0_A3", right_on="ISO_A3", how="left").to_crs("+proj=robin")
    
    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    cmap = get_cmap("Blues_r", len(labels))
    legend_handles = [
        Patch(facecolor=cmap(i / (len(labels) - 1)), edgecolor="black", linewidth=0.5, label=labels[i])
        for i in range(len(labels))
    ]
    legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))

    map_df.plot(
        column="year_bin",
        cmap="Blues_r",
        linewidth=0.5,
        edgecolor="black",
        missing_kwds={"color": "grey"},
        categorical=True,
        legend=False,
        ax=ax
    )

    ax.legend(handles=legend_handles, title="Year", title_fontsize=12, loc="lower left")
    ax.set_title(f"Countries with Observations up to (including) {month-1}", fontsize=15)
    ax.set_axis_off()
    
    filepath = f"../Products/Monthly_first_obs_Maps/{month-1}.png"
    plt.savefig(filepath, dpi=300, bbox_inches="tight")
    plt.close()

    saved_files.append(filepath) # for the following GIF

In [ ]:
# create GIF

own.gif_maker(*saved_files, path="C:/Studium/X_Masterarbeit/Data/Products/Monthly_first_obs_Maps/Animation", duration=200)

Monthly Maps with active/inactive countries.

In [ ]:
world = gpd.read_file("../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

df["ISO_A3"] = df["Country"].apply(own.get_iso3)

pd.set_option("display.max_columns", None)
df.head(3)

countries_ever = set(df["ISO_A3"].dropna().unique())
all_months = pd.period_range(
    df["year_month"].min(),
    df["year_month"].max(),
    freq="M"
)

for month in all_months:
    
    # countries with observations in this month
    current_active = set(
        df.loc[df["year_month"] == month, "ISO_A3"].dropna().unique()
    )
    
    # copy of world map
    map_df = world.copy().to_crs("+proj=robin")
    
    # create status column
    def classify_country(iso):
        if iso in current_active:
            return "Active"
        elif iso in countries_ever:
            return "Inactive"
        else:
            return "Never active"
    
    map_df["status"] = map_df["ADM0_A3"].apply(classify_country)
    
    # plot
    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    categories = ["Active", "Inactive", "Never active"]
    map_df["status"] = pd.Categorical(map_df["status"], categories=categories)

    # define colors
    cmap = mcolors.ListedColormap(["blue", "#df6a91", "grey"])
    color_map = {
        "Active": "blue",
        "Inactive": "#df6a91",
        "Never active": "grey"
    }

    fig, ax = plt.subplots(1, 1, figsize=(16, 8))

    map_df.plot(
        column="status",
        categorical=True,
        cmap=cmap,
        linewidth=0.5,
        edgecolor="black",
        legend=False,
        ax=ax
    )

    legend_handles = [
        Patch(facecolor=color, edgecolor="black", linewidth=0.5, label=label)
        for label, color in color_map.items()
    ]
    
    ax.legend(handles=legend_handles, title="Country Status", title_fontsize=12, loc="lower left")
    ax.set_title(f"Active Countries in {month}", fontsize=15)
    ax.set_axis_off()
    
    plt.savefig(f"../Products/Monthly_active_Countries_Maps/{month}.png",
                dpi=300, bbox_inches="tight")
    plt.close()

Now do the same thing for actual spots, not whole countries.

In [ ]:
world = gpd.read_file("../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

df["geometry"] = df.apply(
    lambda row: Point(row["longitude"], row["latitude"]), axis=1
)

gdf = gpd.GeoDataFrame(
    df,
    geometry="geometry",
    crs="EPSG:4326"
).to_crs("+proj=robin")

all_months = pd.period_range(
    gdf["year_month"].min(),
    gdf["year_month"].max(),
    freq="M"
)

for month in all_months:

    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    # map below
    world.to_crs("+proj=robin").plot(
        ax=ax,
        color="grey",
        edgecolor="black",
        linewidth=0.5
    )
    
    # active spots in this month
    active = gdf[gdf["year_month"] == month]
    
    # all other spots
    inactive = gdf[gdf["year_month"] < month]
    
    # first plot inactive ones
    inactive.plot(
        ax=ax,
        color="red",
        markersize=5,
        alpha=0.4
    )
    
    # then active ones
    active.plot(
        ax=ax,
        color="blue",
        markersize=8,
        alpha=0.8
    )

    active_patch = mpatches.Patch(facecolor="blue", edgecolor="black", linewidth=0.5, label="Active")
    inactive_patch = mpatches.Patch(facecolor="red", edgecolor="black", linewidth=0.5, label="Inactive")

    legend = ax.legend(
        handles=[active_patch, inactive_patch],
        title="Spot Status",
        loc="lower left",
        frameon=True
    )

    legend.get_title().set_fontsize(12)
    for text in legend.get_texts():
        text.set_fontsize(10)
    
    ax.set_title(f"Active Measurement Spots in {month}", fontsize=16)
    ax.set_axis_off()
    
    plt.savefig(f"../Products/Monthly_active_Spots_Maps/{month}.png",
                dpi=300, bbox_inches="tight")
    plt.close()

Monthly Maps of the number of active users per country

In [ ]:
world = gpd.read_file("../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")
df["ISO_A3"] = df["Country"].apply(own.get_iso3)

countries_ever = set(df["ISO_A3"].dropna().unique())
all_months = pd.period_range(
    df["year_month"].min(),
    df["year_month"].max(),
    freq="M"
)

# define bins
bins = [0, 1, 5, 10, 20, 50, float("inf")]
labels = ["0", "1-5", "6-10", "11-20", "21-50", ">51"]
colors = ["#ffffff", "#9ecae1", "#6baed6", "#3182bd", "#08519c", "#08306b"]
cmap = mcolors.ListedColormap(colors)
norm = mcolors.BoundaryNorm(bins, cmap.N)

legend_handles = [
    Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="Never active"),
    Patch(facecolor="white", edgecolor="black", linewidth=0.5, label="No observations (this month)"),
] + [
    Patch(facecolor=colors[i+1], edgecolor="black", linewidth=0.5, label=labels[i+1])
    for i in range(len(labels)-1)
]

for month in all_months:

    user_counts = (
        df[df["year_month"] == month]
        .groupby("ISO_A3")["spotted_by"]
        .nunique()
    )

    map_df = world.copy().to_crs("+proj=robin")
    map_df["user_count"] = map_df["ADM0_A3"].map(user_counts)

    def assign_value(row):
        if row["ADM0_A3"] not in countries_ever:
            return -1
        elif pd.isna(row["user_count"]):
            return 0
        else:
            return row["user_count"]

    map_df["plot_value"] = map_df.apply(assign_value, axis=1)

    fig, ax = plt.subplots(1, 1, figsize=(16, 8))

    # plot never active countries grey
    map_df[map_df["plot_value"] == -1].plot(
        ax=ax, color="grey", edgecolor="black", linewidth=0.5, zorder=1
    )

    # plot currently inactive countries white
    map_df[map_df["plot_value"] == 0].plot(
        ax=ax, color="white", edgecolor="black", linewidth=0.5, zorder=1
    )

    # plot active countries according to previously specified colors
    map_df[map_df["plot_value"] > 0].plot(
        column="plot_value",
        ax=ax,
        cmap=cmap,
        norm=norm,
        edgecolor="black",
        linewidth=0.5,
        zorder=2,
        legend=False
    )

    ax.legend(
        handles=legend_handles,
        title="Active Users",
        title_fontsize=11,
        fontsize=9,
        loc="lower left"
    )
    ax.set_title(f"Active Users per Country in {month}", fontsize=15)
    ax.set_axis_off()

    plt.savefig(f"../Products/Monthly_active_Users_Maps/{month}.png",
                dpi=300, bbox_inches="tight")
    plt.close()

Now we generate a dataframe with monthly percentages of hydrological variables measured. E.g. for Switzerland, in January 2024, 32% virtual scale, 17% physical scale, 5% soil moisture, 40% plastic pollution, 1% temporary stream, 3% stream type and 2% standing water type MIGHT be observed.

In [18]:
df = pd.read_csv("../CWData_clean7.csv")
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

category_cols = [
    "physical scale",
    "plastic pollution",
    "soil moisture",
    "standing water type",
    "stream type",
    "temporary stream",
    "virtual scale"
]

counts = (
    df
    .groupby(["Country", "year_month", "Category"])
    .size()
    .reset_index(name="n_obs")
)

totals = (
    df
    .groupby(["Country", "year_month"])
    .size()
    .reset_index(name="total_obs")
)

counts = counts.merge(totals, on=["Country","year_month"])
counts["percent"] = round(counts["n_obs"] / counts["total_obs"] * 100,2)

category_percentages = (
    counts
    .pivot_table(
        index=["Country","year_month"],
        columns="Category",
        values="percent",
        fill_value=0
    )
    .reset_index()
)

#category_percentages["year_month"] = category_percentages["year_month"].dt.to_period("M")
full_range = pd.period_range("2017-02", "2026-01", freq="M")
countries = category_percentages["Country"].unique()
full_index = pd.MultiIndex.from_product(
    [countries, full_range],
    names=["Country", "year_month"]
)

category_percentages_full = (
    category_percentages
    .set_index(["Country","year_month"])
    .reindex(full_index)
    .reset_index()
)

category_percentages_full[category_cols] = category_percentages_full[category_cols].fillna(0)
mask = category_percentages_full[category_cols].any(axis=1)
category_percentages_full["top_category"] = None
category_percentages_full.loc[mask, "top_category"] = (
    category_percentages_full.loc[mask, category_cols]
    .idxmax(axis=1)
)

category_percentages_full["ISO_A3"] = category_percentages_full["Country"].apply(own.get_iso3)

C:\Users\yanni\AppData\Local\Temp\ipykernel_3356\2214125278.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

In [22]:
category_percentages_full.head()

Category,Country,year_month,physical scale,plastic pollution,soil moisture,standing water type,stream type,temporary stream,virtual scale,top_category,ISO_A3
0,Afghanistan,2017-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,AFG
1,Afghanistan,2017-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,AFG
2,Afghanistan,2017-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,AFG
3,Afghanistan,2017-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,AFG
4,Afghanistan,2017-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,AFG

Now create monthly maps of the top category

In [ ]:
# uses category_percentages_full

world = gpd.read_file(f"../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona").to_crs("+proj=robin")
countries_with_obs = category_percentages_full["ISO_A3"].unique()

category_colors = {
    "physical scale": "#1418fc",
    "plastic pollution": "#fbff2b",
    "soil moisture": "#82571b",
    "standing water type": "#dd6ef0",
    "stream type": "#fc1471",
    "temporary stream": "#8c14fc",
    "virtual scale": "#14c2fc"
}

months = category_percentages_full["year_month"].unique()

for month in months:

    month_df = category_percentages_full[
        category_percentages_full["year_month"] == month
    ]
    
    map_df = world.merge(
        month_df,
        left_on="ADM0_A3",
        right_on="ISO_A3",
        how="left"
    )

    fig, ax = plt.subplots(1,1, figsize=(16,8))

    # Basemap --> countries without any observations ever
    world.plot(
        ax=ax,
        color="grey",
        edgecolor="black",
        linewidth=0.5
    )

    # countries without observations in this specific month
    no_obs_this_month = map_df[
        (map_df["ADM0_A3"].isin(countries_with_obs)) &
        (map_df["top_category"].isna())
    ]

    if not no_obs_this_month.empty:
        no_obs_this_month.plot(
            ax=ax,
            color="lightgrey",
            edgecolor="black",
            linewidth=0.5
        )

    #countries with observations in this specific month
    for category, color in category_colors.items():
        subset = map_df[map_df["top_category"] == category]
        if not subset.empty:
            subset.plot(
                ax=ax,
                color=color,
                edgecolor="black",
                linewidth=0.5
            )
        
    legend_order = [
        "physical scale",
        "virtual scale",
        "soil moisture",
        "stream type",
        "temporary stream",
        "plastic pollution",
        "standing water type",
        "No observations this month",
        "No observations"
    ]
    legend_handles = [
        Patch(facecolor=category_colors.get(label, "lightgrey" if label == "No observations this month" else "grey"), label=label, edgecolor="black", linewidth=0.5)
        for label in legend_order
    ]
    ax.legend(handles=legend_handles, loc="lower left", title="Category", title_fontsize=12)
    
    ax.axis("off")
    plt.title(f"Dominant CrowdWater Category Type - {month}", fontsize=15)
    plt.savefig(f"../Products/Hydro_Categories/top_category/top_category_{month}.png", dpi=300, bbox_inches="tight")
    plt.close()

And now monthly maps for each category that shows the percentage of observations per country

In [ ]:
def category_plotter(df, category):
    world = gpd.read_file(f"../ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona").to_crs("+proj=robin")
    countries_with_obs = df["ISO_A3"].unique()
    months = df["year_month"].unique()

    bins = [0, 20, 40, 60, 80, 100]
    labels = ["0-20%", ">20-40%", ">40-60%", ">60-80%", ">80-100%"]
    bin_col = category + "_binned"

    cmap = get_cmap("Blues", len(labels))
    legend_handles = [
        Patch(facecolor=cmap(i / (len(labels) - 1)), label=labels[i], edgecolor="black", linewidth=0.5, )
        for i in range(len(labels))
    ]
    
    legend_handles.append(Patch(facecolor="lightgrey", edgecolor="black", linewidth=0.5, label="No observations this month"))
    legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))
    
    for month in months:
        month_df = df[df["year_month"] == month].copy()
        month_df[bin_col] = pd.cut(month_df[category], bins=bins, labels=labels, include_lowest=True)
        month_df["_codes"] = month_df[bin_col].cat.codes
        
        map_df = world.merge(
            month_df,
            left_on="ADM0_A3",
            right_on="ISO_A3",
            how="left"
        )

        fig, ax = plt.subplots(1, 1, figsize=(16, 8))
        world.plot(ax=ax, color="grey", edgecolor="black", linewidth=0.5)
        
        map_df[map_df["ADM0_A3"].isin(countries_with_obs)].plot(
            ax=ax, color="lightgrey", edgecolor="black", linewidth=0.5
        )

        subset = map_df[map_df[category] > 0].copy()
        if not subset.empty:
            subset.plot(
                column="_codes", cmap="Blues", legend=False,
                vmin=0, vmax=len(labels) - 1,
                ax=ax, edgecolor="black", linewidth=0.5
            )

        ax.legend(handles=legend_handles, loc="lower left", title=f"% of observations", title_fontsize=12)
        ax.axis("off")
        plt.title(f"Share of Observations in Category {category.title()} - {month}", fontsize=15)
        plt.savefig(f"../Products/Hydro_Categories/{category.replace(' ', '_')}/{category.replace(' ', '_')}_{month}.png", dpi=300, bbox_inches="tight")
        plt.close()

In [ ]:
# uses category_percentages_full

categories = ["physical scale",
            "virtual scale",
            "soil moisture",
            "stream type",
            "temporary stream",
            "plastic pollution",
            "standing water type"
        ]
for category in categories:
    category_plotter(category_percentages_full, category)

And also create a graph that shows average percentages for each country, yearly

In [ ]:
# uses category_percentages_full

cat_cols = ["physical scale", "virtual scale", "soil moisture", "stream type", "temporary stream", "plastic pollution", "standing water type"]

country_totals = category_percentages_full.groupby("Country")[cat_cols].sum() # sum per country

country_pct = country_totals.div(country_totals.sum(axis=1), axis=0) * 100 # percentages per country

country_pct = country_pct.sort_values("Country", ascending=False) # sort alphabetically

colors = ["#1418fc", "#14c2fc", "#82571b", "#fc1471", "#8c14fc", "#fbff2b", "#dd6ef0"]
color_dict = dict(zip(cat_cols, colors))

fig, ax = plt.subplots(figsize=(12, len(country_pct) * 0.4))

lefts = pd.Series([0.0] * len(country_pct), index=country_pct.index)

for cat, color in color_dict.items():
    vals = country_pct[cat]
    ax.barh(
        country_pct.index,
        vals,
        left=lefts,
        color=color,
        label=cat,
        edgecolor="none"
    )
    lefts += vals

ax.set_xlim(0, 100)
ax.set_ylim(-0.5, len(country_pct) - 0.5)
ax.set_xlabel("Percentage of Observations (%)", fontsize=12)
ax.set_title("Observation Categories per Country", fontsize=15)
ax.grid(axis="x", linestyle="--", color="black", alpha=0.8)

patches = [mpatches.Patch(facecolor=color_dict[cat], label=cat) for cat in cat_cols]
ax.legend(handles=patches, bbox_to_anchor=(1.01, 1), loc="upper left", fontsize=10, frameon=True)

plt.savefig("../Products/Hydro_Categories/barchart_category_per_country.png", dpi=300, bbox_inches="tight")
plt.close()