In [71]:
import requests
import pandas as pd
from datetime import datetime, timezone
import time
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.colors import BoundaryNorm
from matplotlib.cm import get_cmap
from matplotlib.patches import Patch
import matplotlib.dates as mdates
import ast
import folium
from folium.plugins import MarkerCluster
import reverse_geocoder as rg
import re
import pycountry
import os
import numpy as np
import geopandas as gpd
import fiona
import sys
from shapely.geometry import Point
from sklearn.cluster import DBSCAN
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RepeatedKFold, cross_val_score
from sklearn.inspection import permutation_importance
from sklearn.inspection import PartialDependenceDisplay
from sklearn.model_selection import LeaveOneOut
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
import ruptures as rpt
from haversine import haversine
import functions as own
from timezonefinder import TimezoneFinder
import zoneinfo
from itertools import product
from scipy.stats import spearmanr
import seaborn as sns
from geopy.distance import geodesic
import wbgapi as wb
from IPython.display import display
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

Distance to Zurich: Mean or Median distance of all observations in a country to Zurich (47.3717, 8.5422)

In [13]:
df = pd.read_csv("../CWData_clean7.csv")

Zurich_coords = (47.3717, 8.5422)

# mean and median coordinates per country
df["distance_to_zurich_km"] = df.apply(
    lambda row: geodesic((row["latitude"], row["longitude"]), Zurich_coords).km, axis=1
)

distance_per_country = (
    df.groupby("Country")
    .agg(
        total_observations=("created_by", "size"),
        distance_to_zurich_km_mean=("distance_to_zurich_km", "mean"),
        distance_to_zurich_km_median=("distance_to_zurich_km", "median"),
    )
    .reset_index()
)

distance_per_country = distance_per_country[distance_per_country["total_observations"] >= 10].reset_index(drop=True)

pd.set_option("display.max_rows", None)
distance_per_country

C:\Users\yanni\AppData\Local\Temp\ipykernel_38788\1866434761.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

,Country,total_observations,distance_to_zurich_km_mean,distance_to_zurich_km_median
0,Argentina,110,12401.684666,13259.754221
1,Australia,357,16004.245814,16232.804061
2,Austria,6247,454.266481,360.414399
3,Belgium,18,395.622967,368.974988
4,Brazil,148,9366.525604,9423.963887
5,Bulgaria,25,1318.665636,1294.777419
6,Canada,2175,7538.529621,7854.139757
7,Chile,947,12341.412200,12338.268890
8,China,85,8036.545453,7437.518515
9,Colombia,15,8965.976002,8804.712298
10,Costa Rica,629,9406.644138,9401.194710
11,Croatia,19,587.808529,597.879900
12,Cyprus,542,2472.423434,2470.756479
13,Czechia,43,627.745564,635.646630
14,Ecuador,69,10023.012848,10019.927380
15,El Salvador,16,9506.018901,9506.659511
16,Estonia,1681,1710.404546,1718.844389
17,Finland,21,1835.402623,1781.672639
18,France,2293,537.222893,554.249583
19,Germany,12720,375.125286,374.406748
20,Greece,612,1699.812676,1708.457643
21,Guatemala,237,9418.978208,9419.438109
22,Hungary,182,781.029327,747.169305
23,India,18,7361.409245,7418.815460
24,Indonesia,124,11147.331711,11141.667480
25,Iran,12,3400.938393,3238.685283
26,Ireland,966,1340.442836,1327.946728
27,Italy,1431,967.757421,1153.733978
28,Kenya,18,6021.615968,6012.222258
29,Kyrgyzstan,785,5107.085838,5069.850952
30,Lebanon,86,2739.435649,2739.409078
31,Liechtenstein,25,75.100460,74.762549
32,Luxembourg,52,304.986303,305.795860
33,Malaysia,156,10027.854110,9981.518758
34,Malta,142,1359.932728,1361.300115
35,Mexico,80,9762.551721,9816.432440
36,Morocco,27,2211.717005,2244.003923
37,Netherlands,926,598.996399,607.071270
38,New Zealand,16,18702.152470,18711.564347
39,North Macedonia,83,1171.185337,1175.878482
40,Norway,153,1553.935868,1407.543760
41,Peru,15,10594.277114,10618.575458
42,Philippines,104,10702.676365,10668.390979
43,Poland,23,966.686545,1038.114471
44,Portugal,410,1776.462752,1773.760197
45,Russia,80,2284.419402,2110.691273
46,Serbia,28,945.841821,945.710081
47,Slovakia,110,768.733523,726.744947
48,Slovenia,23,455.469075,425.025647
49,Spain,1611,967.545375,966.238248
50,Sweden,249,1676.832274,1549.995573
51,Switzerland,24086,41.161799,14.677115
52,United Kingdom,5419,867.188261,828.140695
53,United States of America,1991,6790.587347,6131.664081
54,Uruguay,28,11135.809171,11152.573063

Get population, population density, area, GDP per capita for each country

In [46]:
world_area = gpd.read_file("../Borders/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp", engine="fiona")
world_area = world_area.to_crs("ESRI:54009")
world_area["area_km2"] = world_area.geometry.area / 1e6
country_attrs = world_area[["ADM0_A3", "area_km2"]].copy()

indicators = {
    "SP.POP.TOTL": "population",
    "NY.GDP.PCAP.CD": "gdp_per_capita",
    "EN.POP.DNST": "pop_density",
}

wb_df = wb.data.DataFrame(list(indicators), time=2023, labels=False).reset_index()
wb_df = wb_df.rename(columns={"economy": "ADM0_A3", **indicators})

edu_df = pd.read_csv("../Education_Index/Education_index.csv", sep=";", encoding="utf-8-sig")
edu_df = edu_df[["ADM0_A3", "Education_Index"]]

regression_data = distance_per_country.copy()
regression_data["ADM0_A3"] = regression_data["Country"].apply(own.get_iso3)
regression_data = regression_data.merge(wb_df, on="ADM0_A3", how="left")
regression_data = regression_data.merge(country_attrs, on="ADM0_A3", how="left")
regression_data = regression_data.merge(edu_df, on="ADM0_A3", how="left")

regression_data = regression_data[regression_data["ADM0_A3"] != "CHE"]

regression_data

,Country,total_observations,distance_to_zurich_km_mean,distance_to_zurich_km_median,ADM0_A3,pop_density,gdp_per_capita,population,area_km2,Education_Index
0,Argentina,110,12401.684666,13259.754221,ARG,16.639956,14261.846567,4.553840e+07,2.789349e+06,0.872819
1,Australia,357,16004.245814,16232.804061,AUS,3.465919,65058.377315,2.665992e+07,7.723183e+06,0.929000
2,Austria,6247,454.266481,360.414399,AUT,110.661185,56579.504175,9.131761e+06,8.394346e+04,0.864390
3,Belgium,18,395.622967,368.974988,BEL,386.303732,55244.681458,1.177995e+07,3.062973e+04,0.922988
4,Brazil,148,9366.525604,9423.963887,BRA,25.261688,10377.589279,2.111407e+08,8.523997e+06,0.719532
5,Bulgaria,25,1318.665636,1294.777419,BGR,59.382793,15854.019289,6.446596e+06,1.128203e+05,0.807280
6,Canada,2175,7538.529621,7854.139757,CAN,4.556884,54847.537011,4.004909e+07,9.916644e+06,0.903674
7,Chile,947,12341.412200,12338.268890,CHL,26.464725,17081.518074,1.965884e+07,7.380176e+05,0.846158
8,China,85,8036.545453,7437.518515,CHN,150.264001,12951.178240,1.410710e+09,9.394406e+06,0.697838
9,Colombia,15,8965.976002,8804.712298,COL,47.157415,7012.491691,5.232115e+07,1.142648e+06,0.697897
10,Costa Rica,629,9406.644138,9401.194710,CRI,99.990697,17140.771430,5.105525e+06,5.147549e+04,0.748982
11,Croatia,19,587.808529,597.879900,HRV,68.972230,22183.498226,3.859686e+06,5.502309e+04,0.857286
12,Cyprus,542,2472.423434,2470.756479,CYP,145.560173,36623.707031,1.344976e+06,5.407600e+03,0.869012
13,Czechia,43,627.745564,635.646630,CZE,140.785548,31761.594410,1.086404e+07,7.867298e+04,0.898592
14,Ecuador,69,10023.012848,10019.927380,ECU,72.395245,6718.144794,1.798008e+07,2.567290e+05,0.711546
15,El Salvador,16,9506.018901,9506.659511,SLV,304.518533,5319.719527,6.309624e+06,2.066218e+04,0.552025
16,Estonia,1681,1710.404546,1718.844389,EST,32.068476,30264.006489,1.370286e+06,4.567821e+04,0.895624
17,Finland,21,1835.402623,1781.672639,FIN,18.370545,52864.693158,5.583911e+06,3.316773e+05,0.932654
18,France,2293,537.222893,554.249583,FRA,126.862021,44700.138418,6.837229e+07,6.371612e+05,0.839276
19,Germany,12720,375.125286,374.406748,DEU,238.351810,54776.766824,8.328727e+07,3.571768e+05,0.957357
20,Greece,612,1699.812676,1708.457643,GRC,80.739728,23343.710396,1.040735e+07,1.315376e+05,0.885129
21,Guatemala,237,9418.978208,9419.438109,GTM,169.138093,5754.428339,1.812484e+07,1.094373e+05,0.491511
22,Hungary,182,781.029327,747.169305,HUN,105.108328,22208.650982,9.592186e+06,9.315475e+04,0.840760
23,India,18,7361.409245,7418.815460,IND,483.679010,2434.448263,1.438070e+09,3.165389e+06,0.589182
24,Indonesia,124,11147.331711,11141.667480,IDN,148.576922,4876.299296,2.811901e+08,1.892367e+06,0.660346
25,Iran,12,3400.938393,3238.685283,IRN,55.845120,5049.299316,9.060871e+07,1.627124e+06,0.749566
26,Ireland,966,1340.442836,1327.946728,IRL,77.101727,106818.917131,5.311538e+06,6.931506e+04,0.890833
27,Italy,1431,967.757421,1153.733978,ITA,199.459678,39279.699782,5.898422e+07,3.013514e+05,0.825221
28,Kenya,18,6021.615968,6012.222258,KEN,95.268137,1942.588028,5.533900e+07,5.896371e+05,0.606215
29,Kyrgyzstan,785,5107.085838,5069.850952,KGZ,37.016423,2138.222102,7.099750e+06,1.991575e+05,0.755360
30,Lebanon,86,2739.435649,2739.409078,LBN,564.368817,3477.724898,5.773493e+06,1.002958e+04,0.670194
31,Liechtenstein,25,75.100460,74.762549,LIE,249.037500,206780.590353,3.984600e+04,1.371836e+02,0.841793
32,Luxembourg,52,304.986303,305.795860,LUX,258.862053,133230.619179,6.664300e+05,2.605605e+03,0.818478
33,Malaysia,156,10027.854110,9981.518758,MYS,106.913097,11386.039564,3.512630e+07,3.300722e+05,0.721789
34,Malta,142,1359.932728,1361.300115,MLT,1727.334375,40932.523877,5.527470e+05,3.263700e+02,0.855964
35,Mexico,80,9762.551721,9816.432440,MEX,66.740276,13830.843849,1.297398e+08,1.966640e+06,0.713542
36,Morocco,27,2211.717005,2244.003923,MAR,84.500347,3813.726074,3.771250e+07,5.937568e+05,0.625350
37,Netherlands,926,598.996399,607.071270,NLD,530.950906,63515.603078,1.787712e+07,3.733703e+04,0.922332
38,New Zealand,16,18702.152470,18711.564347,NZL,19.748585,49302.341876,5.200000e+06,2.687124e+05,0.929433
39,North Macedonia,83,1171.185337,1175.878482,MKD,72.474861,8674.358463,1.827816e+06,2.540575e+04,0.751596
40,Norway,153,1553.935868,1407.543760,NOR,15.152500,90984.408714,5.519601e+06,3.803884e+05,0.937265
41,Peru,15,10594.277114,10618.575458,PER,26.441888,7919.046348,3.384562e+07,1.298027e+06,0.752638
42,Philippines,104,10702.676365,10668.390979,PHL,385.321122,3804.082741,1.148912e+08,2.950901e+05,0.688659
43,Poland,23,966.686545,1038.114471,POL,119.787616,22145.266065,3.668735e+07,3.129170e+05,0.903570
44,Portugal,410,1776.462752,1773.760197,PRT,115.475189,27634.618314,1.057817e+07,9.150743e+04,0.809187
45,Russia,80,2284.419402,2110.691273,RUS,8.782272,13986.995117,1.438261e+08,1.692397e+07,0.779921
46,Serbia,28,945.841821,945.710081,SRB,78.763028,12281.707946,6.623183e+06,7.764402e+04,0.805895
47,Slovakia,110,768.733523,726.744947,SVK,112.868968,24614.873464,5.426740e+06,4.841655e+04,0.851964
48,Slovenia,23,455.469075,425.025647,SVN,105.314808,32660.475358,2.120461e+06,2.032193e+04,0.917184
49,Spain,1611,967.545375,966.238248,ESP,96.763617,33493.222541,4.835253e+07,5.074615e+05,0.853824
50,Sweden,249,1676.832274,1549.995573,SWE,25.871368,54950.283473,1.053663e+07,4.444898e+05,0.924678
52,United Kingdom,5419,867.188261,828.140695,GBR,283.247220,49919.689662,6.852600e+07,2.432804e+05,0.944419
53,United States of America,1991,6790.587347,6131.664081,USA,36.814211,82586.784771,3.367551e+08,9.469009e+06,0.905972
54,Uruguay,28,11135.809171,11152.573063,URY,19.358250,23378.639973,3.388081e+06,1.778368e+05,0.836999

Random forest regression with population, GDP per capita and median distance to Zurich as dependent, and number of observations as independent variable

Log transformation of number of observations

In [48]:
d = regression_data.dropna(subset=["total_observations", "population", "gdp_per_capita", "distance_to_zurich_km_median", "area_km2", "Education_Index"]).copy()

d["log_obs"] = np.log10(d["total_observations"])
d["log_pop"] = np.log10(d["population"])
d["log_gdp"] = np.log10(d["gdp_per_capita"])
d["log_dist"] = np.log10(d["distance_to_zurich_km_median"].clip(lower=1))
d["log_area"] = np.log10(d["area_km2"])

In [ ]:
features = ["log_pop", "log_gdp", "log_dist", "log_area", "Education_Index"]
X = d[features]
y = d["log_obs"]

# collinearity
display(X.corr().round(2))

                 log_pop  log_gdp  log_dist  log_area  Education_Index
log_pop             1.00    -0.41      0.47      0.86            -0.31
log_gdp            -0.41     1.00     -0.55     -0.28             0.82
log_dist            0.47    -0.55      1.00      0.58            -0.47
log_area            0.86    -0.28      0.58      1.00            -0.12
Education_Index    -0.31     0.82     -0.47     -0.12             1.00

In [73]:
final_features = ["log_pop", "log_gdp", "log_dist"]
final_X = d[final_features]
final_y = d["log_obs"]

loo = LeaveOneOut()

rf = RandomForestRegressor(
    n_estimators=1000,
    min_samples_leaf=3,      #against overfitting
    max_features=2,
    random_state=1,
    oob_score=True,
)

y_true_rf, y_pred_rf = [], []
for train_idx, test_idx in loo.split(final_X):
    X_train, X_test = final_X.iloc[train_idx], final_X.iloc[test_idx]
    y_train, y_test = final_y.iloc[train_idx], final_y.iloc[test_idx]
    rf.fit(X_train, y_train)
    pred = rf.predict(X_test)
    y_true_rf.append(y_test.values[0])
    y_pred_rf.append(pred[0])

rf_loo_r2 = r2_score(y_true_rf, y_pred_rf)
print(f"RF LOO CV R²: {rf_loo_r2:.3f}")

rf.fit(final_X, final_y)
print(f"OOB R²: {rf.oob_score_:.3f}")

# Permutation Importance instead of impurity-based
perm = permutation_importance(rf, final_X, final_y, n_repeats=50, random_state=42, scoring="r2")
imp = pd.DataFrame({
    "feature": final_features,
    "importance": perm.importances_mean,
    "std": perm.importances_std,
}).sort_values("importance", ascending=False)
display(imp)

RF LOO CV R²: 0.143
OOB R²: 0.161

    feature  importance       std
1   log_gdp    0.752247  0.142724
0   log_pop    0.455328  0.075637
2  log_dist    0.136888  0.016758

In [80]:
n = len(final_features)
ncols = 2
nrows = -(-n // ncols)

fig, axes = plt.subplots(nrows, ncols, figsize=(10, 4*nrows))
axes = axes.flatten()

feature_labels = {
    "log_gdp": "log(GDP per capita)",
    "log_pop": "log(Population)",
    "log_dist": "log(Distance to Zurich)"
}

display = PartialDependenceDisplay.from_estimator(
    rf, final_X, final_features,
    ax=axes[:n],
    line_kw={"color": "teal", "linewidth": 2}
)

for ax, feat in zip(axes[:n], final_features):
    for coll in ax.collections:
        coll.remove()
    
    ax.set_xlabel(feature_labels.get(feat, feat), fontsize=13)
    ax.set_ylabel("Partial dependence", fontsize=13)
    ax.tick_params(labelsize=11)
    ax.grid(axis="both", linestyle="--", alpha=0.4)

for ax in axes[n:]:
    ax.axis("off")


fig.suptitle("Partial Dependence: Random Forest Regression (Country Level)", fontsize=16)

plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.savefig("../Products/RF_partial_dependence.png", dpi=300, bbox_inches="tight")
plt.close()

"Normal" Multiple Regression

In [75]:
lr = LinearRegression()

y_true_lr, y_pred_lr = [], []
for train_idx, test_idx in loo.split(final_X):
    X_train, X_test = final_X.iloc[train_idx], final_X.iloc[test_idx]
    y_train, y_test = final_y.iloc[train_idx], final_y.iloc[test_idx]
    lr.fit(X_train, y_train)
    pred = lr.predict(X_test)
    y_true_lr.append(y_test.values[0])
    y_pred_lr.append(pred[0])

lr_loo_r2 = r2_score(y_true_lr, y_pred_lr)
print(f"OLS LOO CV R²: {lr_loo_r2:.3f}")

# statsmodels für Koeffizienten/p-Werte bleibt unverändert
X_ols = sm.add_constant(final_X)
ols_model = sm.OLS(final_y, X_ols).fit()
ols_model.summary()

OLS LOO CV R²: 0.076

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                log_obs   R-squared:                       0.231
Model:                            OLS   Adj. R-squared:                  0.185
Method:                 Least Squares   F-statistic:                     4.997
Date:                Fri, 25 Sep 2026   Prob (F-statistic):            0.00415
Time:                        08:20:14   Log-Likelihood:                -57.201
No. Observations:                  54   AIC:                             122.4
Df Residuals:                      50   BIC:                             130.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6013      1.851     -1.946      0.057      -7.319       0.116
log_pop        0.3225      0.139      2.316      0.025       0.043       0.602
log_gdp        0.8291      0.252      3.296      0.002       0.324       1.334
log_dist      -0.0364      0.222     -0.164      0.870      -0.481       0.409
==============================================================================
Omnibus:                        2.622   Durbin-Watson:                   2.420
Prob(Omnibus):                  0.270   Jarque-Bera (JB):                1.970
Skew:                           0.300   Prob(JB):                        0.373
Kurtosis:                       2.282   Cond. No.                         173.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [76]:
X_vif = sm.add_constant(final_X)

vif_data = pd.DataFrame()
vif_data["feature"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]
vif_data

    feature         VIF
0     const  351.614331
1   log_pop    1.346761
2   log_gdp    1.494941
3  log_dist    1.603446