In [2]:
import requests
import pandas as pd
from datetime import datetime, timezone
import time
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.colors import BoundaryNorm
from matplotlib.cm import get_cmap
from matplotlib.patches import Patch
import ast
import folium
from folium.plugins import MarkerCluster
import reverse_geocoder as rg
import re
import pycountry
import os
import numpy as np
import geopandas as gpd
import fiona
import sys
from shapely.geometry import Point
from sklearn.cluster import DBSCAN
import ruptures as rpt
from haversine import haversine
import functions as own
from timezonefinder import TimezoneFinder
import zoneinfo

Now, we create plots for every country and every first order region with daily observation counts and running monthly means.

In [3]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

df["date"] = pd.to_datetime(df["date"])

start_date = pd.to_datetime("2017-02-01")
end_date   = pd.to_datetime("2026-01-31")

def plot_country(country, split_by_year=True):
    base_path = f"../Products/Timelines_by_Country/{country}"
    os.makedirs(base_path, exist_ok=True)

    df_filtered = df[df["Country"] == country].copy()
    _plot(df_filtered, base_path, title=country, filename_prefix=country, split_by_year=split_by_year)

def plot_region(country, region, split_by_year=True):
    
    base_path = f"../Products/Timelines_by_Country/{country}/regions/{region}"
    os.makedirs(base_path, exist_ok=True)

    df_filtered = df[(df["Country"] == country) & (df["Region"] == region)].copy()
    _plot(df_filtered, base_path, title=f"{country} - {region}", filename_prefix=f"{country}_{region}", split_by_year=split_by_year)

def _plot(df_filtered, base_path, title, filename_prefix, split_by_year=True):
    # internal helping function
    
    full_range = pd.date_range(start=start_date, end=end_date, freq="D")

    daily = (
        df_filtered
        .groupby("date")
        .size()
        .rename("daily_observations")
        .reindex(full_range, fill_value=0)
    )
    rolling_30 = daily.rolling(window=30, min_periods=1).mean()
    data = pd.DataFrame({"daily": daily, "rolling_30": rolling_30})

    # Full plot
    _save_plot(data.index, data["daily"], data["rolling_30"], 
               title=title, 
               path=f"{base_path}/timeline_{filename_prefix}_full.png")

    if split_by_year:
        for year in range(2017, 2027):
            start = pd.to_datetime(f"{year}-01-01")
            end   = pd.to_datetime(f"{year}-12-31")
            if year == 2017: start = pd.to_datetime("2017-02-01")
            if year == 2026: end   = pd.to_datetime("2026-01-31")

            df_year = data.loc[start:end]
            if df_year["daily"].sum() == 0:
                continue

            _save_plot(df_year.index, df_year["daily"], df_year["rolling_30"],
                       title=f"{title} - {year}",
                       path=f"{base_path}/timeline_{filename_prefix}_{year}.png")

def _save_plot(index, daily, rolling, title, path):
    
    plt.figure(figsize=(16, 8))
    plt.plot(index, daily)
    plt.plot(index, rolling)
    plt.title(title, fontsize=15)
    plt.xlabel("Date")
    plt.ylabel("Observations")
    plt.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.6)
    plt.legend(["Daily observations", "Running 30-day mean"], loc="upper right")
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_3488\3695409245.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

In [4]:
for country in df["Country"].unique():
    plot_country(country)

for (country, region) in df[["Country", "Region"]].drop_duplicates().values:
    plot_region(country, region)

Make dataframes of daily observations in each and every first order subregion and in every country of the world, in order to later detect events in the data (=unusual patterns with spikes in observations).

In [5]:
df = pd.read_csv("../CWData_clean7.csv")
df["date"] = pd.to_datetime(df["date"])

daily_region = (
    df
    .groupby(["Country", "Region", "date"])
    .size()
    .rename("daily_obs")
    .reset_index()
)

daily_country = (
    df.groupby(["Country", "date"])
    .size()
    .rename("daily_obs")
    .reset_index()
)

C:\Users\yanni\AppData\Local\Temp\ipykernel_3488\423652575.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

calculate z-score (using daily observations, 60-day mean observation counts and 60-day standard deviation) for every day for every region and every country.

In [6]:
# uses daily_country and daily_region

full_range = pd.date_range("2017-02-01", "2026-01-31", freq="D")

all_regions = []

for (country, region), group in daily_region.groupby(["Country", "Region"]):

    d = group.set_index("date").sort_index()
    d = d.reindex(full_range)
    d["daily_obs"] = d["daily_obs"].fillna(0)
    d["Country"] = country
    d["Region"] = region
    d["mean_60"] = d["daily_obs"].rolling(60).mean()
    d["std_60"]  = d["daily_obs"].rolling(60).std()
    d["z_score"] = (d["daily_obs"] - d["mean_60"]) / d["std_60"]

    d = d.reset_index().rename(columns={"index": "date"})

    all_regions.append(d)

region_events_df = pd.concat(all_regions, ignore_index=True)

all_countries = []

for country, group in daily_country.groupby("Country"):

    d = group.set_index("date").sort_index()
    d = d.reindex(full_range)
    d["daily_obs"] = d["daily_obs"].fillna(0)
    d["Country"] = country
    d["mean_60"] = d["daily_obs"].rolling(60).mean()
    d["std_60"]  = d["daily_obs"].rolling(60).std()
    d["z_score"] = (d["daily_obs"] - d["mean_60"]) / d["std_60"]
    
    d = d.reset_index().rename(columns={"index": "date"})
    
    all_countries.append(d)

country_events_df = pd.concat(all_countries, ignore_index=True)

Function that detects events

In [7]:
def detect_events(df_input, group_col, z_threshold=2, block_length=3): # everything above threshold counts as unusual and if more than x days are above it, it's an event
    
    df_input = df_input.copy()
    df_input["is_event_day"] = df_input["z_score"] > z_threshold

    df_input["rolling_sum"] = (
        df_input
        .groupby(group_col)["is_event_day"]
        .transform(lambda x: x.rolling(block_length).sum())
    )

    df_input["event_block"] = (
        df_input
        .groupby(group_col)["rolling_sum"]
        .transform(lambda x: pd.concat(
            [x.shift(-i) for i in range(block_length)], axis=1
        ).max(axis=1) >= block_length)
    )

    periods = []

    for group_val in df_input[group_col].unique():

        d = df_input[df_input[group_col] == group_val].copy()
        country = d["Country"].iloc[0]

        d["event_shift"] = d["event_block"].shift(1, fill_value=False)

        starts = d[(d["event_block"] == True) & (d["event_shift"] == False)]
        ends   = d[(d["event_block"] == False) & (d["event_shift"] == True)]

        start_dates = starts["date"].values
        end_dates   = ends["date"].values

        if len(start_dates) > len(end_dates):
            end_dates = list(end_dates) + [d["date"].iloc[-1]]

        for s, e in zip(start_dates, end_dates):
            periods.append({
                "Country":    country,
                "Region":     group_val if group_col == "Region" else None,
                "level":      group_col,  # "Region" or "Country"
                "start_date": s,
                "end_date":   pd.to_datetime(e) - pd.Timedelta(days=1),
                "event_length (days)": (pd.to_datetime(e) - pd.to_datetime(s)).days
            })

    return pd.DataFrame(periods)

In [8]:
# uses country_events_df and region_events_df

events_list = []
events_list.append(detect_events(country_events_df, "Country", block_length=3))
events_list.append(detect_events(region_events_df, "Region", block_length=3))

pd.set_option("display.max_rows", None)
events_table = pd.concat(events_list, ignore_index=True)
events_table

,Country,Region,level,start_date,end_date,event_length (days)
0,Argentina,None,Country,2020-11-13,2020-11-15,3
1,Australia,None,Country,2021-05-31,2021-06-03,4
2,Australia,None,Country,2021-06-08,2021-06-11,4
3,Austria,None,Country,2018-01-10,2018-01-12,3
4,Austria,None,Country,2018-01-15,2018-01-17,3
5,Austria,None,Country,2021-01-31,2021-02-02,3
6,Brazil,None,Country,2023-10-02,2023-10-05,4
7,Brazil,None,Country,2024-10-22,2024-10-24,3
8,Canada,None,Country,2023-04-05,2023-04-07,3
9,Canada,None,Country,2025-03-07,2025-03-09,3
10,Chile,None,Country,2022-03-07,2022-03-09,3
11,Chile,None,Country,2023-11-24,2023-11-26,3
12,Costa Rica,None,Country,2023-03-20,2023-03-23,4
13,Estonia,None,Country,2024-02-28,2024-03-02,4
14,France,None,Country,2018-07-07,2018-07-09,3
15,France,None,Country,2019-07-16,2019-07-18,3
16,France,None,Country,2019-07-30,2019-08-01,3
17,France,None,Country,2022-09-04,2022-09-06,3
18,Germany,None,Country,2018-07-02,2018-07-04,3
19,Germany,None,Country,2018-09-06,2018-09-08,3
20,Germany,None,Country,2019-09-29,2019-10-01,3
21,Germany,None,Country,2024-03-24,2024-03-26,3
22,Indonesia,None,Country,2020-07-23,2020-07-25,3
23,Ireland,None,Country,2024-04-15,2024-04-17,3
24,Ireland,None,Country,2025-04-22,2025-04-24,3
25,Italy,None,Country,2021-03-18,2021-03-20,3
26,Kyrgyzstan,None,Country,2021-09-29,2021-10-01,3
27,Kyrgyzstan,None,Country,2022-05-20,2022-05-23,4
28,Lebanon,None,Country,2024-05-19,2024-05-21,3
29,Luxembourg,None,Country,2018-07-03,2018-07-05,3
30,Malaysia,None,Country,2019-04-28,2019-05-04,7
31,Mexico,None,Country,2024-02-17,2024-02-19,3
32,Mexico,None,Country,2026-01-09,2026-01-11,3
33,Netherlands,None,Country,2021-02-22,2021-02-24,3
34,Norway,None,Country,2023-04-11,2023-04-14,4
35,Norway,None,Country,2024-03-19,2024-03-22,4
36,Philippines,None,Country,2021-09-08,2021-09-11,4
37,Poland,None,Country,2024-09-13,2024-09-15,3
38,Serbia,None,Country,2022-04-20,2022-04-22,3
39,Slovakia,None,Country,2021-03-25,2021-03-30,6
40,Slovenia,None,Country,2025-08-19,2025-08-21,3
41,Spain,None,Country,2021-02-17,2021-02-20,4
42,Spain,None,Country,2022-03-02,2022-03-05,4
43,Sweden,None,Country,2021-07-21,2021-07-24,4
44,United States,None,Country,2018-04-13,2018-04-15,3
45,United States,None,Country,2019-12-18,2019-12-20,3
46,United States,None,Country,2021-06-29,2021-07-01,3
47,United States,None,Country,2021-09-03,2021-09-06,4
48,United States,None,Country,2023-05-16,2023-05-19,4
49,Australia,Northern Territory,Region,2021-09-14,2021-09-16,3
50,Australia,Northern Territory,Region,2021-10-05,2021-10-07,3
51,Australia,Queensland,Region,2021-05-31,2021-06-03,4
52,Australia,Queensland,Region,2021-06-08,2021-06-11,4
53,Austria,Carinthia,Region,2018-10-10,2018-10-18,9
54,Austria,Carinthia,Region,2022-09-18,2022-09-20,3
55,Austria,Lower Austria,Region,2020-06-21,2020-06-23,3
56,Austria,Salzburg,Region,2018-01-10,2018-01-12,3
57,Austria,Salzburg,Region,2018-01-15,2018-01-17,3
58,Austria,Salzburg,Region,2024-02-09,2024-02-11,3
59,Austria,Salzburg,Region,2024-02-13,2024-02-15,3
60,Austria,Tyrol,Region,2020-08-13,2020-08-15,3
61,Austria,Tyrol,Region,2023-02-27,2023-03-01,3
62,Austria,Tyrol,Region,2025-07-20,2025-07-22,3
63,Brazil,Santa Catarina,Region,2023-10-02,2023-10-05,4
64,Brazil,Santa Catarina,Region,2024-10-22,2024-10-24,3
65,Canada,Ontario,Region,2025-03-07,2025-03-09,3
66,Canada,Quebec,Region,2023-04-05,2023-04-07,3
67,Chile,Araucania,Region,2023-11-24,2023-11-26,3
68,Chile,Biobio,Region,2022-03-07,2022-03-09,3
69,Cyprus,Ammochostos,Region,2019-07-23,2019-07-26,4
70,Cyprus,Limassol,Region,2020-04-06,2020-04-08,3
71,Cyprus,Pafos,Region,2020-04-08,2020-04-10,3
72,France,Languedoc-Roussillon,Region,2021-02-26,2021-02-28,3
73,France,Pays de la Loire,Region,2019-05-18,2019-05-20,3
74,France,Rhone-Alpes,Region,2019-07-30,2019-08-01,3
75,Germany,Baden-Wuerttemberg,Region,2021-01-27,2021-01-30,4
76,Germany,Bavaria,Region,2023-02-15,2023-02-17,3
77,Germany,Bavaria,Region,2025-07-07,2025-07-09,3
78,Germany,Brandenburg,Region,2018-07-02,2018-07-04,3
79,Germany,Brandenburg,Region,2020-08-19,2020-08-22,4
80,Germany,Brandenburg,Region,2020-08-24,2020-08-27,4
81,Germany,Hesse,Region,2018-09-18,2018-09-20,3
82,Germany,North Rhine-Westphalia,Region,2024-03-18,2024-03-20,3
83,Germany,North Rhine-Westphalia,Region,2025-11-25,2025-11-27,3
84,Germany,Saxony,Region,2020-09-02,2020-09-04,3
85,Germany,Saxony,Region,2021-12-31,2022-01-02,3
86,Greece,Crete,Region,2019-07-18,2019-07-20,3
87,Ireland,Connaught,Region,2023-03-20,2023-03-22,3
88,Ireland,Leinster,Region,2024-04-14,2024-04-17,4
89,Italy,Sicily,Region,2024-05-04,2024-05-06,3
90,Italy,Trentino-Alto Adige,Region,2024-08-22,2024-08-24,3
91,Italy,Tuscany,Region,2022-07-29,2022-07-31,3
92,Kyrgyzstan,Chuy,Region,2022-06-06,2022-06-09,4
93,Kyrgyzstan,Jalal-Abad,Region,2021-09-29,2021-10-01,3
94,Kyrgyzstan,Jalal-Abad,Region,2022-05-20,2022-05-23,4
95,Kyrgyzstan,Naryn,Region,2024-09-07,2024-09-09,3
96,Lebanon,Beqaa,Region,2024-05-20,2024-05-22,3
97,Luxembourg,Luxembourg,Region,2018-07-03,2018-07-05,3
98,Malaysia,Selangor,Region,2019-04-28,2019-05-04,7
99,Mexico,Jalisco,Region,2024-02-17,2024-02-19,3
100,Mexico,Mexico City,Region,2026-01-09,2026-01-11,3
101,Netherlands,North Holland,Region,2021-02-22,2021-02-24,3
102,Netherlands,South Holland,Region,2019-12-12,2019-12-15,4
103,Netherlands,Utrecht,Region,2019-12-27,2019-12-29,3
104,Norway,Sogn og Fjordane,Region,2023-04-11,2023-04-14,4
105,Norway,Sogn og Fjordane,Region,2024-03-19,2024-03-22,4
106,Philippines,Bicol,Region,2021-09-08,2021-09-11,4
107,Poland,Masovian Voivodeship,Region,2024-09-13,2024-09-15,3
108,Serbia,Central Serbia,Region,2022-04-20,2022-04-22,3
109,Slovakia,Nitriansky,Region,2021-03-25,2021-03-30,6
110,Slovenia,Bohinj,Region,2025-08-19,2025-08-21,3
111,Spain,Balearic Islands,Region,2021-02-17,2021-02-20,4
112,Spain,Balearic Islands,Region,2022-03-02,2022-03-05,4
113,Spain,Basque Country,Region,2019-08-07,2019-08-09,3
114,Sweden,Uppsala,Region,2021-07-21,2021-07-24,4
115,Switzerland,Aargau,Region,2020-03-29,2020-03-31,3
116,Switzerland,Aargau,Region,2020-08-22,2020-08-26,5
117,Switzerland,Aargau,Region,2020-09-07,2020-09-11,5
118,Switzerland,Aargau,Region,2021-04-06,2021-04-08,3
119,Switzerland,Aargau,Region,2023-03-13,2023-03-16,4
120,Switzerland,Aargau,Region,2023-03-18,2023-03-20,3
121,Switzerland,Bern,Region,2018-01-22,2018-01-24,3
122,Switzerland,Grisons,Region,2019-09-15,2019-09-20,6
123,Switzerland,Grisons,Region,2020-06-13,2020-06-15,3
124,Switzerland,Grisons,Region,2021-07-15,2021-07-17,3
125,Switzerland,Grisons,Region,2022-08-18,2022-08-20,3
126,Switzerland,Obwalden,Region,2018-07-05,2018-07-09,5
127,Switzerland,Obwalden,Region,2023-02-08,2023-02-10,3
128,Switzerland,Saint Gallen,Region,2018-06-17,2018-06-21,5
129,Switzerland,Saint Gallen,Region,2019-05-19,2019-05-22,4
130,Switzerland,Saint Gallen,Region,2020-02-02,2020-02-04,3
131,Switzerland,Saint Gallen,Region,2020-04-16,2020-04-19,4
132,Switzerland,Saint Gallen,Region,2023-02-14,2023-02-16,3
133,Switzerland,Saint Gallen,Region,2023-06-05,2023-06-07,3
134,Switzerland,Schwyz,Region,2017-09-15,2017-09-17,3
135,Switzerland,Schwyz,Region,2017-09-22,2017-09-24,3
136,Switzerland,Solothurn,Region,2018-07-02,2018-07-04,3
137,Switzerland,Solothurn,Region,2020-12-24,2020-12-26,3
138,Switzerland,Thurgau,Region,2023-02-11,2023-02-15,5
139,Switzerland,Ticino,Region,2017-04-24,2017-04-28,5
140,Switzerland,Ticino,Region,2022-10-08,2022-10-12,5
141,Switzerland,Ticino,Region,2022-10-18,2022-10-23,6
142,Switzerland,Vaud,Region,2018-05-10,2018-05-12,3
143,Switzerland,Vaud,Region,2021-06-06,2021-06-09,4
144,Switzerland,Vaud,Region,2022-02-08,2022-02-10,3
145,Switzerland,Zurich,Region,2020-05-22,2020-05-24,3
146,United Kingdom,Scotland,Region,2025-09-08,2025-09-10,3
147,United States,Colorado,Region,2024-07-26,2024-07-28,3
148,United States,Maine,Region,2023-05-15,2023-05-19,5
149,United States,Maine,Region,2023-05-21,2023-05-26,6
150,United States,Minnesota,Region,2021-09-28,2021-09-30,3
151,United States,New Mexico,Region,2024-03-20,2024-03-22,3
152,United States,New York,Region,2018-04-13,2018-04-16,4
153,United States,North Carolina,Region,2024-04-08,2024-04-10,3
154,United States,Oregon,Region,2018-12-17,2018-12-19,3
155,United States,Oregon,Region,2019-12-18,2019-12-20,3
156,United States,Virginia,Region,2021-09-03,2021-09-08,6

Change-Point-Detection (C. Truong, L. Oudre, N. Vayatis. Selective review of offline change point detection methods. Signal Processing, 167:107299, 2020.)

In [9]:
def detect_change_points(df_input, group_col, pen, min_size):

    change_points_list = []

    for group_val in df_input[group_col].unique():

        d = df_input[df_input[group_col] == group_val].copy()
        
        # if region has less than five total observations, skip it
        if d["daily_obs"].max() < 5:
            continue
        country = d["Country"].iloc[0]

        # remove time before first activity in region
        #first_activity = d[d["daily_obs"] > 0]["date"]
        #if len(first_activity) == 0:
            #continue

        #d = d[d["date"] >= first_activity.min()]

        # weekly aggregation
        d_weekly = (
            d.set_index("date")
             .resample("W")["daily_obs"]
             .sum()
             .reset_index()
        )

        d_weekly["cum_obs"] = d_weekly["daily_obs"].cumsum()

        d_weekly["growth"] = d_weekly["daily_obs"].pct_change().fillna(0)

        signal = d_weekly["daily_obs"].values

        if np.sum(signal) == 0:
            continue

        # Model
        model = rpt.Pelt(model="l2", min_size=min_size).fit(signal)

        if len(signal) < 2 * min_size:
            continue

        # calculate breakpoints
        breakpoints = model.predict(pen=pen)

        # predict() returns indices
        # last point is always length (--> ignore that one)
        for bp in breakpoints[:-1]:

            change_points_list.append({
                "Country": country,
                "Region": group_val if group_col == "Region" else None,
                "level": group_col,
                "change_point_date": d_weekly["date"].iloc[bp]
            })

    return pd.DataFrame(change_points_list)

In [10]:
# uses country_events_df and region_events_df

cp_list = []
cp_list.append(detect_change_points(country_events_df, "Country", pen=80, min_size=8))
cp_list.append(detect_change_points(region_events_df, "Region", pen=80, min_size=8))

pd.set_option("display.max_rows", None)
cp_table = pd.concat(cp_list, ignore_index=True)
cp_table

            Country                  Region    level change_point_date
0         Australia                    None  Country        2021-05-30
1         Australia                    None  Country        2021-10-17
2         Australia                    None  Country        2022-01-30
3           Austria                    None  Country        2018-01-21
4           Austria                    None  Country        2018-04-01
5           Austria                    None  Country        2018-08-19
6           Austria                    None  Country        2019-01-06
7           Austria                    None  Country        2019-11-17
8           Austria                    None  Country        2020-07-19
9           Austria                    None  Country        2021-05-30
10          Austria                    None  Country        2021-08-08
11          Austria                    None  Country        2022-06-19
12          Austria                    None  Country        2022-08-28
13          Austria                    None  Country        2022-11-06
14          Austria                    None  Country        2023-02-19
15          Austria                    None  Country        2023-04-30
16          Austria                    None  Country        2023-07-09
17          Austria                    None  Country        2023-09-17
18          Austria                    None  Country        2023-11-26
19          Austria                    None  Country        2024-07-28
20          Austria                    None  Country        2025-06-08
21          Austria                    None  Country        2025-08-17
22           Canada                    None  Country        2019-04-21
23           Canada                    None  Country        2022-03-06
24           Canada                    None  Country        2022-08-28
25           Canada                    None  Country        2023-03-26
26           Canada                    None  Country        2023-09-17
27           Canada                    None  Country        2024-06-23
28            Chile                    None  Country        2020-04-05
29            Chile                    None  Country        2020-06-14
30            Chile                    None  Country        2020-08-23
31            Chile                    None  Country        2021-01-10
32            Chile                    None  Country        2021-07-04
33            Chile                    None  Country        2021-09-12
34            Chile                    None  Country        2022-11-06
35       Costa Rica                    None  Country        2022-12-11
36       Costa Rica                    None  Country        2023-03-26
37       Costa Rica                    None  Country        2023-06-04
38       Costa Rica                    None  Country        2024-03-10
39       Costa Rica                    None  Country        2024-05-19
40           Cyprus                    None  Country        2019-04-21
41           Cyprus                    None  Country        2019-06-30
42           Cyprus                    None  Country        2020-07-19
43           Cyprus                    None  Country        2022-01-30
44          Ecuador                    None  Country        2020-08-23
45          Ecuador                    None  Country        2020-11-01
46          Estonia                    None  Country        2022-04-10
47          Estonia                    None  Country        2022-10-02
48          Estonia                    None  Country        2022-12-11
49          Estonia                    None  Country        2023-06-04
50          Estonia                    None  Country        2023-09-17
51          Estonia                    None  Country        2023-11-26
52          Estonia                    None  Country        2024-02-04
53          Estonia                    None  Country        2024-12-15
54          Estonia                    None  Country        2025-07-13
55          Estonia                    None  Country        2025-09-21
56           France                    None  Country        2019-04-21
57           France                    None  Country        2019-06-30
58           France                    None  Country        2019-09-08
59           France                    None  Country        2020-01-26
60           France                    None  Country        2020-04-05
61           France                    None  Country        2020-06-14
62           France                    None  Country        2020-09-27
63           France                    None  Country        2022-07-24
64           France                    None  Country        2023-03-26
65           France                    None  Country        2024-07-28
66           France                    None  Country        2024-11-10
67          Germany                    None  Country        2018-12-02
68          Germany                    None  Country        2019-11-17
69          Germany                    None  Country        2020-03-01
70          Germany                    None  Country        2020-07-19
71          Germany                    None  Country        2020-11-01
72          Germany                    None  Country        2021-03-21
73          Germany                    None  Country        2021-07-04
74          Germany                    None  Country        2021-09-12
75          Germany                    None  Country        2021-12-26
76          Germany                    None  Country        2022-04-10
77          Germany                    None  Country        2022-07-24
78          Germany                    None  Country        2022-10-02
79          Germany                    None  Country        2023-06-04
80          Germany                    None  Country        2023-08-13
81          Germany                    None  Country        2024-02-04
82          Germany                    None  Country        2024-04-14
83          Germany                    None  Country        2024-07-28
84          Germany                    None  Country        2024-11-10
85          Germany                    None  Country        2025-03-30
86          Germany                    None  Country        2025-06-08
87          Germany                    None  Country        2025-08-17
88          Germany                    None  Country        2025-10-26
89           Greece                    None  Country        2019-05-26
90           Greece                    None  Country        2019-08-04
91           Greece                    None  Country        2023-02-19
92           Greece                    None  Country        2023-06-04
93           Greece                    None  Country        2023-08-13
94        Guatemala                    None  Country        2025-05-04
95        Guatemala                    None  Country        2025-07-13
96          Hungary                    None  Country        2019-08-04
97          Hungary                    None  Country        2020-01-26
98        Indonesia                    None  Country        2020-07-19
99        Indonesia                    None  Country        2020-09-27
100         Ireland                    None  Country        2023-02-19
101         Ireland                    None  Country        2023-06-04
102         Ireland                    None  Country        2023-08-13
103         Ireland                    None  Country        2023-11-26
104         Ireland                    None  Country        2024-05-19
105           Italy                    None  Country        2019-04-21
106           Italy                    None  Country        2019-10-13
107           Italy                    None  Country        2020-01-26
108           Italy                    None  Country        2022-07-24
109           Italy                    None  Country        2022-10-02
110           Italy                    None  Country        2024-04-14
111           Italy                    None  Country        2024-06-23
112      Kyrgyzstan                    None  Country        2020-08-23
113      Kyrgyzstan                    None  Country        2020-11-01
114      Kyrgyzstan                    None  Country        2021-03-21
115      Kyrgyzstan                    None  Country        2021-05-30
116      Kyrgyzstan                    None  Country        2021-08-08
117      Kyrgyzstan                    None  Country        2021-10-17
118      Kyrgyzstan                    None  Country        2022-05-15
119      Kyrgyzstan                    None  Country        2022-10-02
120      Kyrgyzstan                    None  Country        2024-05-19
121      Kyrgyzstan                    None  Country        2024-11-10
122        Malaysia                    None  Country        2019-04-21
123        Malaysia                    None  Country        2019-06-30
124           Malta                    None  Country        2019-03-17
125           Malta                    None  Country        2019-06-30
126     Netherlands                    None  Country        2019-04-21
127     Netherlands                    None  Country        2019-06-30
128     Netherlands                    None  Country        2019-11-17
129     Netherlands                    None  Country        2020-04-05
130     Netherlands                    None  Country        2021-02-14
131     Netherlands                    None  Country        2021-07-04
132     Netherlands                    None  Country        2021-09-12
133          Norway                    None  Country        2024-03-10
134          Norway                    None  Country        2024-05-19
135     Philippines                    None  Country        2021-09-12
136     Philippines                    None  Country        2021-11-21
137        Portugal                    None  Country        2019-04-21
138        Portugal                    None  Country        2019-09-08
139        Portugal                    None  Country        2019-11-17
140        Portugal                    None  Country        2020-03-01
141        Slovakia                    None  Country        2021-03-21
142        Slovakia                    None  Country        2021-05-30
143           Spain                    None  Country        2019-03-17
144           Spain                    None  Country        2019-06-30
145           Spain                    None  Country        2019-10-13
146           Spain                    None  Country        2020-03-01
147           Spain                    None  Country        2020-06-14
148           Spain                    None  Country        2021-02-14
149           Spain                    None  Country        2021-04-25
150           Spain                    None  Country        2023-02-19
151     Switzerland                    None  Country        2017-04-16
152     Switzerland                    None  Country        2017-06-25
153     Switzerland                    None  Country        2017-09-03
154     Switzerland                    None  Country        2017-11-12
155     Switzerland                    None  Country        2018-01-21
156     Switzerland                    None  Country        2018-06-10
157     Switzerland                    None  Country        2018-09-23
158     Switzerland                    None  Country        2018-12-02
159     Switzerland                    None  Country        2019-02-10
160     Switzerland                    None  Country        2019-04-21
161     Switzerland                    None  Country        2019-06-30
162     Switzerland                    None  Country        2019-10-13
163     Switzerland                    None  Country        2020-03-01
164     Switzerland                    None  Country        2020-05-10
165     Switzerland                    None  Country        2020-07-19
166     Switzerland                    None  Country        2020-11-01
167     Switzerland                    None  Country        2021-01-10
168     Switzerland                    None  Country        2021-04-25
169     Switzerland                    None  Country        2021-07-04
170     Switzerland                    None  Country        2021-09-12
171     Switzerland                    None  Country        2021-11-21
172     Switzerland                    None  Country        2022-01-30
173     Switzerland                    None  Country        2022-04-10
174     Switzerland                    None  Country        2022-06-19
175     Switzerland                    None  Country        2022-08-28
176     Switzerland                    None  Country        2022-11-06
177     Switzerland                    None  Country        2023-02-19
178     Switzerland                    None  Country        2023-04-30
179     Switzerland                    None  Country        2023-07-09
180     Switzerland                    None  Country        2023-09-17
181     Switzerland                    None  Country        2023-11-26
182     Switzerland                    None  Country        2024-02-04
183     Switzerland                    None  Country        2024-04-14
184     Switzerland                    None  Country        2024-06-23
185     Switzerland                    None  Country        2024-09-01
186     Switzerland                    None  Country        2025-02-23
187     Switzerland                    None  Country        2025-05-04
188     Switzerland                    None  Country        2025-07-13
189  United Kingdom                    None  Country        2019-03-17
190  United Kingdom                    None  Country        2019-05-26
191  United Kingdom                    None  Country        2019-10-13
192  United Kingdom                    None  Country        2020-01-26
193  United Kingdom                    None  Country        2020-04-05
194  United Kingdom                    None  Country        2020-07-19
195  United Kingdom                    None  Country        2020-11-01
196  United Kingdom                    None  Country        2021-02-14
197  United Kingdom                    None  Country        2021-05-30
198  United Kingdom                    None  Country        2021-10-17
199  United Kingdom                    None  Country        2022-01-30
200  United Kingdom                    None  Country        2023-03-26
201  United Kingdom                    None  Country        2024-09-01
202  United Kingdom                    None  Country        2024-11-10
203  United Kingdom                    None  Country        2025-02-23
204  United Kingdom                    None  Country        2025-07-13
205  United Kingdom                    None  Country        2025-09-21
206   United States                    None  Country        2018-04-01
207   United States                    None  Country        2020-08-23
208   United States                    None  Country        2020-11-01
209   United States                    None  Country        2021-02-14
210   United States                    None  Country        2021-04-25
211   United States                    None  Country        2021-09-12
212   United States                    None  Country        2021-12-26
213   United States                    None  Country        2023-04-30
214   United States                    None  Country        2023-10-22
215   United States                    None  Country        2024-09-01
216         Austria           Lower Austria   Region        2020-07-19
217         Austria           Lower Austria   Region        2021-01-10
218         Austria           Lower Austria   Region        2021-05-30
219         Austria           Lower Austria   Region        2022-06-19
220         Austria           Lower Austria   Region        2022-10-02
221         Austria           Lower Austria   Region        2023-04-30
222         Austria           Lower Austria   Region        2023-07-09
223         Austria           Lower Austria   Region        2023-09-17
224         Austria           Lower Austria   Region        2024-05-19
225         Austria           Lower Austria   Region        2024-07-28
226         Austria           Lower Austria   Region        2025-05-04
227         Austria           Lower Austria   Region        2025-08-17
228         Austria           Lower Austria   Region        2025-10-26
229         Austria                Salzburg   Region        2018-01-21
230         Austria                Salzburg   Region        2018-04-01
231         Austria                Salzburg   Region        2018-10-28
232         Austria                Salzburg   Region        2019-01-06
233         Austria                Salzburg   Region        2020-07-19
234         Austria                Salzburg   Region        2020-09-27
235         Austria                Salzburg   Region        2021-09-12
236         Austria                Salzburg   Region        2022-07-24
237          Canada                 Alberta   Region        2019-04-21
238          Canada                 Alberta   Region        2024-06-23
239          Canada                  Quebec   Region        2022-03-06
240          Canada                  Quebec   Region        2022-08-28
241          Canada                  Quebec   Region        2023-03-26
242          Canada                  Quebec   Region        2023-09-17
243           Chile                  Biobio   Region        2020-04-05
244           Chile                  Biobio   Region        2020-06-14
245           Chile                  Biobio   Region        2020-08-23
246           Chile                  Biobio   Region        2021-01-10
247           Chile                  Biobio   Region        2021-07-04
248           Chile                  Biobio   Region        2021-09-12
249           Chile                  Biobio   Region        2022-07-24
250      Costa Rica                Alajuela   Region        2023-03-26
251      Costa Rica                Alajuela   Region        2023-06-04
252      Costa Rica                 Cartago   Region        2023-03-26
253      Costa Rica                 Cartago   Region        2023-06-04
254      Costa Rica                San Jose   Region        2022-11-06
255          Cyprus                Lefkosia   Region        2019-03-17
256          Cyprus                Lefkosia   Region        2020-07-19
257         Ecuador                  Manabi   Region        2020-08-23
258         Ecuador                  Manabi   Region        2020-11-01
259         Estonia                Polvamaa   Region        2022-04-10
260         Estonia                Raplamaa   Region        2022-04-10
261         Estonia                 Vorumaa   Region        2022-04-10
262          France                Brittany   Region        2019-08-04
263          France                Brittany   Region        2021-07-04
264          France             Rhone-Alpes   Region        2019-06-30
265          France             Rhone-Alpes   Region        2019-09-08
266          France             Rhone-Alpes   Region        2020-01-26
267          France             Rhone-Alpes   Region        2020-04-05
268          France             Rhone-Alpes   Region        2020-06-14
269          France             Rhone-Alpes   Region        2020-09-27
270          France             Rhone-Alpes   Region        2024-06-23
271          France             Rhone-Alpes   Region        2024-09-01
272         Germany      Baden-Wuerttemberg   Region        2018-12-02
273         Germany      Baden-Wuerttemberg   Region        2019-03-17
274         Germany      Baden-Wuerttemberg   Region        2019-10-13
275         Germany      Baden-Wuerttemberg   Region        2019-12-22
276         Germany      Baden-Wuerttemberg   Region        2020-04-05
277         Germany      Baden-Wuerttemberg   Region        2020-07-19
278         Germany      Baden-Wuerttemberg   Region        2021-01-10
279         Germany      Baden-Wuerttemberg   Region        2021-08-08

Plotting the daily median distance to Zurich of all observations over time, as well as annual plots to see it better

In [11]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["date"] = pd.to_datetime(df["date"])

zurich = (47.3769, 8.5417)

df["distance_zurich"] = df.apply(
    lambda row: haversine(
        zurich,
        (row["latitude"], row["longitude"]),
        unit="km"
    ),
    axis=1
)

daily_distance = (
    df
    .groupby("date")["distance_zurich"]
    .median()
    .reset_index()
)

daily_distance["distance_30d_mean"] = (
    daily_distance["distance_zurich"]
    .rolling(window=30, min_periods=1)
    .mean()
)

plt.figure(figsize=(16,8))

plt.plot(
    daily_distance["date"],
    daily_distance["distance_zurich"],
    alpha=0.6,
    label="Daily median"
)

plt.plot(
    daily_distance["date"],
    daily_distance["distance_30d_mean"],
    linewidth=2,
    label="30-day running mean"
)

plt.ylabel("Distance [km]", fontsize=12)
plt.xlabel("Date", fontsize=12)
plt.title("Daily Median Distance of Observations to Zurich over time", fontsize=15)
plt.legend()
plt.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.4)
plt.ylim(0,8000)
plt.savefig("../Products/Distance_to_Zurich/Median_Distance_to_Zurich_full.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_3488\372182383.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

annual distance-to-Zurich plots

In [12]:
# uses daily_distance

daily_distance["year"] = daily_distance["date"].dt.year
years = sorted(daily_distance["year"].unique())

for year in years:

    data = daily_distance[daily_distance["year"] == year]
    year_median = df[df["date"].dt.year == year]["distance_zurich"].median()

    plt.figure(figsize=(16,8))

    plt.plot(
        data["date"],
        data["distance_zurich"],
        alpha=0.6,
        label="Daily median"
    )

    plt.plot(
        data["date"],
        data["distance_30d_mean"],
        linewidth=2,
        label="30-day running mean"
    )

    plt.text(
        0.02,
        0.95,
        f"Yearly median distance: {year_median:.0f} km",
        transform=plt.gca().transAxes,
        fontsize=12,
        verticalalignment="top"
    )

    plt.ylabel("Distance [km]", fontsize=12)
    plt.xlabel("Date", fontsize=12)
    plt.title(f"Daily Median Distance of Observations to Zurich over time - {year}", fontsize=15)
    plt.legend(loc="upper right")
    plt.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.4)
    plt.ylim(0,8000)
    plt.savefig(f"../Products/Distance_to_Zurich/Median_Distance_to_Zurich_{year}.png", dpi=300, bbox_inches="tight")
    plt.close()