In [153]:
import requests
import pandas as pd
from datetime import datetime, timezone
import time
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.colors import BoundaryNorm
from matplotlib.cm import get_cmap
from matplotlib.patches import Patch
import matplotlib.dates as mdates
import ast
import folium
from folium.plugins import MarkerCluster
import reverse_geocoder as rg
import re
import pycountry
import os
import numpy as np
import geopandas as gpd
import fiona
import sys
from shapely.geometry import Point
from sklearn.cluster import DBSCAN
import ruptures as rpt
from haversine import haversine
import functions as own
from timezonefinder import TimezoneFinder
import zoneinfo
from scipy.stats import gaussian_kde
from scipy.stats import chisquare, kruskal, mannwhitneyu, spearmanr
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from libpysal.weights import lat2W
from libpysal.weights import Queen
from libpysal.weights import DistanceBand
from esda.moran import Moran_Local, Moran
from shapely.geometry import box
import statsmodels.api as sm
from statsmodels.tsa.seasonal import STL
import importlib
from pymannkendall import original_test
from statsmodels.stats.multitest import multipletests

In [50]:
importlib.reload(own)

Lineplot with number of observations per month

In [67]:
df = pd.read_csv("../CWData_clean7.csv")
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")
monthly = df.groupby("year_month").size().reset_index(name="n_obs")
monthly["year_month_dt"] = monthly["year_month"].dt.to_timestamp()

fig, ax = plt.subplots(figsize=(16, 9))
ax.scatter(monthly["year_month_dt"], monthly["n_obs"], color="teal", s=20, zorder=3)
ax.plot(monthly["year_month_dt"], monthly["n_obs"], color="teal", linewidth=0.8, alpha=0.4)

ax.fill_between(monthly["year_month_dt"], monthly["n_obs"], alpha=0.1, color="teal")
ax.grid(axis="x", linestyle="--", alpha=0.5)
ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_axisbelow(True)

plt.title("Total Monthly Observations", fontsize=20)
plt.xlabel("Time", fontsize=17)
plt.ylabel("Number of Observations", fontsize=17)
plt.xticks(rotation=90)

plt.savefig(f"../Products/Lineplot_monthly_Observations.png", dpi=300, bbox_inches="tight")
plt.close()

monthly

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\1723706834.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

    year_month  n_obs year_month_dt
0      2017-02     23    2017-02-01
1      2017-03     46    2017-03-01
2      2017-04     34    2017-04-01
3      2017-05     59    2017-05-01
4      2017-06     73    2017-06-01
5      2017-07     55    2017-07-01
6      2017-08     44    2017-08-01
7      2017-09    117    2017-09-01
8      2017-10    104    2017-10-01
9      2017-11     41    2017-11-01
10     2017-12     53    2017-12-01
11     2018-01    137    2018-01-01
12     2018-02     80    2018-02-01
13     2018-03     86    2018-03-01
14     2018-04    179    2018-04-01
15     2018-05    184    2018-05-01
16     2018-06    292    2018-06-01
17     2018-07    325    2018-07-01
18     2018-08    371    2018-08-01
19     2018-09    280    2018-09-01
20     2018-10    238    2018-10-01
21     2018-11    223    2018-11-01
22     2018-12    270    2018-12-01
23     2019-01    190    2019-01-01
24     2019-02    231    2019-02-01
25     2019-03    448    2019-03-01
26     2019-04    679    2019-04-01
27     2019-05    995    2019-05-01
28     2019-06    744    2019-06-01
29     2019-07    771    2019-07-01
30     2019-08    906    2019-08-01
31     2019-09    641    2019-09-01
32     2019-10    510    2019-10-01
33     2019-11    378    2019-11-01
34     2019-12    629    2019-12-01
35     2020-01    484    2020-01-01
36     2020-02    535    2020-02-01
37     2020-03    520    2020-03-01
38     2020-04    486    2020-04-01
39     2020-05    509    2020-05-01
40     2020-06    860    2020-06-01
41     2020-07    702    2020-07-01
42     2020-08    772    2020-08-01
43     2020-09    794    2020-09-01
44     2020-10    634    2020-10-01
45     2020-11    804    2020-11-01
46     2020-12    749    2020-12-01
47     2021-01    813    2021-01-01
48     2021-02    929    2021-02-01
49     2021-03   1116    2021-03-01
50     2021-04   1005    2021-04-01
51     2021-05   1169    2021-05-01
52     2021-06    983    2021-06-01
53     2021-07   1004    2021-07-01
54     2021-08    924    2021-08-01
55     2021-09   1157    2021-09-01
56     2021-10   1019    2021-10-01
57     2021-11    841    2021-11-01
58     2021-12    808    2021-12-01
59     2022-01    715    2022-01-01
60     2022-02    712    2022-02-01
61     2022-03    862    2022-03-01
62     2022-04    776    2022-04-01
63     2022-05    944    2022-05-01
64     2022-06    828    2022-06-01
65     2022-07    708    2022-07-01
66     2022-08    785    2022-08-01
67     2022-09    826    2022-09-01
68     2022-10    901    2022-10-01
69     2022-11    649    2022-11-01
70     2022-12    506    2022-12-01
71     2023-01    517    2023-01-01
72     2023-02    675    2023-02-01
73     2023-03   1075    2023-03-01
74     2023-04   1069    2023-04-01
75     2023-05   1274    2023-05-01
76     2023-06    907    2023-06-01
77     2023-07    826    2023-07-01
78     2023-08    655    2023-08-01
79     2023-09    653    2023-09-01
80     2023-10    674    2023-10-01
81     2023-11    587    2023-11-01
82     2023-12    504    2023-12-01
83     2024-01    413    2024-01-01
84     2024-02    594    2024-02-01
85     2024-03    781    2024-03-01
86     2024-04   1270    2024-04-01
87     2024-05   1588    2024-05-01
88     2024-06   1145    2024-06-01
89     2024-07    810    2024-07-01
90     2024-08    759    2024-08-01
91     2024-09    732    2024-09-01
92     2024-10    754    2024-10-01
93     2024-11    560    2024-11-01
94     2024-12    547    2024-12-01
95     2025-01    498    2025-01-01
96     2025-02    431    2025-02-01
97     2025-03    525    2025-03-01
98     2025-04    608    2025-04-01
99     2025-05    699    2025-05-01
100    2025-06    627    2025-06-01
101    2025-07    543    2025-07-01
102    2025-08    453    2025-08-01
103    2025-09    316    2025-09-01
104    2025-10    442    2025-10-01
105    2025-11    513    2025-11-01
106    2025-12    390    2025-12-01
107    2026-01    386    2026-01-01
108    2026-02    552    2026-02-01
109    2026-03    804    2026-03-01
110    2026-04    739    2026-04-01

In [68]:
monthly = df.groupby("year_month").size().reset_index(name="n_obs")
monthly["year_month_dt"] = monthly["year_month"].dt.to_timestamp()

result = own.STL_decomposition(monthly, "n_obs", "Monthly Observations", "Observations")

Seasonal strength Monthly Observations: 0.637
Trend strength Monthly Observations:    0.880

In [69]:
trend = result.trend.dropna()
mk = original_test(trend.values)

print(f"Trend: {mk.trend}")
print(f"p-value: {mk.p:.3f}")
print(f"Sen's slope: {mk.slope:.3f} users/month")
print(f"Tau: {mk.Tau:.3f}")

Trend: increasing
p-value: 0.000
Sen's slope: 4.793 users/month
Tau: 0.330

A graphic with three bar charts is created, first the number of observations per hour of day, second the number of observations per month of year, third the number of observations per year

In [128]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["hour"] = df["created_at_local"].dt.hour
df["month"] = df["created_at_local"].dt.month
df["year"] = df["created_at_local"].dt.year

# data
hour_counts = df["hour"].value_counts().reindex(range(24), fill_value=0).sort_index()
years_per_month = df.groupby("month")["year"].nunique()
month_counts = (df["month"].value_counts().reindex(range(1,13), fill_value=0).sort_index() / years_per_month).round(0).astype(int)
year_counts = df["year"].value_counts().reindex(range(2017,2027), fill_value=0).sort_index()

fig, axes = plt.subplots(3, 1, figsize=(16, 24))

# Hour
hour_counts.plot(kind="bar", color="teal", ax=axes[0], fontsize=14)
axes[0].set_title("a) Total Observations per Hour of Day (Local Time)", fontsize=22, fontweight="bold", loc="left")
axes[0].set_ylabel("Number of Observations", fontsize=19)
axes[0].set_xlabel("Hour", fontsize=19)
axes[0].set_xticklabels([f"{h:02d}:00-{(h+1)%24:02d}:00" for h in range(24)], rotation=45, ha="right", fontsize=14)
axes[0].grid(axis="y", linestyle="--", alpha=0.5)
axes[0].set_axisbelow(True)

# Month
month_counts.plot(kind="bar", color="teal", ax=axes[1], fontsize=14)
axes[1].set_title("b) Average Observations per Month of Year", fontsize=22, fontweight="bold", loc="left")
axes[1].set_ylabel("Number of Observations", fontsize=19)
axes[1].set_xlabel("Month", fontsize=19)
axes[1].set_xticklabels(["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"], rotation=45, ha="right", fontsize=14)
axes[1].grid(axis="y", linestyle="--", alpha=0.5)
axes[1].set_axisbelow(True)

# Year
year_counts.plot(kind="bar", color="teal", ax=axes[2], fontsize=14)

# extrapolation in 2026
full_years = range(2018, 2026)
april_fracs = []
for y in full_years:
    total = (df["year"] == y).sum()
    until_april = ((df["year"] == y) & (df["month"] <= 4)).sum()
    april_fracs.append(until_april / total)
avg_april_frac = np.mean(april_fracs)
obs_2026_actual = (df["year"] == 2026).sum()
obs_2026_extrap = int(obs_2026_actual / avg_april_frac) - obs_2026_actual

bars = axes[2].patches
last_bar = bars[-1]
axes[2].bar(last_bar.get_x() + last_bar.get_width()/2, obs_2026_extrap,
            bottom=obs_2026_actual, width=last_bar.get_width(),
            color="#90E4C1", hatch="//", edgecolor="teal",
            label=f"2026 extrapolation")
axes[2].legend(fontsize=14)
axes[2].set_title("c) Total Observations per Year", fontsize=22, fontweight="bold", loc="left")
axes[2].set_ylabel("Number of Observations", fontsize=19)
axes[2].set_xlabel("Year", fontsize=19)
axes[2].set_xticklabels(["2017 (from Feb)","2018","2019","2020","2021","2022","2023","2024","2025","2026 (extrapolated)"], rotation=45, ha="right", fontsize=14)
axes[2].grid(axis="y", linestyle="--", alpha=0.5)
axes[2].set_axisbelow(True)

plt.tight_layout()
plt.savefig("../Products/barcharts_hour_month_year.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\3828962262.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Another double-chart with two stacked bar charts of a) annual and b) monthly new/returning users

In [132]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year"] = df["created_at_local"].dt.year
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

# data annual
all_years = sorted(df["year"].unique())
seen_users = set()
results = []

for year in all_years:
    year_users = set(df[df["year"] == year]["created_by"].dropna().unique())
    new_users = year_users - seen_users
    returning_users = year_users & seen_users
    results.append({
        "year": year,
        "new_users": len(new_users),
        "returning_users": len(returning_users),
        "total_users": len(year_users)
    })
    seen_users.update(year_users)
result_annual = pd.DataFrame(results)

# data monthly
all_months = sorted(df["year_month"].unique())
seen_users = set()
results = []

for month in all_months:
    month_users = set(df[df["year_month"] == month]["created_by"].dropna().unique())
    new_users = month_users - seen_users
    returning_users = month_users & seen_users
    results.append({
        "year_month": month,
        "new_users": len(new_users),
        "returning_users": len(returning_users),
        "total_users": len(month_users)
    })
    seen_users.update(month_users)
result_monthly = pd.DataFrame(results)
result_monthly["year_month_dt"] = result_monthly["year_month"].dt.to_timestamp()

# Plot
fig, axes = plt.subplots(2, 1, figsize=(16, 16))

# Annual
axes[0].bar(result_annual["year"], result_annual["returning_users"],
            label="Returning Users", color="teal", width=0.6)
axes[0].bar(result_annual["year"], result_annual["new_users"],
            bottom=result_annual["returning_users"],
            label="New Users", color="lightblue", width=0.6)
axes[0].set_title("Annual New vs. Returning Users", fontsize=21, fontweight="bold", loc="left")
axes[0].set_xlabel("Year", fontsize=18)
axes[0].set_ylabel("Number of Users", fontsize=18)
axes[0].set_xticks(result_annual["year"])
axes[0].set_xticklabels(result_annual["year"], rotation=45, ha="right", fontsize=13)
axes[0].legend(fontsize=13)
axes[0].grid(axis="y", linestyle="--", alpha=0.5)
axes[0].set_axisbelow(True)

# Monthly
axes[1].bar(result_monthly["year_month_dt"], result_monthly["returning_users"],
            label="Returning Users", color="teal", width=20)
axes[1].bar(result_monthly["year_month_dt"], result_monthly["new_users"],
            bottom=result_monthly["returning_users"],
            label="New Users", color="lightblue", width=20)
axes[1].set_title("Monthly New vs. Returning Users", fontsize=21, fontweight="bold", loc="left")
axes[1].set_xlabel("Month", fontsize=18)
axes[1].set_ylabel("Number of Users", fontsize=18)
axes[1].tick_params(axis="x", labelsize=13)
axes[1].legend(fontsize=13)
axes[1].grid(axis="y", linestyle="--", alpha=0.5)
axes[1].set_axisbelow(True)
axes[1].set_ylim(0, 200)

plt.tight_layout()
plt.savefig("../Products/new_vs_returning_combined.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\1474056019.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

In [133]:
pd.set_option("display.max_rows", None)
result_monthly

    year_month  new_users  returning_users  total_users year_month_dt
0      2017-02          2                0            2    2017-02-01
1      2017-03          8                2           10    2017-03-01
2      2017-04          3                4            7    2017-04-01
3      2017-05         15                8           23    2017-05-01
4      2017-06          7               13           20    2017-06-01
5      2017-07         11                9           20    2017-07-01
6      2017-08          4               10           14    2017-08-01
7      2017-09         10               16           26    2017-09-01
8      2017-10          2               15           17    2017-10-01
9      2017-11          3                9           12    2017-11-01
10     2017-12          9               10           19    2017-12-01
11     2018-01         29               12           41    2018-01-01
12     2018-02          6               21           27    2018-02-01
13     2018-03          5                9           14    2018-03-01
14     2018-04         25               15           40    2018-04-01
15     2018-05         14               25           39    2018-05-01
16     2018-06         12               20           32    2018-06-01
17     2018-07         12               32           44    2018-07-01
18     2018-08         16               29           45    2018-08-01
19     2018-09         31               27           58    2018-09-01
20     2018-10         10               25           35    2018-10-01
21     2018-11         12               27           39    2018-11-01
22     2018-12         18               23           41    2018-12-01
23     2019-01         11               21           32    2019-01-01
24     2019-02         11               27           38    2019-02-01
25     2019-03         25               25           50    2019-03-01
26     2019-04         47               31           78    2019-04-01
27     2019-05         34               49           83    2019-05-01
28     2019-06         22               51           73    2019-06-01
29     2019-07         16               45           61    2019-07-01
30     2019-08          9               47           56    2019-08-01
31     2019-09         37               38           75    2019-09-01
32     2019-10         15               38           53    2019-10-01
33     2019-11          8               27           35    2019-11-01
34     2019-12         25               31           56    2019-12-01
35     2020-01         18               34           52    2020-01-01
36     2020-02         19               42           61    2020-02-01
37     2020-03         16               36           52    2020-03-01
38     2020-04         15               36           51    2020-04-01
39     2020-05         28               29           57    2020-05-01
40     2020-06        123               46          169    2020-06-01
41     2020-07         39               45           84    2020-07-01
42     2020-08         27               39           66    2020-08-01
43     2020-09         31               48           79    2020-09-01
44     2020-10         34               42           76    2020-10-01
45     2020-11         41               43           84    2020-11-01
46     2020-12         19               46           65    2020-12-01
47     2021-01         35               45           80    2021-01-01
48     2021-02         32               59           91    2021-02-01
49     2021-03         55               66          121    2021-03-01
50     2021-04         42               75          117    2021-04-01
51     2021-05        106               77          183    2021-05-01
52     2021-06         85               48          133    2021-06-01
53     2021-07         25               81          106    2021-07-01
54     2021-08         17               60           77    2021-08-01
55     2021-09         95               54          149    2021-09-01
56     2021-10         21               68           89    2021-10-01
57     2021-11         15               49           64    2021-11-01
58     2021-12         16               50           66    2021-12-01
59     2022-01          9               54           63    2022-01-01
60     2022-02         11               55           66    2022-02-01
61     2022-03         33               60           93    2022-03-01
62     2022-04         32               56           88    2022-04-01
63     2022-05         99               60          159    2022-05-01
64     2022-06         45               49           94    2022-06-01
65     2022-07         14               54           68    2022-07-01
66     2022-08         26               62           88    2022-08-01
67     2022-09         43               64          107    2022-09-01
68     2022-10         35               59           94    2022-10-01
69     2022-11         32               69          101    2022-11-01
70     2022-12         14               58           72    2022-12-01
71     2023-01         27               55           82    2023-01-01
72     2023-02         38               53           91    2023-02-01
73     2023-03         95               80          175    2023-03-01
74     2023-04         36               90          126    2023-04-01
75     2023-05        100               81          181    2023-05-01
76     2023-06         57               58          115    2023-06-01
77     2023-07         13               55           68    2023-07-01
78     2023-08         27               57           84    2023-08-01
79     2023-09         39               61          100    2023-09-01
80     2023-10         29               69           98    2023-10-01
81     2023-11         12               58           70    2023-11-01
82     2023-12          6               49           55    2023-12-01
83     2024-01          7               43           50    2024-01-01
84     2024-02         20               48           68    2024-02-01
85     2024-03         99               55          154    2024-03-01
86     2024-04         66               78          144    2024-04-01
87     2024-05        120               64          184    2024-05-01
88     2024-06         60               66          126    2024-06-01
89     2024-07         25               65           90    2024-07-01
90     2024-08         26               56           82    2024-08-01
91     2024-09         25               55           80    2024-09-01
92     2024-10         34               61           95    2024-10-01
93     2024-11         11               53           64    2024-11-01
94     2024-12          9               48           57    2024-12-01
95     2025-01         12               42           54    2025-01-01
96     2025-02         15               52           67    2025-02-01
97     2025-03         20               53           73    2025-03-01
98     2025-04         59               56          115    2025-04-01
99     2025-05         96               62          158    2025-05-01
100    2025-06         55               44           99    2025-06-01
101    2025-07         29               51           80    2025-07-01
102    2025-08         22               47           69    2025-08-01
103    2025-09         26               39           65    2025-09-01
104    2025-10         31               58           89    2025-10-01
105    2025-11         36               40           76    2025-11-01
106    2025-12         27               48           75    2025-12-01
107    2026-01         37               33           70    2026-01-01
108    2026-02         24               46           70    2026-02-01
109    2026-03         71               68          139    2026-03-01
110    2026-04         39               90          129    2026-04-01

STL decomposition of these data

In [134]:
result1 = own.STL_decomposition(result_monthly, "total_users", "Total Users", "Users")
result2 = own.STL_decomposition(result_monthly, "new_users", "New Users", "Users")
result3 = own.STL_decomposition(result_monthly, "returning_users", "Returning Users", "Users")

Seasonal strength Total Users: 0.779
Trend strength Total Users:    0.840
Seasonal strength New Users: 0.747
Trend strength New Users:    0.528
Seasonal strength Returning Users: 0.602
Trend strength Returning Users:    0.910

Mann-Kendall test (3 times)

In [135]:
trend = result1.trend.dropna()
mk = original_test(trend.values)

print(f"Trend: {mk.trend}")
print(f"p-value: {mk.p:.3f}")
print(f"Sen's slope: {mk.slope:.3f} users/month")
print(f"Tau: {mk.Tau:.3f}")

Trend: increasing
p-value: 0.000
Sen's slope: 0.801 users/month
Tau: 0.555

In [136]:
trend = result2.trend.dropna()
mk = original_test(trend.values)

print(f"Trend: {mk.trend}")
print(f"p-value: {mk.p:.3f}")
print(f"Sen's slope: {mk.slope:.3f} users/month")
print(f"Tau: {mk.Tau:.3f}")

Trend: increasing
p-value: 0.000
Sen's slope: 0.334 users/month
Tau: 0.573

In [137]:
trend = result3.trend.dropna()
mk = original_test(trend.values)

print(f"Trend: {mk.trend}")
print(f"p-value: {mk.p:.3f}")
print(f"Sen's slope: {mk.slope:.3f} users/month")
print(f"Tau: {mk.Tau:.3f}")

Trend: increasing
p-value: 0.000
Sen's slope: 0.471 users/month
Tau: 0.541

Here, monthly maps of observations are created

In [87]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

monthly_counts = (
    df
    .groupby(["year_month", "latitude", "longitude"])
    .size()
    .reset_index(name="count")
)

world = gpd.read_file(f"../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona").to_crs("+proj=robin")

saved_files = []
for month in monthly_counts["year_month"].unique():
    subset = monthly_counts[monthly_counts["year_month"] == month]
    robin_subset = gpd.GeoDataFrame(
        subset,
        geometry=gpd.points_from_xy(subset["longitude"], subset["latitude"]),
        crs="EPSG:4326"
    ).to_crs("+proj=robin")

    fig, ax = plt.subplots(figsize=(16,8))
    
    # draw world map
    world.plot(ax=ax, color="grey", edgecolor="black", linewidth=0.5)
    
    # plot points
    ax.scatter(
        robin_subset.geometry.x,
        robin_subset.geometry.y,
        s=np.log1p(robin_subset["count"]) * 40, # log for radius
        color="#90E4C1",
        edgecolor="black",
        linewidth=0.3,
        alpha=0.7
    )

    legend_counts = [1, 10, 50, 100]
    legend_handles = [
        plt.scatter([], [], s=np.log1p(c) * 40, color="#90E4C1", edgecolor="black", linewidth=0.7, label=str(c))
        for c in legend_counts
    ]
    legend = ax.legend(
        handles=legend_handles,
        title="Observations",
        loc="lower left",
        frameon=True,
        labelspacing=1.5
    )
    legend.get_title().set_fontsize(15)
    for text in legend.get_texts():
        text.set_fontsize(12)
    
    ax.set_title(f"Observations - {month}", fontsize=18)
    ax.set_axis_off()
    
    filepath = f"../Products/Monthly_Activity_Maps/{month}.png"
    plt.savefig(filepath, dpi=300, bbox_inches="tight")
    plt.close()
    saved_files.append(filepath)

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\248588565.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

In [88]:
own.gif_maker(*saved_files, path="../Products/Monthly_Activity_Maps/Animation", duration=200)

I'm retrieving the date when the first observation is made, the number of observations and the number of unique users per Country.

In [114]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

first_countries = (
    df
    .groupby("Country")
    .agg(
        first_date = ("created_at_local","min"),
        total_observations = ("created_at_local","count"),
        unique_users = ("created_by","nunique")
    )
    .reset_index()
)

pd.set_option("display.max_rows", None)

first_countries_view = (
    first_countries
    .sort_values(by="first_date")
    .assign(first_date=lambda x: x["first_date"].dt.strftime("%d.%m.%Y"))
)
first_countries_view

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\3679988019.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

                     Country  first_date  total_observations  unique_users
80               Switzerland  05.02.2017               23369          1664
5                    Austria  04.03.2017                6228            92
30                   Germany  19.03.2017               12553           484
28                    France  19.03.2017                2282            75
79                    Sweden  08.04.2017                 242            25
12                    Canada  06.05.2017                2170            46
87  United States of America  18.05.2017                1922           143
86            United Kingdom  17.06.2017                5154           155
0                Afghanistan  03.07.2017                   1             1
82                  Thailand  08.07.2017                   2             1
65                      Peru  14.07.2017                  15             5
38                 Indonesia  25.07.2017                 124            11
58               Netherlands  03.08.2017                 926           126
50                 Lithuania  07.08.2017                   8             3
47                    Latvia  08.08.2017                   4             3
25                   Estonia  10.08.2017                1603             7
63                    Norway  15.08.2017                 153            53
42                     Italy  28.08.2017                1429            67
4                  Australia  12.12.2017                 357            14
33                 Guatemala  13.12.2017                 197             8
14                     Chile  07.01.2018                 946            46
3                  Argentina  13.01.2018                 110            19
11                  Cameroon  09.02.2018                   3             1
37                     India  25.03.2018                  18             9
70                    Russia  05.04.2018                  78             5
20                   Czechia  08.04.2018                  43            12
43                     Japan  18.05.2018                   8             6
44                Kazakhstan  15.06.2018                   4             2
51                Luxembourg  03.07.2018                  52             8
17                Costa Rica  17.07.2018                 625           180
75                  Slovenia  19.07.2018                  23             7
52                  Malaysia  02.08.2018                 156             8
40                   Ireland  21.10.2018                 964            42
49             Liechtenstein  24.10.2018                  25             5
34                  Honduras  26.02.2019                   2             2
78                     Spain  15.03.2019                1611            28
19                    Cyprus  19.03.2019                 542             4
53                     Malta  26.03.2019                 142             4
35                   Hungary  03.04.2019                 182            14
68                  Portugal  08.04.2019                 410            12
74                  Slovakia  29.04.2019                 110             6
32                    Greece  04.05.2019                 611            23
15                     China  08.05.2019                  85             8
23                     Egypt  09.05.2019                   2             2
56                   Morocco  30.05.2019                  27             3
46                Kyrgyzstan  30.05.2019                 769            34
27                   Finland  27.07.2019                  21             4
9                   Bulgaria  13.08.2019                  25             3
45                     Kenya  25.08.2019                  18             3
18                   Croatia  22.09.2019                  19             6
1                    Albania  17.10.2019                   1             1
69                   Romania  05.12.2019                   4             1
60                 Nicaragua  22.01.2020                   1             1
71                    Rwanda  25.04.2020                   2             1
22                   Ecuador  13.05.2020                  69            23
39                      Iran  15.05.2020                  12             3
67                    Poland  08.07.2020                  21             8
59               New Zealand  10.07.2020                  16             6
21                   Denmark  17.07.2020                   7             3
8                     Brazil  04.09.2020                 148            46
16                  Colombia  22.11.2020                  15             6
81                    Taiwan  01.12.2020                   2             1
89                Uzbekistan  16.12.2020                   1             1
7                    Belgium  28.02.2021                  18             6
66               Philippines  07.04.2021                 104            85
61                   Nigeria  03.05.2021                   1             1
73                    Serbia  17.07.2021                  28             1
29                   Georgia  26.07.2021                   1             1
88                   Uruguay  20.08.2021                  28             5
76              South Africa  27.10.2021                   7             2
31                     Ghana  14.12.2021                   2             2
64                    Panama  17.01.2022                   1             1
10                  Cambodia  26.02.2022                   4             2
83       Trinidad and Tobago  24.04.2022                   1             1
41                    Israel  24.04.2022                   1             1
55                Montenegro  23.05.2022                   3             1
85                   Ukraine  25.06.2022                   1             1
2                 Antarctica  06.12.2022                   1             1
24               El Salvador  19.01.2023                  16             7
6                 Bangladesh  25.05.2023                   4             2
54                    Mexico  27.09.2023                  80             9
48                   Lebanon  12.05.2024                  85             7
77               South Korea  29.05.2024                   7             1
36                   Iceland  24.07.2024                   3             1
84                    Uganda  18.09.2024                   7             1
62           North Macedonia  02.10.2024                  72             8
26                  Ethiopia  06.11.2024                   9             4
57                Mozambique  10.12.2024                   1             1
72              Saudi Arabia  06.07.2025                   1             1
13                      Chad  16.01.2026                   5             1

Then, the date of the first observation per country is plotted on a map, this is an overview.

In [96]:
# uses first_countries

world = gpd.read_file(f"../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})
first_countries["first_date"] = pd.to_datetime(first_countries["first_date"])
first_countries["year"] = first_countries["first_date"].dt.year

bins = [2016, 2017, 2018, 2019, 2020, 2022, 2024, 2026]
labels = ["2017 (Feb-Dec)","2018","2019","2020","2021-2022","2023-2024","2025-2026 (Jan)"]
first_countries["year_bin"] = pd.cut(first_countries["year"], bins=bins, labels=labels)
first_countries["ISO_A3"] = first_countries["Country"].apply(own.get_iso3)

map_df = world.merge(first_countries, left_on="Country", right_on="Country", how="left").to_crs("+proj=robin")

fig, ax = plt.subplots(1, 1, figsize=(16, 8))

cmap = get_cmap("Blues_r", len(labels))
legend_handles = [
    Patch(facecolor=cmap(i / (len(labels) - 1)), edgecolor="black", linewidth=0.5, label=labels[i])
    for i in range(len(labels))
]
legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))

map_df.plot(
    column="year_bin",
    cmap="Blues_r",
    linewidth=0.5,
    edgecolor="black",
    missing_kwds={"color": "grey"},
    legend=False,
    categorical=True,
    ax=ax
)

ax.legend(handles=legend_handles, title="Year", title_fontsize=15, loc="lower left")
for text in legend.get_texts():
        text.set_fontsize(12)
ax.set_title("First Observation per Country", fontsize=18)
ax.set_axis_off()

filepath = f"../Products/first_obs_per_Country_total.png"
plt.savefig(filepath, dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\24111754.py:17: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))

Then, monthly maps of first observations are created (same colors as the one above).

In [102]:
# uses first_countries

world = gpd.read_file(f"../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})
first_countries["ISO_A3"] = first_countries["Country"].apply(own.get_iso3)
first_countries["first_date"] = pd.to_datetime(first_countries["first_date"])

bins = [2016, 2017, 2018, 2019, 2020, 2022, 2024, 2026]
labels = ["2017 (Feb-Dec)","2018","2019","2020","2021-2022","2023-2024","2025-2026 (Apr)"]
first_countries["year_bin"] = pd.cut(first_countries["first_date"].dt.year, bins=bins, labels=labels)

# sort months
all_months = pd.period_range(first_countries["first_date"].min(), first_countries["first_date"].max() + pd.offsets.MonthEnd(5), freq="M")

# generate monthly maps
saved_files = []
for month in all_months:
    current = first_countries[first_countries["first_date"] <= month.to_timestamp()]
    if current.empty:
        continue
    
    map_df = world.merge(current, left_on="Country", right_on="Country", how="left").to_crs("+proj=robin")
    
    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    cmap = get_cmap("Blues_r", len(labels))
    legend_handles = [
        Patch(facecolor=cmap(i / (len(labels) - 1)), edgecolor="black", linewidth=0.5, label=labels[i])
        for i in range(len(labels))
    ]
    legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))

    map_df.plot(
        column="year_bin",
        cmap="Blues_r",
        linewidth=0.5,
        edgecolor="black",
        missing_kwds={"color": "grey"},
        categorical=True,
        legend=False,
        ax=ax
    )

    ax.legend(handles=legend_handles, title="Year", title_fontsize=15, loc="lower left")
    for text in legend.get_texts():
        text.set_fontsize(12)
    ax.set_title(f"Countries with Observations up to (including) {month-1}", fontsize=18)
    ax.set_axis_off()
    
    filepath = f"../Products/Monthly_first_obs_Maps/{month-1}.png"
    plt.savefig(filepath, dpi=300, bbox_inches="tight")
    plt.close()

    saved_files.append(filepath) # for the following GIF

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4153336744.py:26: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Blues_r", len(labels))

In [103]:
# create GIF

own.gif_maker(*saved_files, path="../Products/Monthly_first_obs_Maps/Animation", duration=200)

Monthly Maps with active/inactive countries.

In [ ]:
world = gpd.read_file("../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

df["ISO_A3"] = df["Country"].apply(own.get_iso3)

pd.set_option("display.max_columns", None)
df.head(3)

countries_ever = set(df["ISO_A3"].dropna().unique())
all_months = pd.period_range(
    df["year_month"].min(),
    df["year_month"].max(),
    freq="M"
)

for month in all_months:
    
    # countries with observations in this month
    current_active = set(
        df.loc[df["year_month"] == month, "ISO_A3"].dropna().unique()
    )
    
    # copy of world map
    map_df = world.copy().to_crs("+proj=robin")
    
    # create status column
    def classify_country(iso):
        if iso in current_active:
            return "Active"
        elif iso in countries_ever:
            return "Inactive"
        else:
            return "Never active"
    
    map_df["status"] = map_df["ADM0_A3"].apply(classify_country)
    
    # plot
    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    categories = ["Active", "Inactive", "Never active"]
    map_df["status"] = pd.Categorical(map_df["status"], categories=categories)

    # define colors
    cmap = mcolors.ListedColormap(["blue", "#df6a91", "grey"])
    color_map = {
        "Active": "blue",
        "Inactive": "#df6a91",
        "Never active": "grey"
    }

    fig, ax = plt.subplots(1, 1, figsize=(16, 8))

    map_df.plot(
        column="status",
        categorical=True,
        cmap=cmap,
        linewidth=0.5,
        edgecolor="black",
        legend=False,
        ax=ax
    )

    legend_handles = [
        Patch(facecolor=color, edgecolor="black", linewidth=0.5, label=label)
        for label, color in color_map.items()
    ]
    
    ax.legend(handles=legend_handles, title="Country Status", title_fontsize=12, loc="lower left")
    ax.set_title(f"Active Countries in {month}", fontsize=15)
    ax.set_axis_off()
    
    plt.savefig(f"../Products/Monthly_active_Countries_Maps/{month}.png",
                dpi=300, bbox_inches="tight")
    plt.close()

Now do the same thing for actual spots, not whole countries.

In [107]:
world = gpd.read_file("../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")

df["geometry"] = df.apply(
    lambda row: Point(row["longitude"], row["latitude"]), axis=1
)

gdf = gpd.GeoDataFrame(
    df,
    geometry="geometry",
    crs="EPSG:4326"
).to_crs("+proj=robin")

all_months = pd.period_range(
    gdf["year_month"].min(),
    gdf["year_month"].max(),
    freq="M"
)

for month in all_months:

    fig, ax = plt.subplots(1, 1, figsize=(16, 8))
    
    # map below
    world.to_crs("+proj=robin").plot(
        ax=ax,
        color="grey",
        edgecolor="black",
        linewidth=0.5
    )
    
    # active spots in this month
    active = gdf[gdf["year_month"] == month]
    
    # all other spots
    inactive = gdf[gdf["year_month"] < month]
    
    # first plot inactive ones
    inactive.plot(
        ax=ax,
        color="red",
        markersize=5,
        alpha=0.4
    )
    
    # then active ones
    active.plot(
        ax=ax,
        color="blue",
        markersize=8,
        alpha=0.8
    )

    active_patch = mpatches.Patch(facecolor="blue", edgecolor="black", linewidth=0.5, label="Active")
    inactive_patch = mpatches.Patch(facecolor="red", edgecolor="black", linewidth=0.5, label="Inactive")

    legend = ax.legend(
        handles=[active_patch, inactive_patch],
        title="Spot Status",
        loc="lower left",
        frameon=True
    )

    legend.get_title().set_fontsize(15)
    for text in legend.get_texts():
        text.set_fontsize(12)
    
    ax.set_title(f"Active Observation Spots in {month}", fontsize=18)
    ax.set_axis_off()
    
    plt.savefig(f"../Products/Monthly_active_Spots_Maps/{month}.png",
                dpi=300, bbox_inches="tight")
    plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4001877958.py:4: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")
C:\Users\yanni\AppData\Local\Temp\ipykernel_39640\4001877958.py:43: UserWarning: The GeoDataFrame you are attempting to plot is empty. Nothing has been displayed.
  inactive.plot(