In [1]:
import requests
import pandas as pd
from datetime import datetime, timezone
import time
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import matplotlib.patches as mpatches
from matplotlib.colors import BoundaryNorm
from matplotlib.cm import get_cmap
from matplotlib.patches import Patch, Rectangle
import ast
import folium
from folium.plugins import MarkerCluster
import reverse_geocoder as rg
import re
import pycountry
import os
import numpy as np
import geopandas as gpd
import fiona
import sys
from shapely.geometry import Point
from sklearn.cluster import DBSCAN
import ruptures as rpt
from haversine import haversine
import functions as own
from timezonefinder import TimezoneFinder
import zoneinfo
from scipy.stats import gaussian_kde
from scipy.stats import chisquare, kruskal, mannwhitneyu, spearmanr
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from libpysal.weights import lat2W
from libpysal.weights import Queen
from libpysal.weights import DistanceBand
from esda.moran import Moran_Local, Moran
from shapely.geometry import box

First look at the data

In [2]:
df = pd.read_csv("../CWData_clean7.csv")
pd.set_option("display.max_columns", None)
df.head()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\3727079677.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

,id,root_id,category,description,latitude,longitude,spotted_at,spotted_by,spotted_by_type,spotted_by_name,spotted_by_topic_role,created_at,created_at_local,created_by,modified_at,modified_by,date,year_month,Country,Region,City,top_country,top_country_count,total_obs_user,first_country,percent_in_country,Category,Category_Nr,Waterlevel_Virtual,SoilMoisture,SoilMoisture_Nr,TempStream,TempStream_Nr,Plastic_Amount,Plastic_Amount_Nr,Stream_Width,Stream_Depth,Streambed_Material,Streambed_Material_Nr,FlowVelocity_Method,FlowVelocity_Method_Nr,FlowVelocity_direct_vel,FlowVelocity_PS_dist,FlowVelocity_PS_time1,FlowVelocity_PS_time2,FlowVelocity_PS_time3,Plastic_ObservationTime,Plastic_Location,Plastic_Location_Nr,Plastic_RiverWidth,Plastic_RiverWidth_Nr,Plastic_PET,Plastic_PET_Nr,Plastic_POSoft,Plastic_POSoft_Nr,Plastic_POHard,Plastic_POHard_Nr,Plastic_PS,Plastic_PS_Nr,Plastic_PSE,Plastic_PSE_Nr,Plastic_PMultilayer,Plastic_PMultilayer_Nr,Plastic_POther,Plastic_POther_Nr,Plastic_Shore_Plotsize,Plastic_Shore_Plotsize_Nr,Plastic_Removed,Plastic_River_Stagnant,Waterlevel_Physical_Unit,Waterlevel_Physical_Unit_Nr,Waterlevel_Physical,Streamtype,Streamtype_Nr,Swimming_Quality,Drinking_Quality,Naturality,Naturality_Nr,StreamColor,StreamColor_Nr,Stream_Ground_Visibility,Stream_Ground_Visibility_Nr,Stream_Animals,Stream_Pollution_Reason,Stream_sometimes_dry,Stream_Name,TempStream_snow_ice,Stream_Waterquality,Stream_Waterquality_Nr,Stream_Waterclarity,Stream_Waterclarity_Nr,StreamColor_other,Stream_Vegetation,Stream_Foam,Stream_Foam_Nr,Stream_Algae,Stream_Algae_Nr,Stream_Odor,Stream_Odor_Type,Stream_Odor_Type_Nr,Stream_Odor_Type_other,Stream_Litter,Stream_Litter_Nr,Stream_Flow_Alteration,Stream_Flow_Alteration_Nr,Stream_typical_Color,Stream_typical_Color_Nr,Stream_Drainage_Basin,Stream_Drainage_Basin_Nr,Watertype,Watertype_Nr,Lake_Usage,Lake_Usage_Nr,Lake_Access,Lake_Shore_State,Lake_Shore_State_Nr,Lake_Swimming,Lake_Transparency,Lake_Transparency_Nr,Lake_Color,Lake_Color_Nr,Lake_Odor,Lake_Odor_Nr,Lake_Shore_Vegetation,Lake_Shore_Vegetation_Nr,Lake_Underwater_Vegetation,Lake_Floating_Leaveplants,Lake_Duckweed,Lake_Duckweed_Nr,Lake_Mussels,Lake_Mussels_Nr,Lake_Deadwood,Lake_Deadwood_Nr,Lake_Animals,Lake_Animals_Nr,Lake_Waterlevel_Changes,Lake_Waterlevel_Changes_Nr,Lake_Dry,Lake_Dry_Nr,Image_Gallery,image,geo_hash
0,16726,16726,470,Bei der Brücke am Parkplatz der Pizolbahn,47.029225,9.433322,2017-02-05 14:49:14,1996,2,Simon Meili,editor,2017-02-05 13:49:16,2017-02-05 14:49:16,1996,2019-12-29 12:55:32,11596.0,2017-02-05,2017-02,Switzerland,Sankt Gallen,Vaduz,Switzerland,155,246,Switzerland,63.00813,virtual scale,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River and Land,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17726.0,000007/2017/02/11ba68865090752368e3a24f55058a24,u0qew9mjh6fw
1,16727,16726,470,NaN,47.029225,9.433322,2017-02-05 14:50:00,1996,2,Simon Meili,editor,2017-02-05 13:50:58,2017-02-05 14:50:58,1996,2026-03-19 15:21:53,118221.0,2017-02-05,2017-02,Switzerland,Sankt Gallen,Vaduz,Switzerland,155,246,Switzerland,63.00813,virtual scale,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,0.05,gravel,2.0,poo-stick,2.0,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River and Land,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17727.0,000007/2017/02/2f43e32aa5f88ed53822f9a75f9155ea,u0qew9mjh6fw
2,16736,16736,469,NaN,47.398311,8.543917,2017-02-10 08:36:00,1996,2,Simon Meili,editor,2017-02-10 15:48:11,2017-02-10 16:48:11,1996,2026-03-19 15:21:53,118221.0,2017-02-10,2017-02,Switzerland,Zürich,Zürich,Switzerland,155,246,Switzerland,63.00813,soil moisture,2,NaN,immediately wet,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River and Land,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17736.0,000007/2017/02/912b50b8cb2200e7f0fab88a7426e920,u0qjdkt7ptw6
3,16737,16737,470,NaN,47.560411,7.589407,2017-02-11 12:36:29,2005,1,Barbara Strobl,editor,2017-02-11 11:36:29,2017-02-11 12:36:29,2005,2019-12-29 12:55:45,11596.0,2017-02-11,2017-02,Switzerland,Basel-Stadt,Basel,Switzerland,252,322,Switzerland,78.26087,virtual scale,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gravel,2.0,poo-stick,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River and Land,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17737.0,000007/2017/03/b8d2705115f82a7c34e0b39cadf7415e,u0mqsdn7qp0n
4,16740,16740,470,NaN,47.127880,8.744036,2017-02-12 10:39:27,1996,2,Simon Meili,editor,2017-02-12 09:39:26,2017-02-12 10:39:26,1996,2019-12-29 12:55:48,11596.0,2017-02-12,2017-02,Switzerland,Schwyz,Schwyz,Switzerland,155,246,Switzerland,63.00813,virtual scale,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,River and Land,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17740.0,000007/2017/02/a0fe95aeebbab149d2aed0e603238b44,u0qhngr5yc9f

Here, I create an overview map with all the observation points. Locations with more observations get bigger points.

In [3]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

counts = df.groupby(["latitude", "longitude"]).size().reset_index(name="count")

map_center = [df["latitude"].mean(),df["longitude"].mean()]
m = folium.Map(location=map_center, zoom_start=7)

for _, row in counts.iterrows():
    folium.Circle(
        location = [row["latitude"], row["longitude"]],
        radius = 5 + row["count"] * 2,
        color=  "blue",
        fill = True,
        fill_color = "blue",
        fill_opacity = 0.5
    ).add_to(m)

m

m.save("../Products/Overview.html")

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2451309005.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

The same map is produced as a static map

In [4]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])
world = gpd.read_file(f"../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")
world = world.rename(columns={"NAME": "Country"})

counts = df.groupby(["latitude", "longitude"]).size().reset_index(name="count")

gdf_points = gpd.GeoDataFrame(
    counts,
    geometry=gpd.points_from_xy(counts["longitude"], counts["latitude"]),
    crs="EPSG:4326"
).to_crs("+proj=robin")

map_df_all = world.to_crs("+proj=robin")

fig, ax = plt.subplots(1, 1, figsize=(16, 8))

# plot world map
map_df_all.plot(
    color="lightgrey",
    edgecolor="black",
    linewidth=0.5,
    ax=ax
)

# plot points
gdf_points.plot(
    ax=ax,
    color="teal",
    edgecolor="black",
    linewidth=0.3,
    alpha=0.7,
    markersize=np.log1p(gdf_points["count"]) * 40
)

legend_counts = [1, 10, 50, 100]
legend_handles = [
    plt.scatter([], [], s=np.log1p(c) * 40, color="teal", edgecolor="black", linewidth=0.3, alpha=0.7, label=str(c))
    for c in legend_counts
]
legend = ax.legend(
    handles=legend_handles,
    title="Observations",
    loc="lower left",
    frameon=True,
    labelspacing=1.5,
)
legend.get_title().set_fontsize(15)
for text in legend.get_texts():
    text.set_fontsize(12)

ax.set_title("All Observations", fontsize=18)
ax.set_axis_off()

plt.savefig("../Products/Overview.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\1735340019.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Then, a bar chart with 3 subplots of number of observations per country, number of users per country and average number of observations per user per country

In [5]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

# data
country_freq = df["Country"].value_counts()
users_per_country = df.groupby("Country")["created_by"].nunique().sort_values(ascending=False)
obs_per_user_country = (country_freq / users_per_country).dropna()

top50_countries = country_freq.head(50).index.tolist()

# obs per country
top50_obs = country_freq[country_freq.index.isin(top50_countries)].reindex(top50_countries)
other_obs = pd.Series({"Other (Average)": country_freq[~country_freq.index.isin(top50_countries)].mean()})
obs_plot = pd.concat([top50_obs, other_obs])

# users per country
top50_users = users_per_country[users_per_country.index.isin(top50_countries)].reindex(top50_countries)
other_users = pd.Series({"Other (Average)": users_per_country[~users_per_country.index.isin(top50_countries)].mean()})
users_plot = pd.concat([top50_users, other_users])

# avg obs per user per country
top50_opu = obs_per_user_country[obs_per_user_country.index.isin(top50_countries)].reindex(top50_countries)
other_opu = pd.Series({"Other (Average)": obs_per_user_country[~obs_per_user_country.index.isin(top50_countries)].mean()})
opu_plot = pd.concat([top50_opu, other_opu])

# plot
fig, axes = plt.subplots(3, 1, figsize=(16, 23), sharex=True)

obs_plot.plot(kind="bar", color="teal", ax=axes[0], logy=True, fontsize=13)
axes[0].set_title("a) Number of Observations per Country", fontsize=21, fontweight="bold", loc="left")
axes[0].set_ylabel("Number of Observations", fontsize=18)
axes[0].grid(axis="y", linestyle="--", alpha=0.5)
axes[0].set_axisbelow(True)

users_plot.plot(kind="bar", color="teal", ax=axes[1], logy=True, fontsize=13)
axes[1].set_title("b) Number of Users per Country", fontsize=21, fontweight="bold", loc="left")
axes[1].set_ylabel("Number of Users", fontsize=18)
axes[1].grid(axis="y", linestyle="--", alpha=0.5)
axes[1].set_axisbelow(True)

opu_plot.plot(kind="bar", color="teal", ax=axes[2], fontsize=13)
axes[2].set_title("c) Average Number of Observations per User per Country", fontsize=21, fontweight="bold", loc="left")
axes[2].set_ylabel("Average Number of Observations per User", fontsize=18)
axes[2].grid(axis="y", linestyle="--", alpha=0.5)
axes[2].set_axisbelow(True)
axes[2].set_xlabel("Country", fontsize=18)
axes[2].tick_params(axis="x", rotation=90)

# alternating background
for i in range(0, len(obs_plot), 2):
    for ax in axes:
        ax.axvspan(i - 0.5, i + 0.5, color="grey", alpha=0.3, zorder=0)

plt.tight_layout()
plt.savefig("../Products/country_stats_combined.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\1784754425.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

As table + stats

In [7]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

country_freq = df["Country"].value_counts()

pd.set_option("display.max_rows", None)
print(len(country_freq))
print(len(country_freq[country_freq < 11]))
country_freq

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\1245431676.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

90
35

Country
Switzerland                 24086
Germany                     12720
Austria                      6247
United Kingdom               5419
France                       2293
Canada                       2175
United States of America     1991
Estonia                      1681
Spain                        1611
Italy                        1431
Ireland                       966
Chile                         947
Netherlands                   926
Kyrgyzstan                    785
Costa Rica                    629
Greece                        612
Cyprus                        542
Portugal                      410
Australia                     357
Sweden                        249
Guatemala                     237
Hungary                       182
Malaysia                      156
Norway                        153
Brazil                        148
Malta                         142
Indonesia                     124
Argentina                     110
Slovakia                      110
Philippines                   104
Lebanon                        86
China                          85
North Macedonia                83
Russia                         80
Mexico                         80
Ecuador                        69
Luxembourg                     52
Czechia                        43
Serbia                         28
Uruguay                        28
Morocco                        27
Liechtenstein                  25
Bulgaria                       25
Slovenia                       23
Poland                         23
Finland                        21
Croatia                        19
India                          18
Kenya                          18
Belgium                        18
New Zealand                    16
El Salvador                    16
Peru                           15
Colombia                       15
Iran                           12
Denmark                         9
Ethiopia                        9
Lithuania                       8
Japan                           8
South Africa                    7
South Korea                     7
Uganda                          7
Chad                            5
Latvia                          4
Kazakhstan                      4
Romania                         4
Cambodia                        4
Bangladesh                      4
Cameroon                        3
Uzbekistan                      3
Montenegro                      3
Antarctica                      3
Iceland                         3
Thailand                        2
Honduras                        2
Egypt                           2
Rwanda                          2
Taiwan                          2
Ghana                           2
Afghanistan                     1
Albania                         1
Nicaragua                       1
Nigeria                         1
Georgia                         1
Panama                          1
Trinidad and Tobago             1
Israel                          1
Ukraine                         1
Mozambique                      1
Saudi Arabia                    1
Name: count, dtype: int64

As table

In [8]:
pd.set_option("display.max_rows", None)
users_per_country.sort_index(ascending=True)

Country
Afghanistan                    1
Albania                        1
Antarctica                     2
Argentina                     19
Australia                     14
Austria                       95
Bangladesh                     2
Belgium                        6
Brazil                        46
Bulgaria                       3
Cambodia                       2
Cameroon                       1
Canada                        47
Chad                           1
Chile                         46
China                          8
Colombia                       6
Costa Rica                   181
Croatia                        6
Cyprus                         4
Czechia                       12
Denmark                        3
Ecuador                       23
Egypt                          2
El Salvador                    7
Estonia                        7
Ethiopia                       4
Finland                        4
France                        77
Georgia                        1
Germany                      494
Ghana                          2
Greece                        24
Guatemala                      8
Honduras                       2
Hungary                       14
Iceland                        1
India                          9
Indonesia                     11
Iran                           3
Ireland                       42
Israel                         1
Italy                         69
Japan                          6
Kazakhstan                     2
Kenya                          3
Kyrgyzstan                    34
Latvia                         3
Lebanon                        7
Liechtenstein                  5
Lithuania                      3
Luxembourg                     8
Malaysia                       8
Malta                          4
Mexico                         9
Montenegro                     1
Morocco                        3
Mozambique                     1
Netherlands                  126
New Zealand                    6
Nicaragua                      1
Nigeria                        1
North Macedonia               14
Norway                        53
Panama                         1
Peru                           5
Philippines                   85
Poland                         9
Portugal                      12
Romania                        1
Russia                         6
Rwanda                         1
Saudi Arabia                   1
Serbia                         1
Slovakia                       6
Slovenia                       7
South Africa                   2
South Korea                    1
Spain                         28
Sweden                        26
Switzerland                 1929
Taiwan                         1
Thailand                       1
Trinidad and Tobago            1
Uganda                         1
Ukraine                        1
United Kingdom               157
United States of America     147
Uruguay                        5
Uzbekistan                     3
Name: created_by, dtype: int64

As table

In [9]:
obs_per_user_country.sort_values(ascending=False)

Country
Estonia                     240.142857
Cyprus                      135.500000
Austria                      65.757895
Spain                        57.535714
Canada                       46.276596
Malta                        35.500000
United Kingdom               34.515924
Portugal                     34.166667
France                       29.779221
Guatemala                    29.625000
Serbia                       28.000000
Germany                      25.748988
Australia                    25.500000
Greece                       25.500000
Kyrgyzstan                   23.088235
Ireland                      23.000000
Italy                        20.739130
Chile                        20.586957
Malaysia                     19.500000
Slovakia                     18.333333
United States of America     13.544218
Russia                       13.333333
Hungary                      13.000000
Switzerland                  12.486262
Lebanon                      12.285714
Indonesia                    11.272727
China                        10.625000
Sweden                        9.576923
Morocco                       9.000000
Mexico                        8.888889
Bulgaria                      8.333333
Netherlands                   7.349206
South Korea                   7.000000
Uganda                        7.000000
Luxembourg                    6.500000
Kenya                         6.000000
North Macedonia               5.928571
Argentina                     5.789474
Uruguay                       5.600000
Finland                       5.250000
Chad                          5.000000
Liechtenstein                 5.000000
Romania                       4.000000
Iran                          4.000000
Czechia                       3.583333
South Africa                  3.500000
Costa Rica                    3.475138
Slovenia                      3.285714
Brazil                        3.217391
Croatia                       3.166667
Ecuador                       3.000000
Cameroon                      3.000000
Denmark                       3.000000
Belgium                       3.000000
Montenegro                    3.000000
Peru                          3.000000
Iceland                       3.000000
Norway                        2.886792
Lithuania                     2.666667
New Zealand                   2.666667
Poland                        2.555556
Colombia                      2.500000
El Salvador                   2.285714
Ethiopia                      2.250000
Bangladesh                    2.000000
Cambodia                      2.000000
Taiwan                        2.000000
Rwanda                        2.000000
Thailand                      2.000000
Kazakhstan                    2.000000
India                         2.000000
Antarctica                    1.500000
Latvia                        1.333333
Japan                         1.333333
Philippines                   1.223529
Egypt                         1.000000
Albania                       1.000000
Afghanistan                   1.000000
Ghana                         1.000000
Georgia                       1.000000
Honduras                      1.000000
Israel                        1.000000
Mozambique                    1.000000
Nicaragua                     1.000000
Nigeria                       1.000000
Panama                        1.000000
Saudi Arabia                  1.000000
Trinidad and Tobago           1.000000
Ukraine                       1.000000
Uzbekistan                    1.000000
dtype: float64

More bar charts. Here, for the number of observations per user. Since there are a lot of users, only the ones with 50 or more observations are shown.

In [10]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

User_freq = df["created_by"].value_counts()

top100 = User_freq.head(100)
other = pd.Series({"Other": User_freq.iloc[100:].sum()})
User_freq_plot = pd.concat([top100, other])

ax = User_freq_plot.plot(kind="bar", color="teal", figsize=(16,9), logy = True, fontsize=12)

plt.title("Number of Observations per User", fontsize=20)
plt.ylabel("Number of Observations", fontsize=17)
plt.xticks(rotation=90)

#for p in ax.patches: # absolute counts above bars
#    ax.annotate(
#        f'{int(p.get_height())}', 
#        (p.get_x() + p.get_width() / 2., p.get_height()), 
#        ha='center', 
#        va='bottom', 
#        fontsize=10,
#        xytext=(0, 5),
#        textcoords='offset points',
#        rotation=90
#    )

ax.annotate( # bracket
    "",
    xy=(0.492, -0.03),
    xytext=(0.9, -0.03),
    xycoords="axes fraction",
    textcoords="axes fraction",
    arrowprops=dict(arrowstyle="-[, widthB=43.85, lengthB=0.5, angleB=270", color="black", lw=1.5)
)

ax.plot( # line connecting to bracket
    [0.492, 0.492],
    [-0.03, -0.05],
    color="black", 
    lw=1.5, 
    transform=ax.transAxes,
    clip_on=False
)

ax.text( # label for bracket
    0.492,
    -0.08,
    "Individual Users",
    transform=ax.transAxes,
    fontsize=12,
    ha="center"
)

ax.grid(axis="y", linestyle="--", alpha=0.5, which="both")
ax.set_axisbelow(True)
ax.set_ylim(0,30000)
ax.set_xticks([])
ax.set_xticks([len(User_freq_plot) - 1])
ax.set_xticklabels(["Other users"], fontsize=12)

plt.savefig(f"../Products/obs_per_User.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2630018885.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")
C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2630018885.py:57: UserWarning: Attempt to set non-positive ylim on a log-scaled axis will be ignored.
  ax.set_ylim(0,30000)

How many users in total? How many users with ten or less?

In [20]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

User_freq = df["created_by"].value_counts()

print(len(User_freq))
print(len(User_freq[User_freq < 6]))
print(User_freq[User_freq > 700].sum()/User_freq.sum())
User_freq

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2332184767.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

3749
2916
0.5039512436940483

created_by
28919     3841
35124     3764
30178     3546
95692     2406
29542     1992
3065      1967
2316      1805
15185     1762
27610     1647
52314     1647
6542      1465
12938     1371
17235     1263
7079      1087
7867       939
16741      919
64828      837
82037      810
11370      769
2267       727
66748      689
29254      681
11290      539
476        517
109461     457
28674      455
17059      453
77721      427
31773      415
33894      415
13032      399
68724      389
15038      387
39422      377
25925      326
2005       322
23813      300
93344      295
2203       282
38002      281
11175      279
14034      274
52028      266
49909      257
31758      249
1996       246
111531     223
56020      216
11596      197
37254      196
15989      184
36126      171
6529       162
16176      155
95590      155
94379      147
32346      142
62827      140
65591      140
121939     140
95596      136
14100      134
65505      133
40769      132
2270       130
95588      113
6521       111
14183      109
39107      109
35073      108
72995      106
44572      105
49002      105
13622      104
78277      102
2471       101
5514       101
14939      101
101765      99
87715       98
7251        93
64587       93
15622       91
11960       84
96936       83
18260       82
90857       80
91266       78
99185       78
77497       77
95598       77
16090       75
95587       75
123349      75
15991       74
61784       74
29636       72
78276       70
86360       70
6400        69
67692       69
79111       69
90691       69
122610      69
5753        68
11266       68
95597       64
95475       64
90065       64
5659        63
14545       63
31811       63
2258        62
24444       58
33977       58
4424        57
24968       57
61155       57
87709       57
122129      57
84936       56
31367       55
5588        55
54690       55
116168      55
63460       53
64633       53
91255       53
100640      53
109473      53
13422       52
14527       52
83091       52
102806      52
39908       51
88178       51
95599       51
111303      51
2277        50
15867       50
28605       48
30281       48
72946       48
76555       48
99151       48
105992      48
8859        48
111283      48
7726        47
14098       47
95476       47
102714      47
6055        46
13547       46
96924       46
6339        44
56559       44
86817       44
104236      44
3431        43
14741       43
76545       43
90792       43
111695      43
33975       42
39083       42
4264        41
24208       41
39518       41
52317       41
77727       41
75377       41
85987       41
118667      41
16053       40
13682       40
28317       40
122382      40
36226       39
30203       38
97384       38
477         37
15829       37
75367       37
84291       37
10997       35
37136       35
37275       35
18142       35
61266       35
95601       35
93086       35
114478      35
123159      35
24232       34
28067       34
78929       34
2555        33
29342       33
73126       33
61490       33
80639       33
94700       33
103881      33
13907       32
40016       32
98295       32
97335       32
122523      32
24679       31
28710       31
59664       31
97345       31
107549      31
111742      31
72239       30
52104       30
97412       30
23703       29
37121       29
119276      29
32147       28
34758       28
62653       28
78030       28
102281      28
119555      28
60741       27
70235       27
71953       27
78315       27
78702       27
122130      27
12177       26
38965       26
63009       26
5462        26
70520       26
78242       26
86607       26
114456      26
2265        25
16272       25
17581       25
18567       25
21797       25
52506       25
82474       25
2268        24
5751        24
2760        24
32350       24
60096       24
77381       24
89765       24
92152       24
5798        23
33761       23
58829       23
77865       23
93622       23
97336       23
95220       23
119125      23
3021        22
68934       22
83093       22
123593      22
2283        21
14000       21
34344       21
38423       21
34688       21
39888       21
39938       21
71939       21
71946       21
77375       21
71949       21
86499       21
115774      21
121850      21
8655        20
14978       20
17921       20
23956       20
51631       20
56212       20
56573       20
93692       20
94414       20
103889      20
105899      20
117607      20
2233        19
3755        19
94023       19
95751       19
98520       19
7408        18
15494       18
27645       18
30257       18
32036       18
11614       18
51824       18
55896       18
32535       18
66122       18
67162       18
71954       18
71964       18
63981       18
16056       18
94339       18
97352       18
98447       18
101470      18
106399      18
113971      18
119593      18
21396       17
32198       17
44598       17
54147       17
74361       17
78085       17
71952       17
84251       17
94272       17
94667       17
97617       17
6397        17
99209       17
120365      17
129697      17
4375        16
11226       16
28321       16
32010       16
32067       16
33693       16
36897       16
3072        16
71951       16
96982       16
83239       16
103506      16
107749      16
118122      16
123113      16
125709      16
2227        15
2894        15
4152        15
8735        15
15852       15
24982       15
37852       15
69641       15
74724       15
77374       15
77384       15
86688       15
104904      15
111457      15
122482      15
2474        14
25370       14
28712       14
28682       14
37064       14
39305       14
61782       14
75117       14
107004      14
103977      14
120009      14
120068      14
121951      14
123496      14
124456      14
16545       13
17596       13
21554       13
25376       13
27706       13
36896       13
39964       13
39467       13
64131       13
68160       13
69306       13
71945       13
17208       13
81896       13
92002       13
94523       13
94691       13
97373       13
115606      13
118329      13
120505      13
120058      13
57968       13
43206       13
124455      13
24641       12
24695       12
27577       12
28869       12
38736       12
56265       12
57274       12
61768       12
62630       12
63035       12
63023       12
64124       12
77946       12
78311       12
76490       12
93920       12
94344       12
95591       12
97337       12
101708      12
104553      12
93063       12
124546      12
129836      12
9006        11
14849       11
32579       11
34139       11
37598       11
38446       11
59962       11
60829       11
62941       11
65467       11
66101       11
73058       11
77382       11
78141       11
78481       11
78501       11
77649       11
87691       11
89938       11
95009       11
87713       11
105370      11
111156      11
117785      11
120912      11
120913      11
123352      11
129460      11
2511        10
3042        10
7625        10
16171       10
25575       10
27129       10
30595       10
24720       10
33708       10
36554       10
37341       10
38416       10
38775       10
39133       10
57167       10
61986       10
73165       10
75205       10
71942       10
77376       10
79366       10
79211       10
82997       10
87164       10
80609       10
95055       10
95589       10
101029      10
92696       10
103934      10
108071      10
108787      10
109340      10
114212      10
117726      10
120066      10
120055      10
120053      10
123415      10
123498      10
123582      10
123587      10
123584      10
123636      10
123894      10
129926      10
6097         9
7209         9
9126         9
14532        9
15693        9
15923        9
15922        9
24713        9
25387        9
28887        9
32071        9
32207        9
31976        9
33740        9
34504        9
37735        9
40104        9
42105        9
43765        9
57470        9
60095        9
64543        9
78109        9
81473        9
81470        9
86286        9
87426        9
87417        9
87420        9
87421        9
87448        9
87446        9
92740        9
93188        9
93727        9
94158        9
94059        9
104176       9
111017       9
111737       9
115800       9
120062       9
120729       9
120916       9
122053       9
123192       9
123589       9
123586       9
123583       9
123585       9
123633       9
123634       9
123632       9
123631       9
123635       9
108421       9
124318       9
3939         8
14567        8
12754        8
22068        8
20621        8
23702        8
25386        8
25385        8
25372        8
30397        8
32082        8
32578        8
33066        8
34502        8
34507        8
34631        8
34505        8
33638        8
36144        8
36386        8
37522        8
36906        8
38316        8
39739        8
39626        8
39951        8
40040        8
39445        8
39517        8
42106        8
42101        8
42107        8
42109        8
42103        8
42100        8
42104        8
42102        8
48485        8
52016        8
52124        8
52368        8
59726        8
62984        8
64580        8
62627        8
67308        8
71271        8
78106        8
78114        8
78113        8
78193        8
78116        8
78108        8
78107        8
78112        8
79608        8
81475        8
83087        8
86952        8
87388        8
87430        8
87447        8
87309        8
87369        8
87383        8
89331        8
90509        8
89722        8
87307        8
87427        8
87428        8
87419        8
87425        8
87442        8
87418        8
87379        8
93726        8
87444        8
94632        8
95546        8
97223        8
95844        8
98623        8
98125        8
102384       8
107065       8
119037       8
119068       8
121205       8
119667       8
119770       8
122515       8
123497       8
123581       8
123638       8
6905         7
6707         7
7250         7
3563         7
8195         7
8901         7
11921        7
16508        7
16483        7
17070        7
15916        7
17205        7
18074        7
22924        7
24523        7
25390        7
27705        7
34503        7
34637        7
34509        7
34506        7
36142        7
36145        7
36140        7
36143        7
36146        7
36147        7
37071        7
38059        7
38749        7
39307        7
47439        7
49608        7
49993        7
52234        7
34086        7
56616        7
62853        7
63466        7
65498        7
71286        7
74313        7
76619        7
76588        7
78110        7
78115        7
78725        7
79358        7
81086        7
81482        7
81487        7
81488        7
83023        7
85196        7
73619        7
86138        7
86687        7
87161        7
93884        7
77739        7
96499        7
96605        7
98799        7
91249        7
103669       7
105415       7
106384       7
107865       7
104698       7
110535       7
97762        7
111089       7
119846       7
120662       7
122073       7
122715       7
124783       7
124913       7
123756       7
129883       7
2436         6
2505         6
3756         6
3924         6
3914         6
3940         6
3928         6
3951         6
5765         6
6610         6
7970         6
11538        6
8716         6
13925        6
6731         6
16120        6
14104        6
16849        6
22189        6
24980        6
26106        6
26098        6
25389        6
27048        6
27763        6
24996        6
32052        6
32197        6
32437        6
32581        6
32254        6
32694        6
34097        6
33973        6
36149        6
33969        6
36985        6
36806        6
36900        6
36899        6
38383        6
39194        6
39784        6
40662        6
41636        6
51008        6
55839        6
56237        6
57568        6
57523        6
59813        6
64506        6
65496        6
71941        6
77643        6
70398        6
78169        6
78177        6
78117        6
52997        6
79361        6
81483        6
81455        6
81477        6
81480        6
81175        6
87449        6
87466        6
90197        6
92989        6
94112        6
93088        6
94616        6
94760        6
93219        6
93287        6
97787        6
103268       6
103925       6
102807       6
104517       6
110522       6
113955       6
115025       6
114281       6
111501       6
118626       6
120065       6
120063       6
120059       6
122763       6
123630       6
123684       6
126869       6
127497       6
129712       6
2459         5
2335         5
2816         5
3739         5
3758         5
2470         5
3919         5
3942         5
3926         5
3953         5
4185         5
5437         5
5641         5
10454        5
13528        5
15528        5
17370        5
16899        5
25286        5
25393        5
26299        5
25375        5
28895        5
29668        5
29411        5
32116        5
31931        5
32163        5
32175        5
32227        5
32070        5
32075        5
32065        5
32072        5
33065        5
33615        5
33743        5
34559        5
31977        5
37597        5
39906        5
39308        5
49528        5
51006        5
51009        5
51017        5
49774        5
52461        5
52927        5
57517        5
57582        5
57839        5
59268        5
59510        5
57450        5
60807        5
61050        5
62018        5
62799        5
61767        5
64474        5
70135        5
70965        5
71219        5
71285        5
71283        5
73438        5
73448        5
77267        5
77728        5
79481        5
79360        5
79542        5
79363        5
79209        5
79207        5
78730        5
81478        5
81484        5
83207        5
88154        5
78266        5
88467        5
88778        5
88972        5
89801        5
90976        5
91309        5
93765        5
93879        5
94528        5
85994        5
95060        5
94990        5
95883        5
97136        5
97842        5
97843        5
97993        5
99417        5
102673       5
103653       5
104719       5
105925       5
107665       5
109990       5
110365       5
110534       5
111117       5
115011       5
107237       5
116475       5
118197       5
121225       5
122836       5
123170       5
119363       5
123390       5
122548       5
123914       5
123889       5
108635       5
129660       5
129817       5
129411       5
129867       5
2432         4
2772         4
2931         4
3931         4
3927         4
7806         4
8711         4
8168         4
11107        4
11477        4
12383        4
13435        4
12447        4
15685        4
15828        4
16140        4
16580        4
17987        4
18666        4
20312        4
24589        4
24227        4
23960        4
25093        4
26300        4
27036        4
28679        4
28748        4
28694        4
29267        4
29918        4
30318        4
29456        4
8872         4
27679        4
30988        4
32049        4
32069        4
32077        4
32076        4
32580        4
33737        4
33981        4
34459        4
36836        4
48606        4
49200        4
49380        4
49784        4
49823        4
6396         4
51682        4
51761        4
51796        4
52191        4
54666        4
56310        4
56465        4
56651        4
56636        4
57451        4
57551        4
25267        4
62647        4
62513        4
62905        4
64798        4
65385        4
65440        4
65509        4
65300        4
65659        4
66145        4
66355        4
68021        4
73436        4
829          4
76256        4
76535        4
78750        4
74612        4
79674        4
77986        4
81258        4
81481        4
81448        4
79495        4
82696        4
77244        4
84109        4
84200        4
84747        4
86137        4
87930        4
87228        4
88228        4
88366        4
88297        4
88784        4
91502        4
93808        4
92530        4
94422        4
94657        4
94649        4
94495        4
94679        4
94443        4
94466        4
93626        4
96770        4
97053        4
97118        4
97216        4
97456        4
97571        4
98032        4
93089        4
98656        4
99484        4
98868        4
100785       4
101594       4
98247        4
102808       4
61057        4
104402       4
102511       4
105571       4
106107       4
107492       4
107727       4
107088       4
109460       4
109466       4
110490       4
110085       4
110565       4
111559       4
111888       4
111861       4
110678       4
114339       4
115012       4
115013       4
115781       4
115971       4
119368       4
117730       4
120238       4
120276       4
120523       4
120914       4
120064       4
121705       4
122035       4
124713       4
124496       4
129675       4
129651       4
129772       4
130030       4
130212       4
129145       4
2519         3
2590         3
2652         3
3210         3
3384         3
3577         3
3731         3
3741         3
3952         3
3954         3
5771         3
7448         3
8704         3
10989        3
2411         3
10432        3
10988        3
13591        3
13854        3
13858        3
14194        3
15104        3
15707        3
15688        3
15730        3
15876        3
6555         3
16552        3
18256        3
18696        3
12803        3
22064        3
22037        3
22021        3
22080        3
8920         3
22079        3
22418        3
22549        3
11966        3
23371        3
23357        3
24504        3
24933        3
25463        3
26897        3
26939        3
27740        3
28624        3
29009        3
29570        3
29624        3
29595        3
29675        3
29689        3
29025        3
29696        3
29669        3
29769        3
29836        3
29833        3
29841        3
29844        3
29856        3
29893        3
29919        3
29914        3
11600        3
25083        3
29950        3
29935        3
29888        3
29981        3
29991        3
29982        3
29988        3
29971        3
29020        3
30018        3
29936        3
30019        3
29923        3
29870        3
30168        3
26777        3
30252        3
30262        3
30259        3
30274        3
30284        3
30003        3
30324        3
30327        3
30328        3
29649        3
30316        3
30267        3
30268        3
30311        3
30407        3
30390        3
30419        3
30446        3
30447        3
30453        3
30461        3
30466        3
27289        3
30515        3
32050        3
33636        3
33722        3
33976        3
33908        3
34555        3
36891        3
37510        3
38051        3
38066        3
38129        3
38289        3
39060        3
39463        3
39648        3
39680        3
40199        3
40406        3
39915        3
40394        3
40226        3
39306        3
42218        3
43345        3
39068        3
44595        3
48779        3
48781        3
48776        3
48780        3
49388        3
49524        3
50990        3
50994        3
50991        3
51005        3
51229        3
51122        3
49996        3
51695        3
51710        3
52331        3
53508        3
56390        3
56954        3
57542        3
58980        3
57952        3
61849        3
17650        3
62167        3
62895        3
62904        3
62826        3
62623        3
63973        3
61779        3
65386        3
65630        3
65726        3
62644        3
65794        3
66142        3
66177        3
66433        3
67410        3
68801        3
68913        3
69776        3
70166        3
71237        3
71294        3
70851        3
71977        3
71289        3
73088        3
72553        3
73250        3
74521        3
74652        3
76270        3
64954        3
76856        3
76855        3
77730        3
78779        3
79364        3
79667        3
79668        3
79756        3
79448        3
79212        3
79630        3
79208        3
81474        3
81494        3
81718        3
81845        3
82217        3
82588        3

Here, an overview of the users is created. More precisely, the number of users that made 1, 2-5, 6-10, 11-50, 51-100, 101-1000 and more than 1000 observations.

In [12]:
# uses User_freq

c1 = 0
c5 = 0
c10 = 0
c50 = 0
c100 = 0
c1000 = 0
c10000 = 0
for count in User_freq:
    if count == 1:
        c1 += 1
    elif count <= 5:
        c5 += 1
    elif count <= 10:
        c10 += 1
    elif count <= 50:
        c50 += 1
    elif count <= 100:
        c100 += 1
    elif count <= 1000:
        c1000 += 1
    else:
        c10000 += 1

bins = ["1 observation","2-5 observations","6-10 observations","11-50 observations", "51-100 observations","101-1000 observations",">1000 observations"]
counts = [c1,c5,c10,c50,c100,c1000,c10000]
bin_series = pd.Series(counts, index=bins)
total = c1+c5+c10+c50+c100+c1000+c10000

plt.figure(figsize=(16,9))
ax = bin_series.plot(kind="bar", color="teal", fontsize=12)

plt.title("Number of Users by Observation Count", fontsize=20)
plt.xlabel("Number of Observations per User", fontsize=17)
plt.ylabel("Number of Users", fontsize=17)
plt.xticks(rotation=90)

# Percentages above bars
#for p in ax.patches:
#    ax.annotate(
#        f'{round(int(p.get_height())/total*100,2)}%',
#        (p.get_x() + p.get_width()/2., p.get_height()),
#        ha='center',
#        va='bottom',
#        xytext=(0,5),
#        textcoords='offset points'
#    )

ax.grid(axis="y", linestyle="--", alpha=0.5)
ax.set_axisbelow(True)

plt.savefig(f"../Products/Users_per_obs_count.png", dpi=300, bbox_inches="tight")
plt.close()

Kernel Density Estimation to look at the density of observations

In [21]:
df = pd.read_csv("../CWData_clean7.csv")
df = df[(df["latitude"].between(-90, 90)) & (df["longitude"].between(-180, 180))]
world = gpd.read_file(f"../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")

# KDE
xy = np.vstack([df["longitude"], df["latitude"]])
kde = gaussian_kde(xy, bw_method=0.05)  # change bw_method for more/less smooting

# grid
lon_grid, lat_grid = np.meshgrid(
    np.linspace(-180, 180, 800),
    np.linspace(-90, 90, 400)
)
grid_coords = np.vstack([lon_grid.ravel(), lat_grid.ravel()])

z = kde(grid_coords).reshape(lon_grid.shape)
z_log = np.log1p(z)  # log scale, else we only see Europe
z_masked = np.where(z_log < 1e-5, np.nan, z_log) # do not show pixels without anything

fig, ax = plt.subplots(figsize=(16, 8), subplot_kw={"projection": ccrs.Robinson()})
ax.set_global()

ax.add_geometries(
    world.geometry,
    crs=ccrs.PlateCarree(),  # SHP is in WGS84
    facecolor="grey",
    edgecolor="grey",
    linewidth=0.5,
    zorder=1
)

# plot KDE
colors = ["#ffffff00", "#4393c3", "#2166ac", "#d6604d", "#b2182b"]
cmap = mcolors.LinearSegmentedColormap.from_list("cw_kde", colors)

vmin, vmax = np.nanmin(z_masked), np.nanpercentile(z_masked, 99) # clip highest percent to make rest of the world more colorful (not just Switzerland)

mesh = ax.pcolormesh(
    lon_grid, lat_grid, z_masked,
    transform=ccrs.PlateCarree(),
    cmap=cmap,
    shading="auto",
    zorder=2,
    alpha=0.85,
    vmax=vmax,
    vmin=vmin
)

ax.add_geometries(
    world.geometry,
    crs=ccrs.PlateCarree(),
    facecolor="none",
    edgecolor="black",
    linewidth=0.5,
    zorder=3
)

ticks = [vmin, vmin + (vmax-vmin)*0.25, vmin + (vmax-vmin)*0.5, vmin + (vmax-vmin)*0.75, vmax]
labels = ["Low", "", "Medium", "", "High"]

cbar = plt.colorbar(mesh, ax=ax, orientation="horizontal", pad=0.03, fraction=0.03)
cbar.set_label("Density (Log Scale)", fontsize=15)
cbar.set_ticks(ticks)
cbar.set_ticklabels(labels)
cbar.ax.tick_params(labelsize=12)

ax.set_title("Global Density of Observations using Kernel Density Estimation (KDE)", fontsize=18)

plt.savefig("../Products/KDE_global.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\1263467607.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Again, density: Hexbin

In [22]:
df = pd.read_csv("../CWData_clean7.csv")
df = df[(df["latitude"].between(-90, 90)) & (df["longitude"].between(-180, 180))]
world = gpd.read_file("../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")

fig, ax = plt.subplots(figsize=(16, 8), subplot_kw={"projection": ccrs.Robinson()})
ax.set_global()

# background
ax.add_geometries(
    world.geometry,
    crs=ccrs.PlateCarree(),
    facecolor="grey",
    edgecolor="grey",
    linewidth=0.5,
    zorder=1
)

# transform coordinates to Robinson
transformer = ccrs.Robinson().transform_points(
    ccrs.PlateCarree(),
    df["longitude"].values,
    df["latitude"].values
)
x_rob = transformer[:, 0]
y_rob = transformer[:, 1]

# Hexbin
cmap = plt.cm.YlOrRd
cmap.set_under(color="none")

hb = ax.hexbin(
    x_rob, y_rob,
    gridsize=100,
    bins="log",
    cmap=cmap,
    mincnt=1,
    zorder=2,
    transform=ccrs.Robinson(),
    linewidths=0
)

# country borders
ax.add_geometries(
    world.geometry,
    crs=ccrs.PlateCarree(),
    facecolor="none",
    edgecolor="black",
    linewidth=0.5,
    zorder=3
)

cbar = plt.colorbar(hb, ax=ax, orientation="horizontal", pad=0.03, fraction=0.03)
cbar.set_label("Number of Observations (Log Scale)", fontsize=15)
cbar.ax.tick_params(labelsize=12)
ax.set_title("Global Distribution of Observations (Hexbin)", fontsize=18)

plt.savefig("../Products/Hexbin_global.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\3507665843.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")

Then, the number of total observations per 1'000 km2 for each country is plotted on a map.

In [23]:
df = pd.read_csv("../CWData_clean7.csv")
df["created_at_local"] = pd.to_datetime(df["created_at_local"])

# dataframe with country and the number of observations in it
obs_per_country = (
    df
    .groupby("Country")
    .agg(
        total_observations = ("created_at_local","count"),
    )
    .reset_index()
)

pd.set_option("display.max_rows", None)

world = gpd.read_file(f"../Borders/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp", engine="fiona") # higher resolution map because of area accuracy
world = world.rename(columns={"NAME": "Country"})
world_area = gpd.read_file(f"../Borders/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp", engine="fiona") # higher resolution map because of area accuracy
world_area = world_area.to_crs("ESRI:54009") # area-true projection, Robinson skews it --> used for area calculations
obs_per_country["ISO_A3"] = obs_per_country["Country"].apply(own.get_iso3)

map_df = world.merge(obs_per_country, left_on="ADM0_A3", right_on="ISO_A3", how="left").to_crs("+proj=robin")
map_df_area = world_area.merge(obs_per_country, left_on="ADM0_A3", right_on="ISO_A3", how="left")

bins = [0,0.01,0.1,1,5,50,float("inf")]
labels = ["<0.01","0.01-0.1","0.11-1","1-5","5-50",">50"]
map_df_area["area_km2"] = map_df_area.geometry.area / 1e6 # area from map_df_area
map_df["area_km2"] = map_df_area["area_km2"].values # area transferred to map_df
map_df["obs_per_1000km2"] = map_df["total_observations"] / map_df["area_km2"] * 1000
map_df["cat_obs_per_1000km2"] = pd.cut(map_df["total_observations"] / map_df["area_km2"] * 1000, bins=bins, labels=labels)

fig, ax = plt.subplots(1, 1, figsize=(16, 8))

cmap = get_cmap("Reds", len(labels))
legend_handles = [
    Patch(facecolor=cmap(i / (len(labels) - 1)), edgecolor="black", linewidth=0.5, label=labels[i])
    for i in range(len(labels))
]
legend_handles.append(Patch(facecolor="grey", edgecolor="black", linewidth=0.5, label="No observations"))

map_df.plot(
    column="cat_obs_per_1000km2",
    cmap="Reds",
    linewidth=0.5,
    edgecolor="black",
    missing_kwds={"color": "grey"},
    legend=False,
    categorical=True,
    ax=ax
)

ax.legend(handles=legend_handles, title="Obs/1000km²", fontsize=12, title_fontsize=15, loc="lower left")
ax.set_title("Number of Observations per 1000 km²", fontsize=18)
ax.set_axis_off()

plt.savefig(f"../Products/number_of_obs_per_1000km2_per_Country.png", dpi=300, bbox_inches="tight")
plt.close()
map_df.to_csv("../Products/CSVs/obs_per_1000kms.csv", index=False)

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2481036292.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")
C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\2481036292.py:34: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = get_cmap("Reds", len(labels))

In [25]:
map_df[["Country_x", "obs_per_1000km2", "cat_obs_per_1000km2", "area_km2", "total_observations"]].sort_values("obs_per_1000km2", ascending=False)

,Country_x,obs_per_1000km2,cat_obs_per_1000km2,area_km2,total_observations
91,Switzerland,581.525823,>50,4.141862e+04,24086.0
222,Malta,435.089074,>50,3.263700e+02,142.0
94,Liechtenstein,182.237532,>50,1.371836e+02,25.0
7,Cyprus,100.229306,>50,5.407600e+03,542.0
88,Austria,74.419137,>50,8.394346e+04,6247.0
50,Estonia,36.800919,5-50,4.567821e+04,1681.0
49,Germany,35.612619,5-50,3.571768e+05,12720.0
93,Netherlands,24.801113,5-50,3.733703e+04,926.0
78,United Kingdom,22.274704,5-50,2.432804e+05,5419.0
57,Luxembourg,19.956978,5-50,2.605605e+03,52.0
77,Ireland,13.936366,5-50,6.931506e+04,966.0
28,Costa Rica,12.219408,5-50,5.147549e+04,629.0
12,Lebanon,8.574638,5-50,1.002958e+04,86.0
90,Italy,4.748609,1-5,3.013514e+05,1431.0
79,Greece,4.652661,1-5,1.315376e+05,612.0
140,Portugal,4.480510,1-5,9.150743e+04,410.0
68,Kyrgyzstan,3.941604,1-5,1.991575e+05,785.0
21,France,3.598775,1-5,6.371612e+05,2293.0
61,North Macedonia,3.266976,1-5,2.540575e+04,83.0
66,Spain,3.174625,1-5,5.074615e+05,1611.0
75,Slovakia,2.271950,1-5,4.841655e+04,110.0
117,Guatemala,2.165623,1-5,1.094373e+05,237.0
74,Hungary,1.953738,1-5,9.315475e+04,182.0
2,Chile,1.283167,1-5,7.380176e+05,947.0
103,Slovenia,1.131782,1-5,2.032193e+04,23.0
116,El Salvador,0.774362,0.11-1,2.066218e+04,16.0
59,Belgium,0.587664,0.11-1,3.062973e+04,18.0
53,Sweden,0.560193,0.11-1,4.444898e+05,249.0
48,Czechia,0.546566,0.11-1,7.867298e+04,43.0
1,Malaysia,0.472624,0.11-1,3.300722e+05,156.0
52,Norway,0.402220,0.11-1,3.803884e+05,153.0
96,Serbia,0.360620,0.11-1,7.764402e+04,28.0
182,Philippines,0.352435,0.11-1,2.950901e+05,104.0
102,Croatia,0.345310,0.11-1,5.502309e+04,19.0
136,Ecuador,0.268766,0.11-1,2.567290e+05,69.0
109,Bulgaria,0.221591,0.11-1,1.128203e+05,25.0
155,Canada,0.219328,0.11-1,9.916644e+06,2175.0
130,Montenegro,0.218424,0.11-1,1.373475e+04,3.0
70,Denmark,0.211318,0.11-1,4.258985e+04,9.0
154,United States of America,0.210265,0.11-1,9.469009e+06,1991.0
198,Trinidad and Tobago,0.193980,0.11-1,5.155177e+03,1.0
45,Uruguay,0.157448,0.11-1,1.778368e+05,28.0
43,Lithuania,0.123483,0.11-1,6.478608e+04,8.0
125,Rwanda,0.078508,0.01-0.1,2.547517e+04,2.0
76,Poland,0.073502,0.01-0.1,3.129170e+05,23.0
24,South Korea,0.070892,0.01-0.1,9.874141e+04,7.0
0,Indonesia,0.065526,0.01-0.1,1.892367e+06,124.0
54,Finland,0.063315,0.01-0.1,3.316773e+05,21.0
51,Latvia,0.062109,0.01-0.1,6.440299e+04,4.0
179,New Zealand,0.059543,0.01-0.1,2.687124e+05,16.0
188,Taiwan,0.055002,0.01-0.1,3.636220e+04,2.0
176,Australia,0.046224,0.01-0.1,7.723183e+06,357.0
26,Morocco,0.045473,0.01-0.1,5.937568e+05,27.0
10,Israel,0.045107,0.01-0.1,2.216956e+04,1.0
156,Mexico,0.040679,0.01-0.1,1.966640e+06,80.0
5,Argentina,0.039436,0.01-0.1,2.789349e+06,110.0
62,Albania,0.035259,0.01-0.1,2.836176e+04,1.0
16,Kenya,0.030527,0.01-0.1,5.896371e+05,18.0
191,Iceland,0.029426,0.01-0.1,1.019504e+05,3.0
127,Bangladesh,0.029086,0.01-0.1,1.375236e+05,4.0
132,Uganda,0.028750,0.01-0.1,2.434798e+05,7.0
56,Cambodia,0.021959,0.01-0.1,1.821607e+05,4.0
189,Japan,0.021381,0.01-0.1,3.741680e+05,8.0
135,Honduras,0.017716,0.01-0.1,1.128939e+05,2.0
44,Brazil,0.017363,0.01-0.1,8.523997e+06,148.0
73,Romania,0.016925,0.01-0.1,2.363335e+05,4.0
60,Georgia,0.014364,0.01-0.1,6.961775e+04,1.0
158,Panama,0.013331,0.01-0.1,7.501052e+04,1.0
137,Colombia,0.013127,0.01-0.1,1.142648e+06,15.0
4,Peru,0.011556,0.01-0.1,1.298027e+06,15.0
9,China,0.009048,<0.01,9.394406e+06,85.0
151,Ghana,0.008326,<0.01,2.402129e+05,2.0
13,Ethiopia,0.007932,<0.01,1.134603e+06,9.0
29,Nicaragua,0.007724,<0.01,1.294666e+05,1.0
92,Iran,0.007375,<0.01,1.627124e+06,12.0
40,Uzbekistan,0.006694,<0.01,4.481824e+05,3.0
146,Cameroon,0.006419,<0.01,4.673756e+05,3.0
36,South Africa,0.005718,<0.01,1.224180e+06,7.0
8,India,0.005687,<0.01,3.165389e+06,18.0
114,Chad,0.003926,<0.01,1.273567e+06,5.0
110,Thailand,0.003865,<0.01,5.174298e+05,2.0
161,Egypt,0.001990,<0.01,1.005119e+06,2.0
33,Ukraine,0.001750,<0.01,5.714563e+05,1.0
129,Afghanistan,0.001553,<0.01,6.438307e+05,1.0
41,Kazakhstan,0.001475,<0.01,2.712413e+06,4.0
122,Mozambique,0.001261,<0.01,7.927934e+05,1.0
99,Nigeria,0.001095,<0.01,9.132573e+05,1.0
105,Saudi Arabia,0.000518,<0.01,1.930318e+06,1.0
175,Antarctica,0.000244,<0.01,1.228165e+07,3.0
3,Bolivia,NaN,NaN,1.092895e+06,NaN
6,Dhekelia,NaN,NaN,1.277170e+02,NaN
11,Palestine,NaN,NaN,6.092424e+03,NaN
14,S. Sudan,NaN,NaN,6.309395e+05,NaN
15,Somalia,NaN,NaN,4.749313e+05,NaN
17,Malawi,NaN,NaN,1.201165e+05,NaN
18,Tanzania,NaN,NaN,9.476734e+05,NaN
19,Syria,NaN,NaN,1.863671e+05,NaN
20,Somaliland,NaN,NaN,1.684705e+05,NaN
22,Suriname,NaN,NaN,1.460908e+05,NaN
23,Guyana,NaN,NaN,2.126144e+05,NaN
25,North Korea,NaN,NaN,1.225198e+05,NaN
27,W. Sahara,NaN,NaN,9.089997e+04,NaN
30,Congo,NaN,NaN,3.472041e+05,NaN
31,Dem. Rep. Congo,NaN,NaN,2.340650e+06,NaN
32,Bhutan,NaN,NaN,4.057824e+04,NaN
34,Belarus,NaN,NaN,2.070948e+05,NaN
35,Namibia,NaN,NaN,8.266709e+05,NaN
37,St-Martin,NaN,NaN,6.865328e+01,NaN
38,Sint Maarten,NaN,NaN,2.348566e+01,NaN
39,Oman,NaN,NaN,3.127893e+05,NaN
42,Tajikistan,NaN,NaN,1.424544e+05,NaN
46,Mongolia,NaN,NaN,1.564041e+06,NaN
47,Russia,NaN,NaN,1.692397e+07,NaN
55,Vietnam,NaN,NaN,3.307267e+05,NaN
58,United Arab Emirates,NaN,NaN,7.140655e+04,NaN
63,Azerbaijan,NaN,NaN,8.634572e+04,NaN
64,Kosovo,NaN,NaN,1.091942e+04,NaN
65,Turkey,NaN,NaN,7.811714e+05,NaN
67,Laos,NaN,NaN,2.293390e+05,NaN
69,Armenia,NaN,NaN,2.962117e+04,NaN
71,Libya,NaN,NaN,1.630170e+06,NaN
72,Tunisia,NaN,NaN,1.570050e+05,NaN
80,Zambia,NaN,NaN,7.564204e+05,NaN
81,Sierra Leone,NaN,NaN,7.207267e+04,NaN
82,Guinea,NaN,NaN,2.458394e+05,NaN
83,Liberia,NaN,NaN,9.592388e+04,NaN
84,Central African Rep.,NaN,NaN,6.220333e+05,NaN
85,Sudan,NaN,NaN,1.866164e+06,NaN
86,Djibouti,NaN,NaN,2.198229e+04,NaN
87,Eritrea,NaN,NaN,1.232475e+05,NaN
89,Iraq,NaN,NaN,4.385641e+05,NaN
95,Côte d'Ivoire,NaN,NaN,3.227597e+05,NaN
97,Mali,NaN,NaN,1.259626e+06,NaN
98,Senegal,NaN,NaN,1.973835e+05,NaN
100,Benin,NaN,NaN,1.168511e+05,NaN
101,Angola,NaN,NaN,1.252237e+06,NaN
104,Qatar,NaN,NaN,1.119780e+04,NaN
106,Botswana,NaN,NaN,5.818149e+05,NaN
107,Zimbabwe,NaN,NaN,3.914036e+05,NaN
108,Pakistan,NaN,NaN,8.758924e+05,NaN
111,San Marino,NaN,NaN,6.033296e+01,NaN
112,Haiti,NaN,NaN,2.703459e+04,NaN
113,Dominican Rep.,NaN,NaN,4.869790e+04,NaN
115,Kuwait,NaN,NaN,1.753511e+04,NaN
118,Timor-Leste,NaN,NaN,1.517902e+04,NaN
119,Brunei,NaN,NaN,5.754598e+03,NaN
120,Monaco,NaN,NaN,1.884544e+01,NaN
121,Algeria,NaN,NaN,2.317479e+06,NaN
123,eSwatini,NaN,NaN,1.718102e+04,NaN
124,Burundi,NaN,NaN,2.722241e+04,NaN
126,Myanmar,NaN,NaN,6.664461e+05,NaN
128,Andorra,NaN,NaN,4.525055e+02,NaN
131,Bosnia and Herz.,NaN,NaN,5.183734e+04,NaN
133,USNB Guantanamo Bay,NaN,NaN,6.569651e+01,NaN
134,Cuba,NaN,NaN,1.104688e+05,NaN
138,Paraguay,NaN,NaN,4.017557e+05,NaN
139,Brazilian I.,NaN,NaN,2.834023e+00,NaN
141,Moldova,NaN,NaN,3.318992e+04,NaN
142,Turkmenistan,NaN,NaN,4.715032e+05,NaN
143,Jordan,NaN,NaN,8.913984e+04,NaN
144,Nepal,NaN,NaN,1.476533e+05,NaN
145,Lesotho,NaN,NaN,3.021060e+04,NaN
147,Gabon,NaN,NaN,2.617182e+05,NaN
148,Niger,NaN,NaN,1.187814e+06,NaN
149,Burkina Faso,NaN,NaN,2.744400e+05,NaN
150,Togo,NaN,NaN,5.722939e+04,NaN
152,Guinea-Bissau,NaN,NaN,3.303111e+04,NaN
153,Gibraltar,NaN,NaN,3.699983e+00,NaN
157,Belize,NaN,NaN,2.242138e+04,NaN
159,Venezuela,NaN,NaN,9.186235e+05,NaN
160,Papua New Guinea,NaN,NaN,4.682049e+05,NaN
162,Yemen,NaN,NaN,4.556674e+05,NaN
163,Mauritania,NaN,NaN,1.041681e+06,NaN
164,Eq. Guinea,NaN,NaN,2.685092e+04,NaN
165,Gambia,NaN,NaN,1.056420e+04,NaN
166,Hong Kong,NaN,NaN,1.041164e+03,NaN
167,Vatican,NaN,NaN,1.221281e-02,NaN
168,N. Cyprus,NaN,NaN,3.326861e+03,NaN
169,Cyprus U.N. Buffer Zone,NaN,NaN,3.417791e+02,NaN
170,Siachen Glacier,NaN,NaN,2.092209e+03,NaN
171,Baikonur,NaN,NaN,6.500075e+03,NaN
172,Akrotiri,NaN,NaN,9.892017e+01,NaN
173,Southern Patagonian Ice Field,NaN,NaN,1.407512e+03,NaN
174,Bir Tawil,NaN,NaN,2.029125e+03,NaN
177,Greenland,NaN,NaN,2.142676e+06,NaN
178,Fiji,NaN,NaN,1.903424e+04,NaN
180,New Caledonia,NaN,NaN,1.893452e+04,NaN
181,Madagascar,NaN,NaN,5.960827e+05,NaN
183,Sri Lanka,NaN,NaN,6.672248e+04,NaN
184,Curaçao,NaN,NaN,4.660866e+02,NaN
185,Aruba,NaN,NaN,1.708041e+02,NaN
186,Bahamas,NaN,NaN,1.266046e+04,NaN
187,Turks and Caicos Is.,NaN,NaN,4.473969e+02,NaN
190,St. Pierre and Miquelon,NaN,NaN,2.426400e+02,NaN
192,Pitcairn Is.,NaN,NaN,4.275893e+01,NaN
193,Fr. Polynesia,NaN,NaN,3.355681e+03,NaN
194,Fr. S. Antarctic Lands,NaN,NaN,7.273233e+03,NaN
195,Seychelles,NaN,NaN,4.385194e+02,NaN
196,Kiribati,NaN,NaN,9.562440e+02,NaN
197,Marshall Is.,NaN,NaN,1.658853e+02,NaN
199,Grenada,NaN,NaN,3.493908e+02,NaN
200,St. Vin. and Gren.,NaN,NaN,3.699513e+02,NaN
201,Barbados,NaN,NaN,4.468764e+02,NaN
202,Saint Lucia,NaN,NaN,6.087477e+02,NaN
203,Dominica,NaN,NaN,7.345382e+02,NaN
204,U.S. Minor Outlying Is.,NaN,NaN,2.816630e+01,NaN
205,Montserrat,NaN,NaN,1.001545e+02,NaN
206,Antigua and Barb.,NaN,NaN,4.543568e+02,NaN
207,St. Kitts and Nevis,NaN,NaN,2.655919e+02,NaN
208,U.S. Virgin Is.,NaN,NaN,3.567267e+02,NaN
209,St-Barthélemy,NaN,NaN,2.455534e+01,NaN
210,Puerto Rico,NaN,NaN,9.054783e+03,NaN
211,Anguilla,NaN,NaN,8.789382e+01,NaN
212,British Virgin Is.,NaN,NaN,1.457174e+02,NaN
213,Jamaica,NaN,NaN,1.109282e+04,NaN
214,Cayman Is.,NaN,NaN,3.108251e+02,NaN
215,Bermuda,NaN,NaN,6.248233e+01,NaN
216,Heard I. and McDonald Is.,NaN,NaN,3.941067e+02,NaN
217,Saint Helena,NaN,NaN,3.681740e+02,NaN
218,Mauritius,NaN,NaN,2.024775e+03,NaN
219,Comoros,NaN,NaN,1.682494e+03,NaN
220,São Tomé and Principe,NaN,NaN,1.044146e+03,NaN
221,Cabo Verde,NaN,NaN,3.949174e+03,NaN
223,Jersey,NaN,NaN,1.189338e+02,NaN
224,Guernsey,NaN,NaN,7.390919e+01,NaN
225,Isle of Man,NaN,NaN,5.735983e+02,NaN
226,Åland,NaN,NaN,9.388728e+02,NaN
227,Faeroe Is.,NaN,NaN,1.323530e+03,NaN
228,Indian Ocean Ter.,NaN,NaN,1.126311e+02,NaN
229,Br. Indian Ocean Ter.,NaN,NaN,4.937547e+01,NaN
230,Singapore,NaN,NaN,5.139398e+02,NaN
231,Norfolk Island,NaN,NaN,4.129332e+01,NaN
232,Cook Is.,NaN,NaN,1.921210e+02,NaN
233,Tonga,NaN,NaN,6.062253e+02,NaN
234,Wallis and Futuna Is.,NaN,NaN,1.401632e+02,NaN
235,Samoa,NaN,NaN,2.797054e+03,NaN
236,Solomon Is.,NaN,NaN,2.737326e+04,NaN
237,Tuvalu,NaN,NaN,2.316562e+01,NaN
238,Maldives,NaN,NaN,1.094678e+02,NaN
239,Nauru,NaN,NaN,2.896101e+01,NaN
240,Micronesia,NaN,NaN,6.379736e+02,NaN
241,S. Geo. and the Is.,NaN,NaN,3.912856e+03,NaN
242,Falkland Is.,NaN,NaN,1.157929e+04,NaN
243,Vanuatu,NaN,NaN,1.236673e+04,NaN
244,Niue,NaN,NaN,2.217545e+02,NaN
245,American Samoa,NaN,NaN,1.813758e+02,NaN
246,Palau,NaN,NaN,4.951428e+02,NaN
247,Guam,NaN,NaN,5.675752e+02,NaN
248,N. Mariana Is.,NaN,NaN,5.825950e+02,NaN
249,Bahrain,NaN,NaN,6.909460e+02,NaN
250,Coral Sea Is.,NaN,NaN,2.083603e-02,NaN
251,Spratly Is.,NaN,NaN,1.205574e+01,NaN
252,Clipperton I.,NaN,NaN,5.033477e+00,NaN
253,Macao,NaN,NaN,3.022115e+01,NaN
254,Ashmore and Cartier Is.,NaN,NaN,2.711974e+00,NaN
255,Bajo Nuevo Bank,NaN,NaN,3.606980e-02,NaN
256,Serranilla Bank,NaN,NaN,1.058941e-01,NaN
257,Scarborough Reef,NaN,NaN,9.835498e-02,NaN

Now, I will also look at the spatial autocorrelation

In [28]:
df = pd.read_csv("../CWData_clean7.csv")
df["year_month"] = pd.to_datetime(df["year_month"]).dt.to_period("M")
df["year"] = df["year_month"].dt.year
df["lon_bin"] = np.floor(df["longitude"]).astype(int)
df["lat_bin"] = np.floor(df["latitude"]).astype(int)

world = gpd.read_file("../Borders/ne_110m_admin_0_countries/ne_110m_admin_0_countries.shp", engine="fiona")

# create full grid with 1° grid cells
lon_bins = np.arange(-180, 180)
lat_bins = np.arange(-90, 90)
grid = pd.MultiIndex.from_product([lat_bins, lon_bins], names=["lat_bin", "lon_bin"]).to_frame(index=False)

all_years = sorted(df["year"].unique())

# LISA colors
lisa_colors = {
    "HH": "red",  # High-High Hotspot
    "HL": "orange",  # High-Low Outlier
    "LH": "lightblue",  # Low-High Outlier
    "ns": "white"   # non-significant
}

# observations per grid cell
counts = (
    df
    .groupby(["lat_bin", "lon_bin"])
    .size()
    .reset_index(name="n_obs")
)

grid_year = grid.merge(counts, on=["lat_bin", "lon_bin"], how="left").fillna(0)
grid_active = grid_year[grid_year["n_obs"] > 0].copy() # ignore cells without any observations

grid_active["geometry"] = grid_active.apply(
    lambda row: box(row["lon_bin"], row["lat_bin"], row["lon_bin"] + 1, row["lat_bin"] + 1),
    axis=1
)
gdf_active = gpd.GeoDataFrame(grid_active, geometry="geometry", crs="EPSG:4326")

gdf_metric = gdf_active.to_crs("EPSG:3857") # metric CRS for distance-based neighborhood (because else neighors might be very far away because of empty cells)

w = DistanceBand.from_dataframe(gdf_metric, threshold=500000, silence_warnings=True)
isolated = [i for i, neighbors in w.neighbors.items() if len(neighbors) == 0]
gdf_metric = gdf_metric.drop(index=isolated).reset_index(drop=True)

w = DistanceBand.from_dataframe(gdf_metric, threshold=500000, silence_warnings=True)
w.transform = "r"

y = gdf_metric["n_obs"].values

# seed makes it reproducible
np.random.seed(1)

# calculate LISA
lisa = Moran_Local(y, w, permutations=999, seed=1)

# calculate Moran's I globally
moran = Moran(y, w, permutations=999)

# significance: p < 0.05
sig = lisa.p_sim < 0.1
quads = lisa.q  # 1=HH, 2=LH, 3=LL, 4=HL
quad_map = {1: "HH", 2: "LH", 3: "LL", 4: "HL"}

gdf_metric["lisa_cat"] = "ns"
gdf_metric.loc[sig, "lisa_cat"] = [quad_map[q] for q in quads[sig]]

gdf_metric = gdf_metric.to_crs("+proj=robin")
gdf_sig = gdf_metric[gdf_metric["lisa_cat"] != "ns"] # only plot significant cells

fig, ax = plt.subplots(1, 1, figsize=(16, 8))

world.to_crs("+proj=robin").plot(
    ax=ax, color="grey", edgecolor="black", linewidth=0.5, zorder=1
)

for cat, color in lisa_colors.items():
    if cat == "ns":
        continue
    subset = gdf_sig[gdf_sig["lisa_cat"] == cat]
    if len(subset) > 0:
        subset.plot(ax=ax, color=color, zorder=2, alpha=0.8)

patches = [
    mpatches.Patch(facecolor=lisa_colors["HH"], edgecolor="black", linewidth=0.5, label="High-High (Hotspot)"),
    mpatches.Patch(facecolor=lisa_colors["HL"], edgecolor="black", linewidth=0.5, label="High-Low (Outlier)"),
    mpatches.Patch(facecolor=lisa_colors["LH"], edgecolor="black", linewidth=0.5, label="Low-High (Outlier)"),
]
legend = ax.legend(handles=patches, title="LISA Cluster (α = 0.1)", loc="lower left", frameon=True)
legend.get_title().set_fontsize(15)
for text in legend.get_texts():
    text.set_fontsize(12)

ax.set_title(f"Local Indicators of Spatial Autocorrelation (LISA)", fontsize=18)

# write Moran's I on map
ax.text(
    0.011, 0.93,
    f"Moran's I = {moran.I:.3f} (p = {moran.p_sim:.3f})",
    transform=ax.transAxes,
    fontsize=12,
    verticalalignment="bottom",
    bbox=dict(boxstyle="round", facecolor="white")
)

ax.set_axis_off()

# Inset for Europe
ax_inset = fig.add_axes([0.129, 0.245, 0.2, 0.3])  # [left, bottom, width, height] in figure fraction

world.to_crs("+proj=robin").plot(
    ax=ax_inset, color="grey", edgecolor="black", linewidth=0.5, zorder=1
)

for cat, color in lisa_colors.items():
    if cat == "ns":
        continue
    subset = gdf_sig[gdf_sig["lisa_cat"] == cat]
    if len(subset) > 0:
        subset.plot(ax=ax_inset, color=color, zorder=2, alpha=0.8)

# extent of Europe
ax_inset.set_xlim(-1000000, 2500000)
ax_inset.set_ylim(3700000, 6500000)
ax_inset.set_axis_off()
ax_inset.set_title("Europe", fontsize=15)

ax_inset.set_axis_off()

# border of inset
rect = Rectangle((0, 0), 1, 1, transform=ax_inset.transAxes,
                 fill=False, edgecolor="black", linewidth=2, zorder=10)
ax_inset.add_patch(rect)

plt.savefig(f"../Products/LISA.png", dpi=300, bbox_inches="tight")
plt.close()

C:\Users\yanni\AppData\Local\Temp\ipykernel_31884\3671233021.py:1: DtypeWarning: Columns (0: Plastic_Amount, 1: Plastic_Location, 2: Plastic_RiverWidth, 3: Plastic_PET, 4: Plastic_POSoft, 5: Plastic_POHard, 6: Plastic_PS, 7: Plastic_PSE, 8: Plastic_PMultilayer, 9: Plastic_POther, 10: Plastic_Shore_Plotsize, 11: Plastic_Removed, 12: Plastic_River_Stagnant, 13: Waterlevel_Physical_Unit, 14: Streamtype, 15: Swimming_Quality, 16: Drinking_Quality, 17: Naturality, 18: StreamColor, 19: Stream_Ground_Visibility, 20: Stream_Animals, 21: Stream_Pollution_Reason, 22: Stream_sometimes_dry, 23: Stream_Name, 24: TempStream_snow_ice, 25: Stream_Waterquality, 26: Stream_Waterclarity, 27: StreamColor_other, 28: Stream_Vegetation, 29: Stream_Foam, 30: Stream_Algae, 31: Stream_Odor, 32: Stream_Odor_Type, 33: Stream_Odor_Type_other, 34: Stream_Litter, 35: Stream_Flow_Alteration, 36: Stream_typical_Color, 37: Stream_Drainage_Basin, 38: Lake_Usage, 39: Lake_Usage_Nr, 40: Lake_Access, 41: Lake_Shore_State, 42: Lake_Swimming, 43: Lake_Transparency, 44: Lake_Color, 45: Lake_Odor, 46: Lake_Shore_Vegetation, 47: Lake_Shore_Vegetation_Nr, 48: Lake_Underwater_Vegetation, 49: Lake_Floating_Leaveplants, 50: Lake_Duckweed, 51: Lake_Mussels, 52: Lake_Deadwood, 53: Lake_Animals, 54: Lake_Animals_Nr, 55: Lake_Waterlevel_Changes, 56: Lake_Dry) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../CWData_clean7.csv")